SET SERVEROUTPUT ON

--FOLOSIND O COLECTIE SA SE AFISEZE NUMELE ANG DIN DEP SA_REPT CU SALARILE INTRE 5000 SI 9000
--ANG VOR FI AFISATI IN ORDINEA DESC A VAL

DECLARE 
    TYPE R_ANG IS RECORD(
    NUME VARCHAR2(30),
    PRENUME VARCHAR2(30),
    SALARIUL NUMBER);
    
    TYPE T_ANG IS TABLE OF R_ANG INDEX BY PLS_INTEGER;
    V T_ANG;
    I PLS_INTEGER;
BEGIN
    SELECT NUME,PRENUME,SALARIUL
    BULK COLLECT INTO V
    FROM ANGAJATI
    WHERE ID_FUNCTIE='SA_REP'
    AND SALARIUL BETWEEN 5000 AND 9000
    ORDER BY SALARIUL DESC;
    
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
         DBMS_OUTPUT.PUT_LINE(V(I).NUME || ' ' ||V(I).PRENUME||' ' ||'Salariul='||V(I).SALARIUL);
         I:=V.NEXT(I);
    END LOOP;
END;
/

--Folosind o colectie sa se afiseze denumirea produselor,valoara totala a comenzilor 
--precum si data ultimei 
--comenzi pt produsul respectiv
-- Se vor afisa produsele ordonate desc dupa data ultimei comenzi

DECLARE
    TYPE R_PR IS RECORD(
    DENUMIRE_PRODUS VARCHAR2(50),
    VALOARE_TOTALA NUMBER,
    DATA_ULTIMA_COMANDA TIMESTAMP);
    
    TYPE T_PR IS TABLE OF R_PR INDEX BY PLS_INTEGER;
    V T_PR;
    I PLS_INTEGER;
BEGIN
    SELECT P.DENUMIRE_PRODUS,
    SUM(RC.CANTITATE * RC.PRET) AS VALOARE_TOTALA,
    MAX(C.DATA) AS DATA_ULTIMA_COMANDA
    BULK COLLECT INTO V
    FROM PRODUSE P
    JOIN RAND_COMENZI RC ON P.ID_PRODUS=RC.ID_PRODUS
    JOIN COMENZI C ON RC.ID_COMANDA=C.ID_COMANDA
    GROUP BY P.DENUMIRE_PRODUS
    ORDER BY MAX(C.DATA) DESC;
    
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(V(I).denumire_produs || ' || Total=' || V(I).valoare_totala ||  ' || Ultima comanda=' || V(I).data_ultima_comanda);
        I:=V.NEXT(I);
    END LOOP;
    
END;
/

DECLARE
    TYPE R_PR IS RECORD(
    DENUMIRE_PRODUS VARCHAR2(50),
    VALOARE_TOTALA NUMBER,
    DATA_ULTIMA_COMANDA TIMESTAMP);
    
    TYPE T_PR IS TABLE OF R_PR; --NESTED TABLE
    V T_PR;
    I PLS_INTEGER;
BEGIN
    SELECT P.DENUMIRE_PRODUS,
    SUM(RC.CANTITATE * RC.PRET) AS VALOARE_TOTALA,
    MAX(C.DATA) AS DATA_ULTIMA_COMANDA
    BULK COLLECT INTO V
    FROM PRODUSE P
    JOIN RAND_COMENZI RC ON P.ID_PRODUS=RC.ID_PRODUS
    JOIN COMENZI C ON RC.ID_COMANDA=C.ID_COMANDA
    GROUP BY P.DENUMIRE_PRODUS
    ORDER BY MAX(C.DATA) DESC;
    
    V.TRIM;--STERGERE ULTIMUL EL;
    
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(V(I).denumire_produs || ' || Total=' || V(I).valoare_totala ||  ' || Ultima comanda=' || V(I).data_ultima_comanda);
        I:=V.NEXT(I);
    END LOOP;
    V.DELETE;
    
END;
/


DECLARE
    TYPE R_PR IS RECORD(
    DENUMIRE_PRODUS VARCHAR2(50),
    VALOARE_TOTALA NUMBER,
    DATA_ULTIMA_COMANDA TIMESTAMP);
    
    TYPE T_PR IS VARRAY(200) OF R_PR;
    V T_PR;
    I PLS_INTEGER;
BEGIN
    SELECT P.DENUMIRE_PRODUS,
    SUM(RC.CANTITATE * RC.PRET) AS VALOARE_TOTALA,
    MAX(C.DATA) AS DATA_ULTIMA_COMANDA
    BULK COLLECT INTO V
    FROM PRODUSE P
    JOIN RAND_COMENZI RC ON P.ID_PRODUS=RC.ID_PRODUS
    JOIN COMENZI C ON RC.ID_COMANDA=C.ID_COMANDA
    GROUP BY P.DENUMIRE_PRODUS
    ORDER BY MAX(C.DATA) DESC;
    
    V.TRIM;
    V.TRIM(5);
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(V(I).denumire_produs || ' || Total=' || V(I).valoare_totala ||  ' || Ultima comanda=' || V(I).data_ultima_comanda);
        I:=V.NEXT(I);
    END LOOP;
    
END;
/



--SA SE MAREASCA CU 5$% SALARIUL ANG CARE AU INTERMEDIAT CEL PUTIN 2 COMENZI. 
--SA SE AFISEZE NR SALARIILOR MARITE

BEGIN
    UPDATE ANGAJATI
    SET SALARIUL=SALARIUL*1.05
    WHERE ID_ANGAJAT IN (
    SELECT ID_ANGAJAT
    FROM COMENZI 
    GROUP BY ID_ANGAJAT
    HAVING COUNT(*)>=2);
    
    IF SQL%FOUND THEN
         DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
    END IF;
END;
/

-- SA SE STEARGA TOATE PRODUSELE CARE NU FOST COMANDATE NICIODATA
--SA SE AFISEZE NR DE PRODUSE STERSE PRECUM SI DENUMIREA LOC
DECLARE 
    TYPE T_PROD IS TABLE OF VARCHAR(200);
    V T_PROD;
BEGIN
    DELETE FROM PRODUSE
    WHERE ID_PRODUS NOT IN (
    SELECT ID_PRODUS
    FROM RAND_COMENZI
    GROUP BY ID_PRODUS)RETURNING DENUMIRE_PRODUS BULK COLLECT INTO V;
    
    DBMS_OUTPUT.PUT_LINE(V.COUNT);
    
    FOR I in 1..V.COUNT LOOP
        DBMS_OUTPUT.PUT_LINE(V(I));
    END LOOP;
END;
/
ROLLBACK;

--FOLOSIND UN CURSOR SA SE AFISEZE NUMELE SI PRENUMELE CLIENT 
--CARE AU DAT CEL PIUTIN 2 COMENZI
--CLIENTII SE VOR AFISA IN ORDINEA DESC A LIMIT CREDIT

DECLARE
    CURSOR C IS SELECT NUME_CLIENT,PRENUME_CLIENT,LIMITA_CREDIT
                    FROM CLIENTI
                    WHERE ID_CLIENT IN ( SELECT ID_CLIENT 
                    FROM COMENZI 
                    GROUP BY ID_CLIENT
                    HAVING COUNT(*)>=2)
                    ORDER BY LIMITA_CREDIT DESC
                    FETCH FIRST 5 ROWS ONLY;
        
    R C%ROWTYPE;
BEGIN
    IF NOT C%ISOPEN THEN
        OPEN C;
    END IF;
    LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND;
        
        DBMS_OUTPUT.PUT_LINE(C%ROWCOUNT||' '||R.NUME_CLIENT||' '||R.PRENUME_CLIENT||' '||R.LIMITA_CREDIT);
    END LOOP;
    
    CLOSE C;
END;
/

--FOLOSIND UN CURSOR SA SE AFISEZE DENUMIREA DEPARTAMENTELOR
--UNDE TOTI ANGAJATII AU SALARILE <=10000

DECLARE
    CURSOR C IS SELECT
    DENUMIRE_DEPARTAMENT
    FROM DEPARTAMENTE
    WHERE ID_DEPARTAMENT IN(
    SELECT ID_DEPARTAMENT
    FROM ANGAJATI
    GROUP BY ID_DEPARTAMENT
    HAVING MAX(SALARIUL)<=10000);
    
    R C%ROWTYPE;
BEGIN
    IF NOT C%ISOPEN THEN
        OPEN C;
    END IF;
    LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(R.DENUMIRE_DEPARTAMENT);
    END LOOP;
    CLOSE C;
END;
/

--FOLOSIND UN CURSOR,
--SA SE AFISEZE DENUMIREA CATEGORIILOR DE PRODUSE SI VALOAREA TOTALA A COMENZILOR
--DIN PERSPECTIVELE CATEGORII. SE VOR AFISA DOAR CATEG CU VAL TOTALA A COMENZILOR >500000

DECLARE
    CURSOR C IS SELECT
    P.CATEGORIE,
    SUM(R.PRET * R.CANTITATE) VAL_T
    FROM PRODUSE P
    JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
    GROUP BY P.CATEGORIE
    HAVING SUM(R.PRET * R.CANTITATE)>50000;
BEGIN
    FOR R IN C LOOP
        DBMS_OUTPUT.PUT_LINE(R.CATEGORIE);
    END LOOP;
END;
/
--FOLOSIND UN CURSOR, SA SE AFISEZE DENUMIREA CATEGORIILOR DE PRODUSE SI VALOAREA TOTALA A COMENZILOR
--DIN PERSPECTIVELE CATEGORII. SE VOR AFISA DOAR CATEG CU VAL TOTALA A COMENZILOR >500000
--PT FIECARE CATEOGIRE SE VOR AFISA PRODUSELE DIN ACEA CATEGORIE SI VALOAREA TOALA COMENZILOR

DECLARE
    CURSOR C IS SELECT
    P.CATEGORIE,
    SUM(R.PRET * R.CANTITATE) VAL_T
    FROM PRODUSE P
    JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
    GROUP BY P.CATEGORIE
    HAVING SUM(R.PRET* R.CANTITATE)>50000;
    
    CURSOR D(P_CATEG VARCHAR2) IS SELECT
    P.DENUMIRE_PRODUS,
    P.CATEGORIE,
    SUM(R.PRET * R.CANTITATE) VAL_T
    FROM PRODUSE P,RAND_COMENZI R
    WHERE P.ID_PRODUS=R.ID_PRODUS
    AND P.CATEGORIE=P_CATEG
    GROUP BY P.DENUMIRE_PRODUS,P.CATEGORIE;
BEGIN
    FOR R IN C LOOP
        DBMS_OUTPUT.PUT_LINE(R.CATEGORIE);
        FOR S IN D(R.CATEGORIE) LOOP
            DBMS_OUTPUT.PUT_LINE(S.DENUMIRE_PRODUS||':'||S.VAL_T);
        END LOOP;
    END LOOP;
END;
/

--SA SE AFISEZE NUMELE SI PRENUMELE CLIENTULUI CARE A DAT CELE MAI MULTE COMENZI
--SE VOR AFISA COMENZILE PT RESPECTIVUL CLIENT 
-- ID_COMANDA, DATA, VAL TOATALA

DECLARE
    CURSOR C1 IS SELECT
    C.ID_CLIENT,
    C.NUME_CLIENT,
    C.PRENUME_CLIENT,
    COUNT(*) NR_COM
    FROM CLIENTI C
    JOIN COMENZI CO ON C.ID_CLIENT=CO.ID_CLIENT
    GROUP BY C.ID_CLIENT,C.NUME_CLIENT,C.PRENUME_CLIENT
    ORDER BY COUNT(*) DESC FETCH FIRST 1 ROW WITH TIES;
    
    CURSOR C2(P_ID NUMBER) IS SELECT
        C.ID_COMANDA,
        C.DATA,
        SUM(R.PRET * R.CANTITATE) VAL_TOT
        FROM COMENZI C
        JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
        WHERE C.ID_CLIENT=P_ID
        GROUP BY C.ID_COMANDA,DATA;
BEGIN

    FOR R1 IN C1 LOOP
        DBMS_OUTPUT.PUT_LINE('Client: ' || R1.nume_client || ' ' || R1.prenume_client);
        FOR R2 IN C2(R1.ID_CLIENT) LOOP
         DBMS_OUTPUT.PUT_LINE('Comanda: ' || R2.id_comanda ||' Data: ' || R2.data||' Total: ' || R2.val_tot);
        END LOOP;
    END LOOP;
END;
/

--CURSORUL FOR UPDATE -PUTEM SA ACTUALIZAM PE MASURA CE PARC CURSORUL

--FOLOSIND UN CURSOR SA SE MAREASCA CU 5% PRETUL DE LISTA PT 
--PRODUSELE CARE APAR IN CEL PUTIN 5 COMENZI DISTINCTE

DECLARE
    CURSOR C IS SELECT
    P.ID_PRODUS,
    P.DENUMIRE_PRODUS,
    P.PRET_LISTA
    FROM PRODUSE P
    WHERE P.ID_PRODUS IN (SELECT R.ID_PRODUS 
                             FROM RAND_COMENZI R
                             GROUP BY R.ID_PRODUS
                             HAVING COUNT(R.ID_PRODUS)>=5) FOR UPDATE WAIT 10;
BEGIN
    FOR R IN C LOOP
        UPDATE PRODUSE
        SET PRET_LISTA=PRET_LISTA*1.05
        WHERE CURRENT OF C;
        DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS||' '||R.DENUMIRE_PRODUS||' '||R.PRET_LISTA); 
    END LOOP;
    
    DBMS_OUTPUT.NEW_LINE;
  
  FOR R IN C LOOP     
     DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS||' '||R.DENUMIRE_PRODUS||' '||R.PRET_LISTA);
   END LOOP;
END;
/


--FOLOSIND O EXCEPTIE SA SE REZOLVE URMATOAREA CERINTA
--SA SE ADAUGE UN ANGAJAT CU ID-UL CITIT DE LA TASTARU SI SALARIUL CITIT DE LA TASTATURA
--DACA ANGAJATUL EXISTA, I SE VA MODIFCA SALARIUL CU CEL CITIT


ACCEPT P_ID_ANG PROMPT "INTRODUCETI ID";
ACCEPT P_SALARIUL PROMPT "INRODUCETI SAL";
BEGIN
    INSERT INTO ANGAJATI(ID_ANGAJAT,NUME,EMAIL,ID_FUNCTIE,DATA_ANGJARE,SALARIUL)
    VALUES (&P_ID_ANG,'JOHNSON','JOHNSON@GMAIL.COM','SA_REP',SYSDATE-30, &P_SALARIUL);
    
    EXCEPTION 
        WHEN DUP_VAL_ON_INDEX THEN
            UPDATE ANGAJATI
            SET SALARIUL=&P_SALARIUL WHERE ID_ANGAJAT=&P_ID_ANG;
END;
/
CREATE TABLE PERSOANE(ID_PERS NUMBER,NUME VARCHAR2(30),PRENUME VARCHAR2(30));

DECLARE
    TABELA_EXISTA EXCEPTION;
    PRAGMA EXCEPTION_INIT(TABELA_EXISTA,-955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE PERSOANE(ID_PERS NUMBER,NUME VARCHAR2(30),PRENUME VARCHAR2(30))';
    EXECUTE IMMEDIATE 'INSERT INTO PERSOANE VALUES(1,''POPESCU'',''MARIUS'')';
    DBMS_OUTPUT.PUT_LINE('AM ADAUGAT RANDUL');
    EXCEPTION 
        WHEN TABELA_EXISTA THEN
            EXECUTE IMMEDIATE 'DROP TABLE PERSOANE';
         DBMS_OUTPUT.PUT_LINE('AM STERS TABELA');
END;
/

--SA SE MODIFICE PROCEDURA ASTFEL INCAT SA SE AFISEZE SI PRRETUL NOU
CREATE OR REPLACE PROCEDURE M(P_ID_PRODUS NUMBER,P_PROCENT NUMBER) IS
V_PRET_NOU NUMBER;
BEGIN
    UPDATE PRODUSE
    SET PRET_LISTA=PRET_LISTA*(100+P_PROCENT)/100 
    WHERE ID_PRODUS=P_ID_PRODUS;
    
    SELECT PRET_LISTA INTO V_PRET_NOU
    FROM PRODUSE
    WHERE ID_PRODUS=P_ID_PRODUS;
    
    DBMS_OUTPUT.PUT_LINE('Pretul nou este: ' || V_PRET_NOU);
    EXCEPTION 
        WHEN NO_DATA_FOUND THEN NULL;
END;
/



-- SA SE CONSTRUIASACA O PROCEDURA CARE PRIMESTE O CATEG DE PRODUSE SI AFISEAZA DENUMIREA 
--FIECAURI PRODUS DIN ACEEA CATEGORIE PRECUM SI VALOAREA TOTALA A COMENZIILOR
--PT FIECARE PRODUS.DACA CATEGORIA NU EXISTA, SA SE RIDICE O EXCEPTIE

CREATE OR REPLACE PROCEDURE AFISARE_PROD(P_CATEGORIE VARCHAR2)IS
CURSOR C IS SELECT
    P.DENUMIRE_PRODUS,
    SUM(R.PRET * R.CANTITATE) AS VALOARE
    FROM PRODUSE P
    JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
    WHERE CATEGORIE=P_CATEGORIE
    GROUP BY P.DENUMIRE_PRODUS;
    
    R C%ROWTYPE;
BEGIN
    IF NOT C%ISOPEN THEN
        OPEN C;
    END IF;
    LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(R.DENUMIRE_PRODUS||'->'||R.VALOARE);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('NUMAR PROCEDURA PT CARE EXISTA COMENZI:'|| C%ROWCOUNT);
    
    IF C%ROWCOUNT=0 THEN
        RAISE_APPLICATION_ERROR(-20000,'NU SUNT PRODUSE IN ACEA CATEGORIE');
    END IF;
    CLOSE C;
END;
/

DECLARE 
    NU_EXISTA EXCEPTION;
    PRAGMA EXCEPTION_INIT(NU_EXISTA,-20000);
BEGIN
    AFISARE_PROD('office2');
    EXCEPTION
        WHEN NU_EXISTA THEN 
         DBMS_OUTPUT.PUT_LINE('A APARUT O EXCEPTIE'||SQLERRM);
END;
/

--SA SE CONSTRUIASAC O FUNCTIE CARE PRIMESTE ID UL UNUI PRODUS IS RETURNEAZA 
--VALOAREA TOTALA A COMENZILOR PT REPSECTIVUL PRODUS
--SA SE APELEZE DINTR UN CURSOR

CREATE OR REPLACE FUNCTION GET_VAL(P_ID_PRODUS NUMBER)RETURN NUMBER IS
V_VAL NUMBER;
BEGIN
    SELECT SUM(PRET*CANTITATE) INTO V_VAL
    FROM RAND_COMENZI
    WHERE ID_PRODUS=P_ID_PRODUS;
    
    RETURN NVL(V_VAL,0);
END;
/

DECLARE 
    CURSOR C IS SELECT
    ID_PRODUS,DENUMIRE_PRODUS,GET_VAL(ID_PRODUS) VAL
    FROM PRODUSE
    WHERE GET_VAL(ID_PRODUS)>5000
    ORDER BY GET_VAL(ID_PRODUS) DESC;
    
BEGIN
    FOR R IN C LOOP
        DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS||'->'||R.DENUMIRE_PRODUS||'->'||R.VAL);
    END LOOP;
END;
/
--SA SE CONSTRUIASAC UN PACHET CARE CONTINE 
--O FUNCTIE CARE PRIMESTE CA PARAMETRUL ID UL UNUI PRODUS SI UN AN CALENDARISITIC(EX 2019)
--FUNCTIA VA RETURNA VALOAREA TOTALA PENTRU COMENZILE PRODUSULUI RESPECTIV IN ANUL RESPECTOV
-- O PROCEDURA CARE APELEAZA FUNCTIA DINTR UN CURSOR,PROCEDURA VA DECLANSA O EXCEPTIE DEFINITA DE UTILIZATOR
--EXCEPTIA SE VA DECLANSA DACA VAL COMENZILOR PENTRU ACEL AN <500.000
--SA SE APELEZE PROCEDURA DINTR UN BLOC ANONIMC, SA SE TRATEZE EXCEPTIA FARA A FOLOSI OTHERS

CREATE OR REPLACE PACKAGE PACK IS
FUNCTION TOTAL_VANZARI(P_ID_PRODUS NUMBER,P_AN NUMBER) RETURN NUMBER;
PROCEDURE AFISARE_TOTAL(P_AN NUMBER);
VAL_MICA EXCEPTION;
PRAGMA EXCEPTION_INIT(VAL_MICA,-20000);
END;
/

CREATE OR REPLACE PACKAGE BODY PACK IS
    FUNCTION TOTAL_VANZARI(P_ID_PRODUS NUMBER,P_AN NUMBER) RETURN NUMBER IS
    V_VAL NUMBER;
    BEGIN
        SELECT SUM(PRET* CANTITATE) INTO V_VAL
        FROM COMENZI C
        JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
        WHERE EXTRACT(YEAR FROM DATA)=P_AN AND R.ID_PRODUS=P_ID_PRODUS;
        RETURN NVL(V_VAL,0);
    END;
    
    PROCEDURE AFISARE_TOTAL(P_AN NUMBER) IS
        CURSOR C IS 
        SELECT ID_PRODUS,DENUMIRE_PRODUS,TOTAL_VANZARI(ID_PRODUS,P_AN) VAL
        FROM PRODUSE
        ORDER BY VAL DESC;
        
        R C%ROWTYPE;
        V_SUMA NUMBER DEFAULT 0;
        BEGIN
            IF NOT C%ISOPEN THEN
                OPEN C;
            END IF;
            LOOP
                FETCH C INTO R;
                EXIT WHEN C%NOTFOUND;
                 DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS||' '||R.DENUMIRE_PRODUS||' '||R.VAL);
                V_SUMA:=V_SUMA+R.VAL;
            END LOOP;
            CLOSE C;
            
            IF V_SUMA<500000 THEN
                RAISE_APPLICATION_ERROR(-20000,'SUMA MICA');
            END IF;
        END;
END;
/

BEGIN
    PACK.AFISARE_TOTAL(2020);
    EXCEPTION
        WHEN PACK.VAL_MICA THEN
            DBMS_OUTPUT.PUT_LINE('EROARE');
END;
/

/*Să se construiască un pachet PL/SQL numit PKG_PERFORMANTA care să conțină:

O funcție (CALCULEAZA_VANZARI_DEPT) care primește ca parametru ID-ul unui departament și un an calendaristic. 
Funcția va returna valoarea totală a vânzărilor realizate de toți angajații din acel 
departament în anul respectiv (vânzările se calculează din RAND_COMENZI prin comenzile 
plasate în COMENZI de către angajații departamentului). Dacă departamentul nu are vânzări, funcția returnează 0.

O procedură (PROMOVEAZA_DEPARTAMENTE) care primește ca parametru un an calendaristic 
și un procent de mărire (ex. 10 pentru 10%). Procedura va folosi un cursor pentru a parcurge toate departamentele. Pentru fiecare departament, va apela funcția creată anterior.

Dacă valoarea totală a vânzărilor departamentului în acel an depășește 1.000.000, 
se va actualiza salariul maxim (SALARIU_MAX) în tabela FUNCTII cu procentul trimis ca parametru, 
însă doar pentru funcțiile deținute de angajații din acel departament.

Procedura va lansa o excepție definită de utilizator (FARA_VANZARI_ANUAL)
dacă mărirea se aplică unui an în care vânzările totale ale tuturor departamentelor cumulate sunt 0. 

Un bloc anonim care apelează procedura din pachet pentru anul 2021 și o mărire de 15%, 
tratând excepția personalizată fără a folosi OTHERS.
*/

CREATE OR REPLACE PACKAGE PKG_PERFORAMNTA IS
    FUNCTION CALCULEAZA_VANZARI_DEPT(P_ID_DEPARTAMENT NUMBER,P_AN NUMBER)RETURN NUMBER;
    PROCEDURE PROMOVEAZA_DEP(P_AN NUMBER,P_PROCENT NUMBER);
    FARA_VANZARI EXCEPTION;
    PRAGMA EXCEPTION_INIT(FARA_VANZARI,-20001);
END;
/

CREATE OR REPLACE PACKAGE BODY PKG_PERFORAMNTA IS
    FUNCTION CALCULEAZA_VANZARI_DEPT(P_ID_DEPARTAMENT NUMBER,P_AN NUMBER)RETURN NUMBER IS
    V_VAL NUMBER;
    BEGIN
        SELECT SUM(R.CANTITATE * R.PRET) INTO V_VAL
        FROM COMENZI C
        JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
        JOIN ANGAJATI A ON C.ID_ANGAJAT=A.ID_ANGAJAT
        WHERE A.ID_DEPARTAMENT=P_ID_DEPARTAMENT 
        AND EXTRACT(YEAR FROM C.DATA)=P_AN;
        
        RETURN NVL(V_VAL,0);
    END;
    
    PROCEDURE PROMOVEAZA_DEP(P_AN NUMBER,P_PROCENT NUMBER) IS
        CURSOR C IS SELECT
            ID_DEPARTAMENT,DENUMIRE_DEPARTAMENT,CALCULEAZA_VANZARI_DEPT(ID_DEPARTAMENT,P_AN) VANZ
            FROM DEPARTAMENTE
            ORDER BY VANZ DESC;
        
        R C%ROWTYPE;
        V_SUMA NUMBER DEFAULT 0;
     BEGIN
        IF NOT C%ISOPEN THEN
            OPEN C;
        END IF;
        
        LOOP
            FETCH C INTO R;
            EXIT WHEN C%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE(R.ID_DEPARTAMENT||' '||R.DENUMIRE_DEPARTAMENT||' '||R.VANZ);
            
            V_SUMA:=V_SUMA+R.VANZ;
            
            IF R.VANZ>1000000 THEN
             UPDATE FUNCTII
             SET SALARIU_MAX=SALARIU_MAX * (1+ P_PROCENT/100)
             WHERE ID_FUNCTIE IN(
             SELECT ID_FUNCTIE
             FROM ANGAJATI
             WHERE ID_DEPARTAMENT=R.ID_DEPARTAMENT);
            END IF;
        END LOOP;
        CLOSE C;

        IF V_SUMA=0 THEN
            RAISE_APPLICATION_ERROR(-20001,'FARA VANZARI');
        END IF;
    END;

END;
/

BEGIN 
    PKG_PERFORAMNTA.PROMOVEAZA_DEP(2015,15);
    EXCEPTION
        WHEN PKG_PERFORAMNTA.FARA_VANZARI THEN
            DBMS_OUTPUT.PUT_LINE('EROARE'||SQLERRM);
END;
/



CREATE OR REPLACE PACKAGE PKG_GESTIUNE_RECRUTARE IS
    FUNCTION NUMAR_FUNCTII_ANTERIOARE(P_ID_ANGAJAT NUMBER)RETURN NUMBER;
    PROCEDURE EVALUARE_VECHIME_DEP(P_ID_DEP NUMBER,P_COMISION NUMBER);
    
    DEPARTAMENT_INVALID EXCEPTION;
    PRAGMA EXCEPTION_INIT(DEPARTAMENT_INVALID,-20000);
END;
/

CREATE OR REPLACE PACKAGE BODY PKG_GESTIUNE_RECRUTARE IS

     FUNCTION NUMAR_FUNCTII_ANTERIOARE(P_ID_ANGAJAT NUMBER)RETURN NUMBER IS
     V_TOT NUMBER;
     BEGIN
        SELECT COUNT(*) INTO V_TOT
        FROM ISTORIC_FUNCTII
        WHERE ID_ANGAJAT=P_ID_ANGAJAT
        ORDER BY V_TOT DESC;
        
        RETURN NVL(V_TOT,0);
     END;
     
     PROCEDURE EVALUARE_VECHIME_DEP(P_ID_DEP NUMBER,P_COMISION NUMBER) IS
        CURSOR C IS SELECT
                 A.ID_ANGAJAT,
                 A.NUME,
                 A.PRENUME,
                 A.COMISION,
                 NUMAR_FUNCTII_ANTERIOARE(A.ID_ANGAJAT) NR_F
                 FROM ANGAJATI A
                 WHERE A.ID_DEPARTAMENT=P_ID_DEP
                 GROUP BY A.ID_ANGAJAT,A.NUME,A.PRENUME,A.COMISION;
        R C%ROWTYPE;
        NR NUMBER DEFAULT 0;
     BEGIN
     
        SELECT COUNT(*) INTO NR
        FROM DEPARTAMENTE
        WHERE ID_DEPARTAMENT=P_ID_DEP;
        
        IF NR=0 THEN
            RAISE_APPLICATION_ERROR(-20000,'DEPARTAMENT INVALID');
        END IF;
        
        IF NOT C%ISOPEN THEN
            OPEN C;
        END IF;
        LOOP
            FETCH C INTO R;
            EXIT WHEN C%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE(R.ID_ANGAJAT||' '||R.NUME||' '||R.PRENUME||' '||R.NR_F);
            
            IF R.COMISION<P_COMISION THEN
                UPDATE ANGAJATI
                SET COMISION=P_COMISION
                WHERE ID_ANGAJAT=R.ID_ANGAJAT;
            END IF;
        END LOOP;
        
     END;
     
END;
/

BEGIN
    PKG_GESTIUNE_RECRUTARE.EVALUARE_VECHIME_DEP(1000,15);
    EXCEPTION
    WHEN PKG_GESTIUNE_RECRUTARE.DEPARTAMENT_INVALID THEN
        DBMS_OUTPUT.PUT_LINE('A APARUT EROARE'||SQLERRM);
END;
/


CREATE OR REPLACE PACKAGE PKG_GESTIUNE_CLIENTI IS
    FUNCTION TOTAL_COMENZI(P_ID_CLIENT NUMBER,P_AN NUMBER)RETURN NUMBER;
    PROCEDURE PROCESARE_CLIENTI_REG(P_NUME_REG VARCHAR2,P_PROCENT NUMBER);
    REGIUNE_INVALIDA EXCEPTION;
    PRAGMA EXCEPTION_INIT(REGIUNE_INVALIDA,-20000);
END;
/

CREATE OR REPLACE PACKAGE BODY PKG_GESTIUNE_CLIENTI IS

    FUNCTION TOTAL_COMENZI(P_ID_CLIENT NUMBER,P_AN NUMBER)RETURN NUMBER IS
    TOTAL NUMBER;
    BEGIN
        SELECT SUM(R.CANTITATE *R.PRET)INTO TOTAL
        FROM COMENZI C
        JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
        WHERE C.ID_CLIENT=P_ID_CLIENT AND EXTRACT(YEAR FROM C.DATA)=P_AN;
        
        RETURN NVL(TOTAL,0);
    END;
    
    PROCEDURE PROCESARE_CLIENTI_REG(P_NUME_REG VARCHAR2,P_PROCENT NUMBER) IS
        CURSOR C IS SELECT
                CLI.ID_CLIENT,CLI.NUME_CLIENT,CLI.PRENUME_CLIENT,CLI.LIMITA_CREDIT,TOTAL_COMENZI(CLI.ID_CLIENT,2018) V_TOT
                FROM CLIENTI CLI
                JOIN COMENZI CO ON CLI.ID_CLIENT=CO.ID_CLIENT
                JOIN ANGAJATI A ON CO.ID_ANGAJAT=A.ID_ANGAJAT
                JOIN DEPARTAMENTE D ON A.ID_DEPARTAMENT=D.ID_DEPARTAMENT
                JOIN LOCATII L ON D.ID_LOCATIE=L.ID_LOCATIE
                JOIN TARI T ON L.ID_TARA=T.ID_TARA
                JOIN REGIUNI R ON T.ID_REGIUNE=R.ID_REGIUNE
                WHERE R.DENUMIRE_REGIUNE=P_NUME_REG;
                
        R C%ROWTYPE;
        NR NUMBER DEFAULT 0;
    BEGIN
        SELECT COUNT(*) INTO NR
        FROM REGIUNI
        WHERE DENUMIRE_REGIUNE=P_NUME_REG;
        
        IF NR=0 THEN
            RAISE_APPLICATION_ERROR(-20000,'REGIUNE INVALIDA');
        END IF;
        
        IF NOT C%ISOPEN THEN
            OPEN C;
        END IF;
        LOOP
            FETCH C INTO R;
            EXIT WHEN C%NOTFOUND;
                DBMS_OUTPUT.PUT_LINE(R.ID_CLIENT||' '||R.NUME_CLIENT||' '||R.PRENUME_CLIENT||' '||R.V_TOT);
            
            IF R.V_TOT>R.LIMITA_CREDIT THEN
                UPDATE CLIENTI
                SET LIMITA_CREDIT=LIMITA_CREDIT *(1+P_PROCENT/100)
                WHERE ID_CLIENT=R.ID_CLIENT;
            END IF;
        END LOOP;
        CLOSE C;
    END;
END;
/

BEGIN
    PKG_GESTIUNE_CLIENTI.PROCESARE_CLIENTI_REG('Asia',0.2);
    EXCEPTION 
        WHEN  PKG_GESTIUNE_CLIENTI.REGIUNE_INVALIDA THEN 
            DBMS_OUTPUT.PUT_LINE('A APARUT EROARE'||SQLERRM);
END;
/


CREATE OR REPLACE PACKAGE PKG_AUDIT_RESURSE IS
    FUNCTION MEDIE_SALARIALA_DEP(P_ID_DEP NUMBER)RETURN NUMBER;
    PROCEDURE VERIFICA_LOCATIE(P_ID_LOC NUMBER,P_SAL NUMBER);
    LOCATIE_INEXISTENTA EXCEPTION;
    PRAGMA EXCEPTION_INIT(LOCATIE_INEXISTENTA,-20000);
END;
/

CREATE OR REPLACE PACKAGE BODY PKG_AUDIT_RESURSE IS

    FUNCTION MEDIE_SALARIALA_DEP(P_ID_DEP NUMBER)RETURN NUMBER IS
    V_MED NUMBER;
    BEGIN
        SELECT AVG(SALARIUL) INTO V_MED
        FROM ANGAJATI
        WHERE ID_DEPARTAMENT=P_ID_DEP;
        
        RETURN NVL(V_MED,0);
    END;
    
    PROCEDURE VERIFICA_LOCATIE(P_ID_LOC NUMBER,P_SAL NUMBER) IS
        CURSOR C IS SELECT
            D.ID_DEPARTAMENT,D.DENUMIRE_DEPARTAMENT,MEDIE_SALARIALA_DEP(D.ID_DEPARTAMENT) MED
            FROM DEPARTAMENTE D
            JOIN LOCATII L ON D.ID_LOCATIE=L.ID_LOCATIE
            WHERE D.ID_LOCATIE=P_ID_LOC
            ORDER BY D.ID_DEPARTAMENT,D.DENUMIRE_DEPARTAMENT; 
        R C%ROWTYPE;
        NR NUMBER DEFAULT 0;
    BEGIN
        SELECT COUNT(*) INTO NR
        FROM LOCATII
        WHERE ID_LOCATIE=P_ID_LOC;
        
        IF NR=0 THEN
            RAISE_APPLICATION_ERROR(-20000,'LOCATIE INEXISTENTA');
        END IF;
        
        IF NOT C%ISOPEN THEN
            OPEN C;
        END IF;
        LOOP
            FETCH C INTO R;
            EXIT WHEN C%NOTFOUND;
            
            DBMS_OUTPUT.PUT_LINE(R.ID_DEPARTAMENT||' '||R.DENUMIRE_DEPARTAMENT||' '||R.MED);
            
            IF R.MED<P_SAL THEN
                UPDATE FUNCTII
                SET SALARIU_MIN=SALARIU_MIN *1.05
                WHERE ID_FUNCTIE IN(
                SELECT ID_FUNCTIE 
                FROM ANGAJATI
                WHERE ID_DEPARTAMENT=R.ID_DEPARTAMENT);
            END IF;
        END LOOP;
    END;
    
    
END;
/

BEGIN
    PKG_AUDIT_RESURSE.VERIFICA_LOCATIE(99,5000);
    EXCEPTION
        WHEN PKG_AUDIT_RESURSE.LOCATIE_INEXISTENTA THEN
            DBMS_OUTPUT.PUT_LINE('A APARUT EROARE'||SQLERRM);
END;
/

CREATE OR REPLACE TRIGGER V BEFORE INSERT OR UPDATE OR DELETE ON COMENZI
BEGIN
    IF INSERTING AND TO_CHAR(SYSDATE,'HH24:MI')>='16:00' THEN
        RAISE_APPLICATION_ERROR(-20000,'NU SE POT AD');
    ELSIF UPDATING AND TO_CHAR(SYSDATE,'HH24;MI')>='16:10' THEN
        RAISE_APPLICATION_ERROR(-20000,'ER');
    ELSIF DELETING AND TO_CHAR(SYSDATE,'HH24:MI')>='16:20' THEN
        RAISE_APPLICATION_ERROR(-20000,'ER');
    END IF;
END;
/



CREATE OR REPLACE PROCEDURE ACT(P_ID_DEP NUMBER,P_NR OUT NUMBER) IS
    CURSOR C IS SELECT
        A.ID_ANGAJAT,
        A.NUME,
        A.PRENUME,
        A.SALARIUL,
        A.ID_DEPARTAMENT,
        D.DENUMIRE_DEPARTAMENT
        FROM ANGAJATI A
        JOIN DEPARTAMENTE D ON A.ID_DEPARTAMENT=D.ID_DEPARTAMENT
        WHERE D.ID_DEPARTAMENT=P_ID_DEP;
    R C%ROWTYPE;
BEGIN
    P_NR:=0;
    IF NOT C%ISOPEN THEN
        OPEN C;
    END IF;
    LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND;
        
        IF R.SALARIUL<5000 THEN
            UPDATE ANGAJATI
            SET SALARIUL=R.SALARIUL*1.10
            WHERE ID_ANGAJAT=R.ID_ANGAJAT;
            
            P_NR:=P_NR+1;
            DBMS_OUTPUT.PUT_LINE('ANGAJATUL '||R.NUME||' DIN DEPARTAMENTUL '||R.DENUMIRE_DEPARTAMENT);
        ELSE 
             DBMS_OUTPUT.PUT_LINE('NU NECESITA MODIFICARI');
        END IF;
    END LOOP;
    
    CLOSE C;
END;
/

DECLARE 
    NR NUMBER;
BEGIN
    ACT(50,NR);
    DBMS_OUTPUT.PUT_LINE('MOD'||NR);
END;
/

CREATE OR REPLACE TRIGGER TG BEFORE INSERT ON PRODUSE
DECLARE 
    NR NUMBER;
BEGIN
    SELECT COUNT(*) INTO NR
    FROM PRODUSE 
    WHERE PRET_LISTA IS NULL;
    
    IF NR>0 THEN
        RAISE_APPLICATION_ERROR(-20000,'ER');
    ELSE 
    DBMS_OUTPUT.PUT_LINE('ADAGUARE');
    END IF;
        
END;
/


CREATE OR REPLACE FUNCTION NR_PROD(P_ID_COMANDA NUMBER)RETURN NUMBER IS
    CURSOR C IS SELECT
        P.ID_PRODUS,P.DENUMIRE_PRODUS,P.PRET_LISTA
        FROM PRODUSE P
        JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
        WHERE R.ID_COMANDA=P_ID_COMANDA;
    R C%ROWTYPE;
    NR NUMBER DEFAULT 0;
BEGIN
    IF NOT C%ISOPEN THEN
        OPEN C;
    END IF;
    LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND;
        
        IF R.PRET_LISTA>200 THEN
            UPDATE PRODUSE
            SET PRET_LISTA=PRET_LISTA * 0.9
            WHERE ID_PRODUS=R.ID_PRODUS;
            NR:=NR+1;
            DBMS_OUTPUT.PUT_LINE('PRODUSUL '||' '||R.DENUMIRE_PRODUS||'  DIN COMANDA '||P_ID_COMANDA||' A FOST MODIFICAT');
        ELSE 
             DBMS_OUTPUT.PUT_LINE('NU NECESITA REDUCERE');
        END IF;
    END LOOP;
    CLOSE C;
    
    RETURN NR;
END;
/

DECLARE 
    NR NUMBER;
BEGIN
    NR:=NR_PROD(2397);
    DBMS_OUTPUT.PUT_LINE(NR);
END;
/

CREATE OR REPLACE TRIGGER TRG BEFORE INSERT ON ANGAJATI
DECLARE 
    NR NUMBER;
BEGIN
    SELECT COUNT(*) INTO NR
    FROM ANGAJATI;
    
    IF NR>=100 THEN
        RAISE_APPLICATION_ERROR(-20000,'NU SE MAI POT ADG');
    END IF;
END;
/


CREATE OR REPLACE PACKAGE PK IS
    FUNCTION TOTAL(P_ID_TARA NUMBER)RETURN NUMBER;
    PROCEDURE AFISARE_RAP;
    PROCEDURE MODIF_SAL(NR_MOD OUT NUMBER);
    
    NO_TARA EXCEPTION;
    NO_PRODUS EXCEPTION;
    PRAGMA EXCEPTION_INIT(NO_TARA,-20000);
    PRAGMA EXCEPTION_INIT(NO_PRODUS,-20001);
END;
/

CREATE OR REPLACE PACKAGE BODY PK IS

    FUNCTION TOTAL(P_ID_TARA NUMBER)RETURN NUMBER IS
    NR_TOTAL NUMBER;
    VERIF_T NUMBER;
    BEGIN
        SELECT COUNT(*) INTO VERIF_T
        FROM TARI
        WHERE ID_TARA=P_ID_TARA;
        
        IF VERIF_T=0 THEN
            RAISE_APPLICATION_ERROR(-20000,'TARA NU EXISTA');
        END IF;
        
        SELECT COUNT(DISTINCT R.ID_PRODUS) INTO NR_TOTAL
        FROM RAND_COMENZI R
        JOIN COMENZI CO ON R.ID_COMANDA=CO.ID_COMANDA
        JOIN ANGAJATI A ON CO.ID_ANGAJAT=A.ID_ANGAJAT
        JOIN DEPARTAMENTE D ON A.ID_DEPARTAMENT=D.ID_DEPARTAMENT
        JOIN LOCATII L ON D.ID_LOCATIE=L.ID_LOCATIE
        JOIN TARI T ON L.ID_TARA=T.ID_TARA
        WHERE T.ID_TARA=P_ID_TARA;
        
        IF NR_TOTAL=0 THEN
            RAISE_APPLICATION_ERROR(-20001,'NU EX PRODUSE');
        END IF;
    END;
    
    PROCEDURE AFISARE_RAP IS
        CURSOR C1 IS SELECT
                D.ID_DEPARTAMENT,D.DENUMIRE_DEPARTAMENT,L.ORAS, SUM(R.PRET * R.CANTITATE) AS VAL_T
                FROM DEPARTAMENTE D
                JOIN LOCATII L ON D.ID_LOCATIE=L.ID_LOCATIE
                JOIN ANGAJATI A ON D.ID_DEPARTAMENT=A.ID_DEPARTAMENT
                JOIN COMENZI C ON A.ID_ANGAJAT=C.ID_ANGAJAT
                JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
                GROUP BY D.ID_DEPARTAMENT,D.DENUMIRE_DEPARTAMENT
                HAVING COUNT(A.ID_ANGAJAT)>=2;
        
        CURSOR C2(P_ID_DEP NUMBER) IS SELECT
            A.ID_ANGAJAT,A.NUME,A.PRENUME,F.DENUMIRE_FUNCTIE,SUM(R.CANTITATE* R.PRET) AS T_ANG
            FROM ANGAJATI A
            JOIN FUNCTII F ON A.ID_FUNCTIE=F.ID_FUNCTIE
            JOIN COMENZI C ON A.ID_ANGAJAT=C.ID_ANGAJAT
            JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
            WHERE A.ID_DEPARTAMENT=P_ID_DEP
            GROUP BY A.ID_ANGAJAT,A.NUME,A.PRENUME;
        
        R1 C1%ROWTYPE;
        R2 C2%ROWTYPE;
        
        BEGIN
            IF NOT C1%ISOPEN THEN
                OPEN C1;
            END IF;
            LOOP
                FETCH C1 INTO R1;
                EXIT WHEN C1%NOTFOUND;
                
                DBMS_OUTPUT.PUT_LINE(R1.DENUMIRE_DEPARTAMENT||' '||R1.ORAS||' '||R1.VAL_T);
                
                IF NOT C2%ISOPEN THEN
                    OPEN C2(R1.ID_DEPARTAMENT);
                END IF;
                LOOP
                    FETCH C2 INTO R2;
                    EXIT WHEN C2%NOTFOUND;
                    DBMS_OUTPUT.PUT_LINE(R2.NUME||' '||R2.PRENUME||' '||R2.DENUMIRE_FUNCTIE||' '||R2.T_ANG);
                END LOOP;
                CLOSE C2;
                
            END LOOP;
            CLOSE C1;
        END;
        
    PROCEDURE MODIF_SAL(NR_MOD OUT NUMBER) IS
    BEGIN
        UPDATE ANGAJATI A
        SET A.SALARIUL=(SELECT 
        F.SALARIU_MAX
        FROM FUNCTII F
        WHERE F.ID_FUNCTIE=A.ID_FUNCTIE)
        WHERE A.ID_ANGAJAT IN(
        SELECT DISTINCT C.ID_ANGAJAT
        FROM COMENZI C
        JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
        JOIN PRODUSE P ON R.ID_PRODUS=P.ID_PRODUS
        WHERE UPPER(P.CATEGORIE)='COMPONENTE'
        AND EXTRACT(YEAR FROM C.DATA)=2026);
        
        NR_MOD:=SQL%ROWCOUNT;
    END;

END;
/

DECLARE
    V_NR NUMBER;
    V_MODIF NUMBER;
BEGIN
    V_NR:=PK.TOTAL(100);
    DBMS_OUTPUT.PUT_LINE('PROD UNICE:'||V_NR);
    
    PK.AFISARE_RAP;
    
    PK.MODIF_SAL(V_MODIF);
    DBMS_OUTPUT.PUT_LINE('MODIFICARI'||V_MODIF);
    
    EXCEPTION 
        WHEN PK.NO_TARA THEN
            DBMS_OUTPUT.PUT_LINE('EROARE'||SQLERRM);
        WHEN PK.NO_PRODUS THEN
            DBMS_OUTPUT.PUT_LINE('EROARE'||SQLERRM);
        
END;
/



CREATE OR REPLACE TRIGGER TG BEFORE UPDATE OF CATEGORIE ON PRODUSE FOR EACH ROW
DECLARE 
    N NUMBER;
BEGIN
    IF :NEW.CATEGORIE!=:OLD.CATEGORIE THEN
    
        SELECT COUNT(*) INTO N
        FROM COMENZI C
        JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
        WHERE R.ID_PRODUS=:NEW.ID_PRODUS
        AND C.DATA>=ADD_MONTHS(SYSDATE,-6);
        
        IF N>0 THEN
            RAISE_APPLICATION_ERROR(-20001,'NU SE POT ACT');
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER LOP BEFORE UPDATE OF CATEGORIE ON PRODUSE FOR EACH ROW
DECLARE
    N NUMBER;
BEGIN
    IF :NEW.CATEGORIE!=:OLD.CATEGORIE THEN
        
        SELECT COUNT(*) INTO N
        FROM COMENZI C
        JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
        WHERE R.ID_COMANDA=:NEW.ID_PRODUS
        AND C.DATA>=ADD_MONTHS(SYSDATE,-6);
        
        IF N>0 THEN
            RAISE_APPLICATION_ERROR(-20001,'NU SE POT ACT');
        END IF;
    END IF;
END;
/


CREATE OR REPLACE PACKAGE PK1 IS
    FUNCTION NR_ANG(ID_LOCATIE NUMBER)RETURN NUMBER;
    PROCEDURE AFIS_RAP;
    PROCEDURE M_SAL(NR_MOD NUMBER);
    
    NO_LOCATIE EXCEPTION;
    NO_ISTORIC EXCEPTION;
    PRAGMA EXCEPTION_INIT(NO_LOCATIE,-20000);
    PRAGMA EXCEPTION_INIT(NO_ISTORIC,-20001);
END;
/

CREATE OR REPLACE PACKAGE BODY PK1 IS
    
     FUNCTION NR_ANG(F_ID_LOCATIE NUMBER)RETURN NUMBER IS
     NR_LOC NUMBER;
     NR_ANG_V NUMBER;
     
     BEGIN
        SELECT COUNT(*) INTO NR_LOC
        FROM LOCATII
        WHERE ID_LOCATIE=F_ID_LOCATIE;
        
        IF NR_LOC=0 THEN
            RAISE_APPLICATION_ERROR(-20000,'LOCATIE INVALIDA');
        END IF;
        
        SELECT COUNT(I.ID_ANGAJAT) INTO NR_ANG_V
        FROM ISTORIC_FUNCTII I
        JOIN DEPARTAMENTE D ON I.ID_DEPARTAMENT=D.ID_DEPARTAMENT
        WHERE D.ID_LOCATIE=F_ID_LOCATIE;
        
        IF NR_ANG_V=0 THEN
            RAISE_APPLICATION_ERROR(-20001,'NU EXISTA ANG');
        END IF;
        
        RETURN NR_ANG_V;
     END;
     
     PROCEDURE AFIS_RAP IS 
        CURSOR C1 IS SELECT
            T.ID_TARA,T.DENUMIRE_TARA,
            COUNT(CLI.ID_CLIENT) AS NR_CLIENTI
            FROM TARI T 
            JOIN LOCATII L ON T.ID_TARA=L.ID_TARA
            JOIN DEPARTAMENTE D ON L.ID_LOCATIE=D.ID_LOCATIE
            JOIN ANGAJATI A ON D.ID_DEPARTAMENT=A.ID_DEPARTAMENT
            JOIN COMENZI C ON A.ID_ANGAJAT=C.ID_ANGAJAT
            JOIN CLIENTI CLI ON C.ID_CLIENT=CLI.ID_CLIENT
            GROUP BY T.ID_TARA,T.DENUMIRE_TARA
            HAVING COUNT(CLI.ID_CLIENT)>=1;
        
        CURSOR C2(P_ID_TARA NUMBER) IS SELECT
            CLI.ID_CLIENT,CLI.NUME_CLIENT,CLI.PRENUME_CLIENT,CLI.LIMITA_CREDIT,
            SUM(R.PRET * R.CANTITATE) AS VAL_T
            FROM CLIENTI CLI
            JOIN COMENZI C ON CLI.ID_CLIENT=C.ID_CLIENT
            JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
            JOIN ANGAJATI A ON CLI.ID_ANGAJAT=A.ID_ANGAJAT
            JOIN DEPARTAMENTE D ON A.ID_DEPARTAMENT=D.ID_DEPARTAMENT
            JOIN LOCATII L ON D.ID_LOCATIE=L.ID_LOCATIE
            JOIN TARI T ON L.ID_TARA=T.ID_TARA
            WHERE T.ID_TARA=P_ID_TARA
            GROUP BY CLI.ID_CLIENT,CLI.NUME_CLIENT,CLI.PRENUME_CLIENT,CLI.LIMITA_CREDIT;
            
        R1 C1%ROWTYPE;
        R2 C2%ROWTYPE;
     BEGIN
        IF NOT C1%ISOPEN THEN
            OPEN C1;
        END IF;
        
        LOOP
            FETCH C1 INTO R1;
            EXIT WHEN C1%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE(R1.DENUMIRE_TARA);
            
             IF NOT C2%ISOPEN THEN
                OPEN C2(R1.ID_TARA);
             END IF;
             
             LOOP
                FETCH C2 INTO R2;
                EXIT WHEN C2%NOTFOUND;
                DBMS_OUTPUT.PUT_LINE(R2.NUME_CLIENT);
             END LOOP;
             CLOSE C2;
        END LOOP;
        CLOSE C1;
     END;
     
     PROCEDURE M_SAL(NR_MOD NUMBER) IS
     V_MED_SAL NUMBER;
     BEGIN
        SELECT AVG(SALARIU_MIN) INTO V_MED_SAL FROM FUNCTII;
        
        UPDATE FUNCTII
        SET SALARIU_MIN=V_MED_SAL
        WHERE ID_FUNCTIE IN(
        SELECT DISTINCT ID_FUNCTIE
        FROM ANGAJATI
        WHERE ID_ANGAJAT NOT IN(
        SELECT DISTINCT ID_ANGAJAT 
        FROM COMENZI
        WHERE ID_ANGAJAT IS NOT NULL)
        );
        
        NR_MOD:=SQL%ROWCOUNT;
     END;
     
END;
/

CREATE OR REPLACE TRIGGER TG1 BEFORE UPDATE OF ID_MANAGER ON DEPARTAMENTE FOR EACH ROW
DECLARE
    N NUMBER;
BEGIN
    IF :NEW.ID_MANAGER!=:OLD.ID_MANAGER THEN
    
        SELECT COUNT(*) INTO N 
        FROM ANGAJATI 
        WHERE ID_MANAGER=:NEW.ID_MANAGER AND COMISION>=0.2;
        
        IF N>0 THEN
            RAISE_APPLICATION_ERROR(-20001,'TRIG');
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TKF BEFORE UPDATE OF ID_MANAGER ON DEPARTAMENTE FOR EACH ROW
DECLARE 
    N NUMBER;
BEGIN
    IF :NEW.ID_MANAGER!=:OLD.ID_MANAGER THEN
        SELECT COUNT(*) INTO N
        FROM ANGAJATI
        WHERE ID_MANAGER=:NEW.ID_MANAGER AND COMISION>=0.2;
        
        IF N>0 THEN 
            RAISE_APPLICATION_ERROR(-20001,'TRIG');
        END IF;
    END IF;
END;
/

-----------------------
CREATE OR REPLACE PACKAGE PKL IS
    FUNCTION ANGAJATI(P_ID_DEP NUMBER)RETURN NUMBER;
    PROCEDURE RAPORT;
    PROCEDURE COM(NR_MOD OUT NUMBER);
    
    NO_DEP EXCEPTION;
    NO_ANG EXCEPTION;
    PRAGMA EXCEPTION_INIT(NO_DEP,-20000);
    PRAGMA EXCEPTION_INIT(NO_ANG,-20001);
END;
/

CREATE OR REPLACE PACKAGE BODY PKL IS
    
    FUNCTION ANGAJATI(P_ID_DEP NUMBER)RETURN NUMBER IS
    NR_D NUMBER;
    NR NUMBER;
    MED NUMBER;
    BEGIN
        SELECT COUNT(*) INTO NR_D
        FROM DEPARTAMENTE
        WHERE ID_DEPARTAMENT=P_ID_DEP;
        
        IF NR_D=0 THEN
            RAISE_APPLICATION_ERROR(-20000,'NU EXISTA DEP');
        END IF;
        
        SELECT AVG(SALARIUL) INTO MED
        FROM ANGAJATI;
        
        SELECT COUNT(*) INTO NR
        FROM ANGAJATI
        WHERE ID_DEPARTAMENT=P_ID_DEP AND SALARIUL>MED;
        
        IF NR=0 THEN
            RAISE_APPLICATION_ERROR(-20001,'NU EXISTA ANG');
        END IF;
        
        RETURN NR;
    END;
    
     PROCEDURE RAPORT IS
        CURSOR C1 IS SELECT
            ID_DEPARTAMENT,DENUMIRE_DEPARTAMENT
            FROM DEPARTAMENTE
            GROUP BY ID_DEPARTAMENT,DENUMIRE_DEPARTAMENT;
            
        CURSOR C2(P_ID_DEP NUMBER) IS SELECT
            A.ID_ANGAJAT,A.NUME,A.PRENUME,A.SALARIUL
            FROM ANGAJATI A
            WHERE A.ID_DEPARTAMENT=P_ID_DEP
            GROUP BY A.ID_ANGAJAT,A.NUME,A.PRENUME,A.SALARIUL;
            
        R1 C1%ROWTYPE;
        R2 C2%ROWTYPE;
     BEGIN
        IF NOT C1%ISOPEN THEN
            OPEN C1;
        END IF;
        LOOP
            FETCH C1 INTO R1;
            EXIT WHEN C1%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('Dept: ' || R1.ID_DEPARTAMENT || ' - ' || R1.DENUMIRE_DEPARTAMENT);
            IF NOT C2%ISOPEN THEN
                OPEN C2(R1.ID_DEPARTAMENT);
            END IF;
             
            LOOP
                FETCH C2 INTO R2;
                EXIT WHEN C2%NOTFOUND;
                DBMS_OUTPUT.PUT_LINE('   -> Angajat: ' || R2.NUME || ' | Salariu: ' || R2.SALARIUL);
            END LOOP;
            CLOSE C2;
        END LOOP;
     END;
     
     PROCEDURE COM(NR_MOD OUT NUMBER) IS
     BEGIN
        UPDATE ANGAJATI
        SET COMISION=0.25
        WHERE EXTRACT(YEAR FROM DATA_ANGAJARE)=2015;
        
        NR_MOD:=SQL%ROWCOUNT;
     END;
    
END;
/


CREATE OR REPLACE TRIGGER TK BEFORE DELETE ON PRODUSE FOR EACH ROW
DECLARE 
    N NUMBER;
BEGIN
    
    SELECT COUNT(*) INTO N
    FROM RAND_COMENZI
    WHERE ID_PRODUS=:OLD.ID_PRODUS;
    
    IF N>0 THEN
        RAISE_APPLICATION_ERROR(-20004,'NU SE POATE STERGE');
    END IF;

END;
/


