SET SERVEROUTPUT ON

--NR1
--ex1
CREATE OR REPLACE PROCEDURE ACTUALIZARE_SALARII_MICI(P_ID_DEPARTAMENT NUMBER,P_NR OUT NUMBER) IS
CURSOR C IS
    SELECT A.ID_ANGAJAT,A.NUME,A.PRENUME,A.SALARIUL,D.DENUMIRE_DEPARTAMENT
    FROM ANGAJATI A
    JOIN DEPARTAMENTE D ON A.ID_DEPARTAMENT=D.ID_DEPARTAMENT
    WHERE D.ID_DEPARTAMENT=P_ID_DEPARTAMENT;
R C%ROWTYPE;
BEGIN
    P_NR:=0;
    OPEN C;
    LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND;
        IF R.SALARIUL <5000 THEN
            
            UPDATE ANGAJATI
            SET SALARIUL=R.SALARIUL*1.10
            WHERE ID_ANGAJAT=R.ID_ANGAJAT;
            
            P_NR:=P_NR+1;
            DBMS_OUTPUT.PUT_LINE('Anajatului'||R.NUME||'din departaemtnul'||R.DENUMIRE_DEPARTAMENT);
        ELSE 
            DBMS_OUTPUT.PUT_LINE('NU NECESITA MODIFICARE');
        END IF;
    END LOOP;
    
    IF C%ROWCOUNT=0 THEN
        RAISE_APPLICATION_ERROR(-20000,'NU SUNT ANGAJATI IN ACEA CATEGORIE');
    END IF;
    CLOSE C;
    
END;
/

DECLARE 
    v_total number;
BEGIN
ACTUALIZARE_SALARII_MICI(50,v_total);
DBMS_OUTPUT.PUT_LINE('Numar total de angajati modificati: ' || v_total);
END;
/

--ex2
CREATE OR REPLACE TRIGGER V_PR BEFORE INSERT ON PRODUSE 
DECLARE 
    NR NUMBER;
BEGIN
    SELECT COUNT(*) INTO NR
    FROM PRODUSE 
    WHERE PRET_LISTA IS NULL OR PRET_LISTA<0;
    
    IF NR >0 THEN
        RAISE_APPLICATION_ERROR(-20000,'EXISTA PRODUSE FARA PRET');
    END IF;
    
END;
/

INSERT INTO PRODUSE(ID_PRODUS,DENUMIRE_PRODUS,PRET_LISTA) VALUES (992,'PRODUS TEST',15000);


--NR2 

--ex1

CREATE OR REPLACE FUNCTION NR_PROD_REDUSE_COMANDA(P_ID_COMANDA NUMBER)RETURN NUMBER IS
CURSOR C IS SELECT
    P.ID_PRODUS,
    P.DENUMIRE_PRODUS,
    P.PRET_LISTA
    FROM PRODUSE P
    JOIN RAND_COMENZI RC ON P.ID_PRODUS=RC.ID_PRODUS
    WHERE RC.ID_COMANDA=P_ID_COMANDA;
R C%ROWTYPE;
NR NUMBER:=0;
BEGIN 
    OPEN C;
    LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND;
        
        IF R.PRET_LISTA>200 THEN
            
            UPDATE PRODUSE 
            SET PRET_LISTA=R.PRET_LISTA*0.9
            WHERE ID_PRODUS=R.ID_PRODUS;
            
            NR:=NR+1;
             DBMS_OUTPUT.PUT_LINE('PRODUSUL '||' '||R.DENUMIRE_PRODUS||'  DIN COMANDA '||P_ID_COMANDA||' A FOST MODIFICAT');
        ELSE 
             DBMS_OUTPUT.PUT_LINE('NU NECESITA REDUCERE');
        END IF;
        
    END LOOP;
    CLOSE C;
    
    RETURN NR;
END;
/

DECLARE 
    REZ NUMBER;
BEGIN
    REZ:=NR_PROD_REDUSE_COMANDA(2397);
    DBMS_OUTPUT.PUT_LINE('Numar total de produse modificate: ' || rez);
END;
/


--ex2
CREATE OR REPLACE TRIGGER TRG_A BEFORE INSERT ON ANGAJATI 
DECLARE 
    N NUMBER;
BEGIN
    SELECT COUNT(*) INTO N FROM ANGAJATI;
    
    IF N>=100 THEN
        RAISE_APPLICATION_ERROR(-20000,'NU SE MAI POT ANGAJA PERSOANE');
    ELSE 
         DBMS_OUTPUT.PUT_LINE('URMEAZA SA FIE ANGAJATA O PERSOANA NOUA');
    END IF;
END;
/

INSERT INTO ANGAJATI(ID_ANGAJAT,PRENUME,NUME) VALUES(999,'TEST','TEST');






