 --SEMINAR 1
 SET SERVEROUTPUT ON
 
 DECLARE 
    v_nume angajati.nume%type;
    v_prenume angajati.prenume%type;
BEGIN
    SELECT NUME, PRENUME INTO V_NUME,V_PRENUME
    FROM ANGAJATI
    WHERE ID_ANGAJAT=100;
    DBMS_OUTPUT.PUT_LINE('ANGAJAT '||V_NUME||' '||V_PRENUME);
END;
/

DECLARE
    V_NUME angajati.nume%type;
    v_prenume char(3);
BEGIN
    SELECT nume,prenume into V_nume,V_prenume
    from angajati
    where id_angajat=100;
    DBMS_OUTPUT.PUT_LINE('ABC');
    DBMS_OUTPUT.PUT_LINE('ANGAJAT '||V_NUME||' '||V_PRENUME);
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NU S-A GASIT ACEST ANGAJAT'); 
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('MAI MULTI ANGAJATI');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ALTA EXCEPTIE'||SQLERRM);
END;
/

DECLARE
    V_NUME ANGAJATI.NUME%TYPE;
    V_PRENUME CHAR(3);
BEGIN
    SELECT NUME,PRENUME INTO V_NUME,V_PRENUME
    FROM ANGAJATI
    WHERE ID_ANGAJAT>=101;
    DBMS_OUTPUT.PUT_LINE('ANGAJAT'||V_NUME||' '||V_PRENUME);
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('EXCEPTIE'||SQLERRM);
END;
/


--SEMINAR 2

DECLARE
    V_NUME ANGAJATI.NUME%TYPE;
    V_PRENUME ANGAJATI.PRENUME%TYPE;
    C_TAXE CONSTANT NUMBER:=0.19;
BEGIN
    SELECT NUME,PRENUME INTO V_NUME,V_PRENUME
    FROM ANGAJATI 
    WHERE ID_ANGAJAT>=101;
    DBMS_OUTPUT.PUT_LINE('ANGAJAT'||V_NUME||' '||V_PRENUME);
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NU S AU GASIT DATE');
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('PREA MULTE COLOANE');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ALTA EXCEPTIE'||SQLERRM);
END;
/

DECLARE
    V_ANG ANGAJATI%ROWTYPE; -- VB TIP RECORD ARE ACELASI CAMPURI CA SI COLOANELE DIN TAB ANG
BEGIN
    SELECT * INTO V_ANG 
    FROM ANGAJATI 
    WHERE ID_ANGAJAT=101;
      DBMS_OUTPUT.PUT_LINE(V_ANG.ID_ANGAJAT||' '||V_ANG.NUME||' '||V_ANG.PRENUME||' '||V_ANG.SALARIUL);
END;
/

DECLARE
    V_NOTA NUMBER(2) DEFAULT 10;
BEGIN
    V_NOTA:=9;
    IF V_NOTA IS NULL THEN
        DBMS_OUTPUT.PUT_LINE('NOTA LIPSA');
    ELSIF V_NOTA<1 OR V_NOTA>10 THEN
        DBMS_OUTPUT.PUT_LINE('NOTA ERONATA');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('PROMOVAT');
    END IF;
    DBMS_OUTPUT.PUT_LINE(V_NOTA);
END;
/

DECLARE
    V_NOTA NUMBER(2) DEFAULT 10;
BEGIN
    V_NOTA:=8;
    CASE 
    WHEN V_NOTA IS NULL THEN
        DBMS_OUTPUT.PUT_LINE('NOTA LIPSA');
     WHEN V_NOTA<1 OR V_NOTA>10 THEN
     DBMS_OUTPUT.PUT_LINE('NOTA ERONATA');
   WHEN V_NOTA < 5 THEN     
        DBMS_OUTPUT.PUT_LINE('PICAT');
        DBMS_OUTPUT.PUT_LINE('CHIAR A PICAT');
   WHEN V_NOTA=10 THEN     
        DBMS_OUTPUT.PUT_LINE('PREMIUL 1');
    ELSE 
    DBMS_OUTPUT.PUT_LINE('PROMOVAT');
        DBMS_OUTPUT.PUT_LINE('FELICITARI');
    END CASE;
    EXCEPTION
        WHEN CASE_NOT_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('PROMOVAT');
        DBMS_OUTPUT.PUT_LINE('FELICITARI');        
END;
/

DECLARE 
    I NUMBER:=5;
    INC NUMBER:=25;
    SF NUMBER:=25;
BEGIN 
    I:=I+2;
    FOR I IN INC..SF LOOP
        DBMS_OUTPUT.PUT_LINE('FELICITARI'); 
    END LOOP;
    EXCEPTION
        WHEN OTHERS THEN NULL;
END;
/

DECLARE
 
  INC NUMBER:=25;
  SF NUMBER:=35;
BEGIN
  FOR I IN INC..SF LOOP 
     CONTINUE WHEN I MOD 2=1;
     DBMS_OUTPUT.PUT_LINE('I='||I);   
     --EXIT WHEN I=30;
     
  END LOOP;
 -- DBMS_OUTPUT.PUT_LINE('I='||I);
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/

DECLARE 
    I PLS_INTEGER:=26;
BEGIN
    WHILE(I<=35) LOOP
     DBMS_OUTPUT.PUT_LINE('I='||I);
     I:=I+2;
    END LOOP;
        
END;
/


DECLARE
    I PLS_INTEGER:=26;
BEGIN
    LOOP
         DBMS_OUTPUT.PUT_LINE('I='||I);
         I:=I+2;
         EXIT WHEN I>35;
    END LOOP;
END;
/

--SEMINAR 3

DECLARE 
    V_SIR VARCHAR2(30):='ueth178uhf*AAkj#EsuPJ';
    V_VOCALE VARCHAR2(30);
    V_CONSOANE VARCHAR2(30);
    C CHAR;
BEGIN
    FOR I IN 1..LENGTH(V_SIR) LOOP
        C:=SUBSTR(V_SIR,I,1);
    IF UPPER(C) NOT BETWEEN 'A' AND 'Z' THEN
     NULL;
    ELSIF UPPER(C) IN ('A','E','I','O','U') THEN
      v_vocale:=v_vocale||C;
    ELSE
      v_consoane:=v_consoane||C;
    END IF;  
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('VOCALE='||v_vocale);
    DBMS_OUTPUT.PUT_LINE('CONSOANE='||v_consoane);
END;
/


DECLARE
  V_ID_ANGAJAT ANGAJATI.ID_ANGAJAT%TYPE;
  V_PRENUME ANGAJATI.PRENUME%TYPE;
  V_NUME ANGAJATI.NUME%TYPE;
  N NUMBER;
BEGIN
  FOR I IN 105..115 LOOP
   SELECT COUNT(*) INTO N FROM  ANGAJATI WHERE ID_ANGAJAT=I;
   IF N=1 THEN
   SELECT ID_ANGAJAT,NUME,PRENUME INTO V_ID_ANGAJAT,V_NUME,V_PRENUME FROM
      ANGAJATI WHERE ID_ANGAJAT=I;
   DBMS_OUTPUT.PUT_LINE(V_ID_ANGAJAT||' '||V_NUME||' '||V_PRENUME);
   END IF;
  END LOOP;    
END;
/

DECLARE 
    TYPE T_ANG IS RECORD(
        ID_ANGAJAT ANGAJATI.ID_ANGAJAT%TYPE,
        PRENUME ANGAJATI.PRENUME%TYPE,
        NUME ANGAJATI.NUME%TYPE);
    V T_ANG;
    N NUMBER;
BEGIN
    FOR I IN 105..115 LOOP
        SELECT COUNT(*) INTO N FROM ANGAJATI WHERE ID_ANGAJAT=I;
        IF N=1 THEN
            SELECT ID_ANGAJAT,NUME,PRENUME INTO V FROM
            ANGAJATI WHERE ID_ANGAJAT=I;
            DBMS_OUTPUT.PUT_LINE(V.ID_ANGAJAT||' '||V.NUME||' '||V.PRENUME);
        END IF;
    END LOOP;
END;
/


--SEMINAR 4

--TIPURI DE DATE
-- SCALARE:VARCHAR2,NUMBER,PLS_INTEGER,DATE,NUMBER ETC
-- COMPUSE : RECORD: TYPE ..IS RECORD(),%ROWTYPE
--          COLECTII: INDEX BY TABLE, NESTED TABLE, VARRAY

DECLARE
    TYPE T_ANG IS TABLE OF PLS_INTEGER INDEX BY VARCHAR2(100);
    V T_ANG;
BEGIN
    V('ION'):=50;
END;
/

DECLARE
    TYPE T_ANG IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER;
    V T_ANG;
BEGIN
    V(1):='ion';
    V(2):='MARIUS';
    V(3):='MARIA';
    V(4):='ANA';
    DBMS_OUTPUT.PUT_LINE(V(2));
    DBMS_OUTPUT.PUT_LINE('NR='||V.COUNT);
    DBMS_OUTPUT.PUT_LINE('PRIMUL='||v.FIRST); --af indexul primul element ->1
    DBMS_OUTPUT.PUT_LINE('ULTIMUL='||v.LAST); --af indexul ultimul element ->4
    V.DELETE(3,4);
    DBMS_OUTPUT.PUT_LINE('NR='||V.COUNT);
END;
/

DECLARE 
    TYPE T_ANG IS TABLE OF VARCHAR2(100)INDEX BY PLS_INTEGER;
    V T_ANG;
BEGIN
    V(1):='ION';
    V(2):='MARIUS';
    V(3):='MARIA';
    V(40):='ANA';
    
    FOR I IN V.FIRST..V.LAST LOOP
        CONTINUE WHEN NOT V.EXISTS(I);
        DBMS_OUTPUT.PUT_LINE(I||'->'||V(I));
    END LOOP;
END;
/

DECLARE
    TYPE T_ANG IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER;
    V T_ANG; 
    
BEGIN
    V(1):='ION';
    V(2):='MARIUS';
    V(3):='MARIA';
    V(4):='ANA';
    
    FOR I in 1 .. V.COUNT LOOP
        DBMS_OUTPUT.PUT_LINE(I||'->'||V(i));
    END LOOP;
    
END;
/

DECLARE
    TYPE T_ANG IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER;
    V T_ANG; 
    I PLS_INTEGER;
    
BEGIN
    V(-1):='ION';
    V(2):='MARIUS';
    V(3):='MARIA';
    V(40):='ANA';
    
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
    DBMS_OUTPUT.PUT_LINE(I||'->'||V(i));
        I:=V.NEXT(I);
    END LOOP;
        
END;
/

DECLARE
    TYPE T_ANG IS TABLE OF VARCHAR2(100)INDEX BY PLS_INTEGER;
    V T_ANG;
    I PLS_INTEGER;
BEGIN
    SELECT NUME||' '||PRENUME||' '||SALARIUL
    BULK COLLECT INTO V
    FROM ANGAJATI
    WHERE ID_FUNCTIE='SA_REP' 
    AND SALARIUL BETWEEN 5000 AND 9000
    ORDER BY SALARIUL DESC;
    
    DBMS_OUTPUT.PUT_LINE('NR='||V.COUNT);
    DBMS_OUTPUT.PUT_LINE('PRIMUL='||v.FIRST);
    DBMS_OUTPUT.PUT_LINE('ULTIMUL='||v.LAST);
    
    FOR I IN 1..V.COUNT LOOP
         DBMS_OUTPUT.PUT_LINE(I||'->'||V(i));
    END LOOP;
    
    --sau
    
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(I||'->'||V(i));
        I:=V.NEXT(I);
    END LOOP;
    
END;
/


DECLARE
    TYPE R_ANG IS RECORD(
    NUME VARCHAR2(30),
    PRENUME VARCHAR2(30),
    SALARIUL NUMBER);
    
    TYPE T_ANG IS TABLE OF R_ANG INDEX BY PLS_INTEGER;
    V T_ANG;
    I PLS_INTEGER;
BEGIN
    SELECT NUME,PRENUME,SALARIUL    
    BULK COLLECT INTO V 
    FROM ANGAJATI
    WHERE ID_FUNCTIE = 'SA_REP'
    AND SALARIUL BETWEEN 5000 AND 9000
    ORDER BY SALARIUL DESC;
    
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(V(I).NUME||' '||V(I).PRENUME||' '||V(I).SALARIUL);
        I:=V.NEXT(I);
    END LOOP;
END;
/

--SEMINAR 5
--INDEX BY TABLE - NU STOCHEAZA IN DB, RESTU DA

--IN INDEX BY TABLE SI NESTED TABLE, PUTEM FACE V.DELETE, SI DE LA MIJLOC
DECLARE
    TYPE R_PROD IS RECORD(
    DENUMIRE_PRODUS VARCHAR2(50),
    VALOARE_TOTALA NUMBER,
    DATA_ULTIMA_COMANDA TIMESTAMP);
    
    TYPE T_PR IS TABLE OF R_PROD INDEX BY PLS_INTEGER; 
    V T_PR;
    I PLS_INTEGER;
BEGIN
    SELECT P.DENUMIRE_PRODUS,
            SUM(R.CANTITATE*R.PRET) VALOARE_TOTALA,
            MAX(C.DATA) AS DATA_ULTIMA_COMANDA
    BULK COLLECT INTO V
    FROM PRODUSE P
    JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
    JOIN COMENZI C ON R.ID_COMANDA=C.ID_COMANDA
    GROUP BY P.DENUMIRE_PRODUS
    ORDER BY MAX(C.DATA) DESC;
    
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
     DBMS_OUTPUT.PUT_LINE(V(I).denumire_produs || ' || Total=' || V(I).valoare_totala ||  ' || Ultima comanda=' || V(I).data_ultima_comanda);
     I:=V.NEXT(I);
     END LOOP;
END;
/



DECLARE
    TYPE R_PROD IS RECORD(
    DENUMIRE_PRODUS VARCHAR2(50),
    VALOARE_TOTALA NUMBER,
    DATA_ULTIMA_COMANDA TIMESTAMP);
    
    TYPE T_PR IS TABLE OF R_PROD; --NESTED TABLE --INDEXATE NUMERIC
    V T_PR;
    I PLS_INTEGER;
    
BEGIN
SELECT p.denumire_produs,
           SUM(r.cantitate * r.pret) AS valoare_totala,
           MAX(c.data) AS data_ultima_comanda
    BULK COLLECT INTO V
    FROM produse p
    JOIN rand_comenzi r ON p.id_produs = r.id_produs
    JOIN comenzi c ON r.id_comanda = c.id_comanda
    GROUP BY p.denumire_produs
    ORDER BY max(c.data) DESC;
    
    V.TRIM;--sterge ultimul elemnent din collectie

    I := V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(V(I).denumire_produs || ' || Total=' || V(I).valoare_totala ||  ' || Ultima comanda=' || V(I).data_ultima_comanda);
        I := V.NEXT(I);
    END LOOP;
    V.DELETE;
END;
/


--VARRAY
-- NU PUTEM STERGE VALORI DE LA MIJLOC

DECLARE
    TYPE R_PR IS RECORD(
        denumire_produs VARCHAR2(50),
        valoare_totala NUMBER,
        data_ultima_comanda TIMESTAMP
    );
    
    TYPE T_PR IS VARRAY(200) OF R_PR; --MAXIM 200
    V T_PR;
    I PLS_INTEGER;
BEGIN
    SELECT p.denumire_produs,
           SUM(r.cantitate * r.pret) AS valoare_totala,
           MAX(c.data) AS data_ultima_comanda
    BULK COLLECT INTO V
    FROM produse p
    JOIN rand_comenzi r ON p.id_produs = r.id_produs
    JOIN comenzi c ON r.id_comanda = c.id_comanda
    GROUP BY p.denumire_produs
    ORDER BY max(c.data) DESC;
    
    --v.delete(5,180); nu putem sterge VALORI DE LA MIJLOC
    V.TRIM(5);--sterge ultimele 5 elemente
    I := V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(V(I).denumire_produs || ' || Total=' || V(I).valoare_totala ||  ' || Ultima comanda=' || V(I).data_ultima_comanda);
        I := V.NEXT(I);
    END LOOP;
END;
/

--SEMINAR 6
/*CURSORUL
    -IMPLICIT -CURSORUL SQL
        -SQL%FOUND, SQL%NOTFOUND, SQL%ROWCOUNT, SQL%ISOPEN 
        (NU PREA ARE UTILITATE,este mereu false)
*/

DECLARE
TYPE R_PR IS RECORD(
        denumire_produs VARCHAR2(50),
        valoare_totala NUMBER,
        data_ultima_comanda TIMESTAMP
    );
    
TYPE T_PR IS VARRAY(200) OF R_PR;
V T_PR;
I PLS_INTEGER;
BEGIN
    SELECT p.denumire_produs,
           SUM(r.cantitate * r.pret) AS valoare_totala,
           MAX(c.data) AS data_ultima_comanda
    BULK COLLECT INTO V
    FROM produse p
    JOIN rand_comenzi r ON p.id_produs = r.id_produs
    JOIN comenzi c ON r.id_comanda = c.id_comanda
    GROUP BY p.denumire_produs
    ORDER BY max(c.data) DESC;
    
    DBMS_OUTPUT.PUT_LINE(V.COUNT);
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
END;
/

BEGIN
    UPDATE ANGAJATI
    SET SALARIUL=SALARIUL*1.05
    WHERE ID_ANGAJAT IN(
    SELECT ID_ANGAJAT FROM COMENZI
    GROUP BY ID_ANGAJAT
    HAVING COUNT(*)>=2);
    
    IF SQL%FOUND THEN
         DBMS_OUTPUT.PUT_LINE('S-AU MODIFICAT SAL');
         DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
    ELSE 
     DBMS_OUTPUT.PUT_LINE('NU S-AU MODIFICAT SAL');
    END IF;
    
END;
/
    
DECLARE 
    TYPE T_ANG IS TABLE OF NUMBER;
    V T_ANG;
BEGIN
    UPDATE ANGAJATI 
    SET SALARIUL=SALARIUL*1.05
    WHERE ID_ANGAJAT IN(
    SELECT ID_ANGAJAT 
    FROM COMENZI
    GROUP BY ID_ANGAJAT
    HAVING COUNT(*)>=2) RETURNING ID_ANGAJAT BULK COLLECT INTO V;
    
      FOR I in 1..V.COUNT LOOP
        DBMS_OUTPUT.PUT_LINE(V(I));
    END LOOP;
END;
/

-- SA SE STEARGA TOATE PRODUSELE CARE NU FOST COMANDATE NICIODATA
--SA SE AFISEZE NR DE PRODUSE STERSE PRECUM SI DENUMIREA LOC

DECLARE
    TYPE R_PROD IS RECORD(
    ID_PRODUS NUMBER,
    DENUMIRE_PRODUS VARCHAR2(100));
    
    TYPE T_ANG IS TABLE OF R_PROD;
    V T_ANG;
BEGIN
    DELETE FROM PRODUSE
    WHERE ID_PRODUS NOT IN(
    SELECT ID_PRODUS
    FROM RAND_COMENZI
    GROUP BY ID_PRODUS)RETURNING ID_PRODUS,DENUMIRE_PRODUS BULK COLLECT INTO V;
    
    DBMS_OUTPUT.PUT_LINE(V.COUNT);
    
    FOR I in 1..V.COUNT LOOP
        DBMS_OUTPUT.PUT_LINE(V(I).ID_PRODUS|| '' ||v(i).denumire_produs);
    END LOOP;
    
END;
/


--CURSORUL EXPLICIT
--NUME_CURORS%ISOPEN
--NUME_CURSOR%FOUND
--NUME_CURSOR%NOTFOUND
--NUME_CURSOR%ROWCOUNT

--FOLOSIND UN CURSOR SA SE AFISEZE NUMELE SI PRENUMELE CLIENT 
--CARE AU DAT CEL PIUTIN 2 COMENZI
--CLIENTII SE VOR AFISA IN ORDINEA DESC A LIMIT CREDIT

DECLARE 
    CURSOR C IS 
    SELECT NUME_CLIENT,PRENUME_CLIENT,LIMITA_CREDIT
    FROM CLIENTI
    WHERE ID_CLIENT IN(
    SELECT ID_CLIENT
    FROM COMENZI
    GROUP BY ID_CLIENT
    HAVING COUNT(*)>=2)
    ORDER BY LIMITA_CREDIT DESC;
    
    R C%ROWTYPE;
BEGIN
    IF NOT C%ISOPEN THEN
        OPEN C;
    END IF;
    
    LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(C%ROWCOUNT||' '||R.NUME_CLIENT||' '||R.PRENUME_CLIENT||' '||R.LIMITA_CREDIT);
    END LOOP;
    CLOSE C;
        
END;
/

DECLARE
    CURSOR C IS SELECT NUME_CLIENT,PRENUME_CLIENT,LIMITA_CREDIT
    FROM CLIENTI
    WHERE ID_CLIENT IN(
    SELECT ID_CLIENT
    FROM COMENZI
    GROUP BY ID_CLIENT
    HAVING COUNT(*)>=2)
    ORDER BY LIMITA_CREDIT DESC;
        --FETCH FIRST 5 ROWS ONLY; -IA DOAR PRIMII 5 DIN SELECT
         --FETCH FIRST 5 ROWS WITH TIES --DACA MAI AFISEAZA UNA DUPA 5
    
    R C%ROWTYPE;
BEGIN
    IF NOT C%ISOPEN THEN
        OPEN C;
    END IF;
    
    LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND OR C%ROWCOUNT>5;
         DBMS_OUTPUT.PUT_LINE(C%ROWCOUNT||' '||R.NUME_CLIENT||' '||R.PRENUME_CLIENT||' '||R.LIMITA_CREDIT);
    END LOOP;
    
    CLOSE C;
END;
/


--FOLOSIND UN CURSOR SA SE AFISEZE DENUMIREA DEPARTAMENTELOR
--UNDE TOTI ANGAJATII AU SALARILE <=10000

DECLARE
    CURSOR C IS SELECT DENUMIRE_DEPARTAMENT
            FROM DEPARTAMENTE 
            WHERE ID_DEPARTAMENT IN(
            SELECT ID_DEPARTAMENT
            FROM ANGAJATI
            GROUP BY ID_DEPARTAMENT
            HAVING MAX(SALARIUL)<=10000);
    --R C%ROWTYPE;
BEGIN
   
   --CAND PARCURGERM CU FOR CURSORNUL NU TRB DESCHIS/INCHIS- DESCHIDE AUTOMAT SI L DECLARA PE 
   -- R CA C%ROWTYPE
   FOR R IN C LOOP
    DBMS_OUTPUT.PUT_LINE(C%ROWCOUNT||' '||R.DENUMIRE_DEPARTAMENT);
    END LOOP;
    
END;
/

--CURSOR IN LINE
BEGIN
    FOR R IN (SELECT DENUMIRE_DEPARTAMENT
                FROM DEPARTAMENTE 
                WHERE ID_DEPARTAMENT IN(
                SELECT ID_DEPARTAMENT 
                FROM ANGAJATI
                GROUP BY ID_DEPARTAMENT
                HAVING MAX(SALARIUL)<=10000))
                LOOP
                DBMS_OUTPUT.PUT_LINE(R.DENUMIRE_DEPARTAMENT);
                END LOOP;
END;
/

--FOLOSIND UN CURSOR,
--SA SE AFISEZE DENUMIREA CATEGORIILOR DE PRODUSE SI VALOAREA TOTALA A COMENZILOR
--DIN PERSPECTIVELE CATEGORII. SE VOR AFISA DOAR CATEG CU VAL TOTALA A COMENZILOR >500000

DECLARE
CURSOR C IS SELECT 
P.CATEGORIE,
SUM(R.CANTITATE*R.PRET) AS VAL_T
FROM PRODUSE P
JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
GROUP BY P.CATEGORIE
HAVING SUM(R.PRET*R.CANTITATE)>50000;
BEGIN
    FOR R IN C LOOP
    DBMS_OUTPUT.PUT_LINE(R.CATEGORIE);
    END LOOP;
END;
/

--SEMINAR 7
--CURSOR PARAMETRIZAT
--FOLOSIND UN CURSOR, SA SE AFISEZE DENUMIREA CATEGORIILOR DE PRODUSE SI VALOAREA TOTALA A COMENZILOR
--DIN PERSPECTIVELE CATEGORII. SE VOR AFISA DOAR CATEG CU VAL TOTALA A COMENZILOR >500000
--PT FIECARE CATEOGIRE SE VOR AFISA PRODUSELE DIN ACEA CATEGORIE SI VALOAREA TOALA COMENZILOR

DECLARE
    CURSOR C IS SELECT 
    P.CATEGORIE,
    SUM(R.CANTITATE*R.PRET) AS VAL_T
    FROM PRODUSE P
    JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
    GROUP BY P.CATEGORIE
    HAVING SUM(R.PRET*R.CANTITATE)>50000;

    CURSOR D(P_CATEG VARCHAR2)IS SELECT
    P.DENUMIRE_PRODUS,
    CATEGORIE,
    SUM(R.PRET *R.CANTITATE) AS VAL_T
    FROM PRODUSE P, RAND_COMENZI R 
    WHERE P.ID_PRODUS=R.ID_PRODUS
    AND P.CATEGORIE=P_CATEG
    GROUP BY P.denumire_produs,categorie;
BEGIN

    FOR R IN C LOOP
        DBMS_OUTPUT.PUT_LINE(R.CATEGORIE);
        FOR S IN D(R.CATEGORIE) LOOP
            DBMS_OUTPUT.PUT_LINE(S.DENUMIRE_PRODUS||':'||S.VAL_T);
        END LOOP;
    END LOOP;
END;
/

----SA SE AFISEZE NUMELE SI PRENUMELE CLIENTULUI CARE A DAT CELE MAI MULTE COMENZI
--SE VOR AFISA COMENZILE PT RESPECTIVUL CLIENT 
-- ID_COMANDA, DATA, VAL TOATALA
DECLARE
    CURSOR C IS SELECT
    C.ID_CLIENT,
    C.NUME_CLIENT,
    C.PRENUME_CLIENT,
    COUNT(*) AS NR_COM
    FROM CLIENTI C
    JOIN COMENZI CO ON C.ID_CLIENT=CO.ID_CLIENT
    GROUP BY C.ID_CLIENT,C.NUME_CLIENT,C.PRENUME_CLIENT
    ORDER BY COUNT(*) DESC  FETCH FIRST 1 ROW WITH TIES;
    
    CURSOR C2(P_ID NUMBER) IS
    SELECT c.id_comanda,
               c.data,
               SUM(r.pret * r.cantitate) AS val_tot
        FROM comenzi c
        JOIN rand_comenzi r ON c.id_comanda = r.id_comanda
        WHERE c.id_client = P_ID
        GROUP BY c.id_comanda, c.data;
BEGIN
    FOR R IN C LOOP
     DBMS_OUTPUT.PUT_LINE('Client: ' || R.nume_client || ' ' || R.prenume_client);
         FOR S IN C2(R.ID_CLIENT) LOOP
            DBMS_OUTPUT.PUT_LINE('Comanda: ' || S.id_comanda ||' Data: ' || S.data||' Total: ' || S.val_tot);
         END LOOP;
    END LOOP;
END;
/
--CURSORUL FOR UPDATE -PUTEM SA ACTUALIZAM PE MASURA CE PARC CURSORUL

--FOLOSIND UN CURSOR SA SE MAREASCA CU 5% PRETUL DE LISTA PT PRODUSELE CARE
--APAR IN CEL PUTIN 5 COMENZI DISTINCTE

DECLARE 
  CURSOR C IS SELECT P.ID_PRODUS,DENUMIRE_PRODUS,PRET_LISTA 
  FROM PRODUSE P
  WHERE P.ID_PRODUS IN (
  SELECT R.ID_PRODUS
  FROM RAND_COMENZI R
  GROUP BY R.ID_PRODUS
  HAVING COUNT(R.ID_PRODUS)>=5) FOR UPDATE WAIT 5; -- SAU NOWAIT
BEGIN
   FOR R IN C LOOP
     UPDATE PRODUSE 
     SET PRET_LISTA=PRET_LISTA*1.05 WHERE CURRENT OF C;
     DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS||' '||R.DENUMIRE_PRODUS||' '||R.PRET_LISTA);
     -- AFISEAZA DATELE DE LA DESCHIDEREA CURSORULUI, NU CELE ACTUALIZATE
   END LOOP;
   DBMS_OUTPUT.NEW_LINE;
  
  FOR R IN C LOOP     
     DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS||' '||R.DENUMIRE_PRODUS||' '||R.PRET_LISTA);
   END LOOP;
   
   EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('NU AM PUTUT BLOCA RANDURILE PENTRU ACTUALIZARE');
END;
/

--SEMINAR 8 SI 9
/*
-COMPILATION TIME ERROS

-RUN TIME ERRORS    
    EXCEPTII
    -IMPLICITE  
        -PREDEFINITE:NO_DATA_FOUND,TOO_MANY_ROWS,DUP_VAL_ON_INDEX(DACA EXISTA O VAL),INVALID_CURSOR..
        -NONPREDEFINITE: AU COD EXCEPTIE DAR NU AU SI HANDLER UL EXCEPITIE
    -EXPLICITE
        -DEFINITE DE UTILIZATOR
        
--INTERVALUL DE CODURI PT EXCEPTILE DEFINITE DE UTILIZATOR ESTE  -20999 ... -20000
*/
DECLARE
  I NUMBER(3);
  CURSOR C IS SELECT * FROM ANGAJATI;
  R C%ROWTYPE;
BEGIN
I:=100;
I:=I/0; 
 EXCEPTION 
   WHEN ZERO_DIVIDE THEN
    BEGIN
    DBMS_OUTPUT.PUT_LINE('NU PUTEM IMPARTI LA ZERO');
    FETCH C INTO R;  
      EXCEPTION WHEN OTHERS THEN 
       DBMS_OUTPUT.PUT_LINE('EXCEPTIE IN EXCEPTIE');
    END;
    
   WHEN INVALID_CURSOR OR VALUE_ERROR THEN  
   DBMS_OUTPUT.PUT_LINE('CURSORUL NU A FOST DESCHIS SAU VARIABILA ARE O DIMENSIUNE PREA MICA');
   WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('A APARUT O EXCEPTIE');
     DBMS_OUTPUT.PUT_LINE(SQLERRM);
     DBMS_OUTPUT.PUT_LINE(SQLCODE);     
END;
/

DECLARE
    ESTE_MANAGER EXCEPTION;
    PRAGMA EXCEPTION_INIT(ESTE_MANAGER,-2292);
BEGIN
    DELETE FROM ANGAJATI WHERE ID_ANGAJAT=100;
    EXCEPTION
        WHEN ESTE_MANAGER THEN
            DBMS_OUTPUT.PUT_LINE('NU POT STERGE ANGAJATUL, SE INCALCA UN FK');
END;
/

--FOLOSIND O EXCEPTIE SA SE REZOLVE URMATOAREA CERINTA
--SA SE ADAUGE UN ANGAJAT CU ID-UL CITIT DE LA TASTARU SI SALARIUL CITIT DE LA TASTATURA
--DACA ANGAJATUL EXISTA, I SE VA MODIFCA SALARIUL CU CEL CITIT

ACCEPT P_ID_ANG PROMPT  "INTRODUCETI ID-UL ANGAJATULUI" 
ACCEPT P_SALARIUL PROMPT "INTRODUCETI SALARIUL ANGAJATULUI" 
BEGIN
    INSERT INTO ANGAJATI(ID_ANGAJAT,NUME,EMAIL,ID_FUNCTIE,DATA_ANGAJARE,SALARIUL) VALUES
    (&P_ID_ANG,'JOHNSON','JOHNSON@GMAIL.COM','SA_REP',SYSDATE-30, &P_SALARIUL);
    
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
         UPDATE ANGAJATI SET SALARIUL=&P_SALARIUL WHERE ID_ANGAJAT=&P_ID_ANG;
        
END;
/

SELECT * FROM ANGAJATI;
-- SA SE CONSTRUIASCA TABELA PERSOANE(ID_PERS,NUME,PRENUME)
-- DACA TABELA EXISTA SA SE STEARGA TABELA CLIENTI
--IN PLSQL PUTEM RULA INSTRUCTIUNI LMD SI LCT DIRECT
--PUTEM RULA INSTRUCTIUNI LDD SI LCD FOLOSIND EXECUTE IMMEDIATE SAU DBMS_SQL

CREATE TABLE PERSOANE(ID_PERS NUMBER, NUME VARCHAR2(30), PRENUME VARCHAR2(30));
-- DE AICI IAU CODUL DE EROARE;
    
DECLARE
    TABELA_EXISTA EXCEPTION;
    PRAGMA EXCEPTION_INIT(TABELA_EXISTA,-955);
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE PERSOANE(ID_PERS NUMBER, NUME VARCHAR2(30), PRENUME VARCHAR2(30))';
    
    EXECUTE IMMEDIATE 'INSERT INTO PERSOANE VALUES(1,''POPESCU'',''MARIUS'')';
    COMMIT;
    
    EXCEPTION WHEN TABELA_EXISTA THEN
        EXECUTE IMMEDIATE 'DROP TABLE PERSOANE';
END;
/

DECLARE
    EX_PRODUS EXCEPTION;
    NU_EXISTA EXCEPTION;
    PRAGMA EXCEPTION_INIT(EX_PRODUS,-2292);
BEGIN
    DELETE FROM PRODUSE WHERE ID_PRODUS>=35000;
    IF SQL%NOTFOUND THEN
        RAISE NU_EXISTA ;
    ELSE
    DBMS_OUTPUT.PUT_LINE('S-AU STERS'||SQL%ROWCOUNT||'PRDOSUE');
    END IF;
    
    EXCEPTION
        WHEN EX_PRODUS THEN
            DBMS_OUTPUT.PUT_LINE('NU SE POATE STERGE ACEST PRODUS');
    WHEN NU_EXISTA  THEN
        DBMS_OUTPUT.PUT_LINE('A APARUT EXCEPTIA');
    
END;
/

--EXCEPTII DEF DE UTILIZATOR

DECLARE
    EX_PRODUS EXCEPTION;
    NU_EXISTA EXCEPTION;
    PRAGMA EXCEPTION_INIT(EX_PRODUS,-2292);
    PRAGMA EXCEPTION_INIT(NU_EXISTA,-20000);
BEGIN
    DELETE FROM PRODUSE WHERE ID_PRODUS>=35000;
    IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR(-20000,'NU EXISTA PROD');
    ELSE
    DBMS_OUTPUT.PUT_LINE('S-AU STERS'||SQL%ROWCOUNT||'PRDOSUE');
    END IF;
    
    EXCEPTION
        WHEN EX_PRODUS THEN
            DBMS_OUTPUT.PUT_LINE('NU SE POATE STERGE ACEST PRODUS');
    WHEN NU_EXISTA  THEN
        DBMS_OUTPUT.PUT_LINE('A APARUT EXCEPTIA');
    
END;
/


--SEMINAR 10
--PROCEDURI SI FUNCTII=PUTEM SA STOCAM COD IN BAZA DE DATE

CREATE OR REPLACE PROCEDURE STERGE_PRODUS IS
    EX_PRODUS EXCEPTION;
    NU_EXISTA EXCEPTION;
    PRAGMA EXCEPTION_INIT(EX_PRODUS,-2292);
    PRAGMA EXCEPTION_INIT(NU_EXISTA,-20000);
BEGIN
    DELETE FROM PRODUSE WHERE ID_PRODUS>=35000;
    IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR(-20000,'NU EXISTA PROD');
    ELSE
    DBMS_OUTPUT.PUT_LINE('S-AU STERS'||SQL%ROWCOUNT||'PRDOSUE');
    END IF;
    
    EXCEPTION
        WHEN EX_PRODUS THEN
            DBMS_OUTPUT.PUT_LINE('NU SE POATE STERGE ACEST PRODUS');
    WHEN NU_EXISTA  THEN
        DBMS_OUTPUT.PUT_LINE('A APARUT EXCEPTIA');
END;
/

EXEC STERGE_PRODUS; --APEL TIP PL/SQL
CALL STERGE_PRODUS(); --APEL TIP SQL

--putem trata execptia in blocul operator sau in bloc anonim

--APELEZ PROCEDURA DINTR UN BLOC ANONIM

DECLARE
    NU_EXISTA EXCEPTION;
    PRAGMA EXCEPTION_INIT(NU_EXISTA,-20000);
BEGIN
    STERGE_PRODUS;
    EXCEPTION
    WHEN NU_EXISTA THEN
        DBMS_OUTPUT.PUT_LINE('A APARUT EXCEPTIA');
END;
/



/* SUBPROGRAMARE POT AVEA PARAMETRII
    IN-(VAR IMPLICITA)
    OUT
    IN OUT
*/

DROP PROCEDURE MARESTE_PRET_PROD;
--SA SE MODIFICE PROCEDURA ASTFEL INCAT SA SE AFISEZE SI PRRETUL NOU

CREATE OR REPLACE PROCEDURE MARESTE_PRET_PROD(P_ID_PRODUS NUMBER, P_PROCENT NUMBER) IS
V_PRET NUMBER;
BEGIN
    SELECT PRET_LISTA INTO V_PRET
    FROM PRODUSE 
    WHERE ID_PRODUS=P_ID_PRODUS;
    DBMS_OUTPUT.PUT_LINE('PRETUL VECHI ESTE '||V_PRET);
    
    UPDATE PRODUSE
    SET PRET_LISTA=PRET_LISTA*(100+P_PROCENT)/100
    WHERE ID_PRODUS=P_ID_PRODUS;
    
    SELECT PRET_LISTA INTO V_PRET
    FROM PRODUSE
    WHERE ID_PRODUS=P_ID_PRODUS;
    DBMS_OUTPUT.PUT_LINE('PRETUL NOU ESTE '||V_PRET);
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            NULL;
END;
/

EXEC MARESTE_PRET_PROD(2378,10);

BEGIN
MARESTE_PRET_PROD(2378,10);
END;
/

CREATE OR REPLACE PROCEDURE MARESTE_PRET_PROD2(P_ID_PRODUS NUMBER,P_PROCENT NUMBER) IS
V_PRET NUMBER;
BEGIN   
   UPDATE PRODUSE 
   SET PRET_LISTA=PRET_LISTA*(100+P_PROCENT)/100 
   WHERE ID_PRODUS=P_ID_PRODUS
   RETURNING PRET_LISTA INTO V_PRET;  
   
   IF SQL%FOUND THEN
   DBMS_OUTPUT.PUT_LINE('PRETUL NOU ESTE '||V_PRET);
   END IF;
END;
/

BEGIN
MARESTE_PRET_PROD2(101,10);
END;
/

CREATE OR REPLACE PROCEDURE MARESTE_PRET_PROD3(P_ID_PRODUS NUMBER,P_PROCENT NUMBER, P_PRET_NOU OUT NUMBER) IS
BEGIN   
   UPDATE PRODUSE SET PRET_LISTA=PRET_LISTA*(100+P_PROCENT)/100 WHERE ID_PRODUS=P_ID_PRODUS
   RETURNING PRET_LISTA INTO P_PRET_NOU;    
END;
/
DECLARE
  P NUMBER;
BEGIN
MARESTE_PRET_PROD3(2378,10,P);
IF P IS NOT NULL THEN
DBMS_OUTPUT.PUT_LINE('PRETUL NOU ESTE '||P);
END IF;
END;
/

CREATE OR REPLACE PROCEDURE MARESTE_PRET_PROD3(P_ID_PRODUS NUMBER, P_PROCENT NUMBER DEFAULT 5,P_PRET_NOU OUT NUMBER) IS
BEGIN
    UPDATE PRODUSE 
    SET PRET_LISTA=PRET_LISTA*(100+P_PROCENT)/100
    WHERE ID_PRODUS=NVL(P_ID_PRODUS,ID_PRODUS)
    RETURNING PRET_LISTA INTO P_PRET_NOU;
    EXCEPTION
        WHEN TOO_MANY_ROWS THEN 
        UPDATE PRODUSE 
        SET PRET_LISTA=PRET_LISTA*(100+P_PROCENT)/100 
        WHERE ID_PRODUS=NVL(P_ID_PRODUS,ID_PRODUS);
        P_PRET_NOU:=SQL%ROWCOUNT; --VEI RETURNA NUMARUL DE RANDURI MODIFICARE NU PRETUL NOU  
END;
/
DECLARE
    P NUMBER;
BEGIN
    MARESTE_PRET_PROD3(P_PRET_NOU=>P,P_ID_PRODUS=>2378,P_PROCENT=>10);
    IF P IS NOT NULL THEN
    DBMS_OUTPUT.PUT_LINE('PRETUL NOU ESTE' ||P);
    ELSE
    DBMS_OUTPUT.PUT_LINE('NU S-A MODIFICAT NICIUN PRODUS');
    END IF;
END;
/


-- SA SE CONSTRUIASACA O PROCEDURA CARE PRIMESTE O CATEG DE PRODUSE SI AFISEAZA DENUMIREA 
--FIECAURI PRODUS DIN ACEEA CATEGORIE PRECUM SI VALOAREA TOTALA A COMENZIILOR
--PT FIECARE PRODUS.DACA CATEGORIA NU EXISTA, SA SE RIDICE O EXCEPTIE

CREATE OR REPLACE PROCEDURE AFISARE_PROD(P_CATEGORIE VARCHAR2)IS
CURSOR C IS 
    SELECT P.DENUMIRE_PRODUS,
    SUM(R.PRET*R.CANTITATE) AS VALOARE
    FROM PRODUSE P
    JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
    WHERE CATEGORIE=P_CATEGORIE
    GROUP BY P.DENUMIRE_PRODUS;
R C%ROWTYPE;
BEGIN
   OPEN C;
    LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(R.DENUMIRE_PRODUS||'->'||R.VALOARE);
    END LOOP;
    
   
    IF C%ROWCOUNT=0 THEN
        RAISE_APPLICATION_ERROR(-20000,'NU SUNT PRODUSE IN ACEA CATEGORIE');
    END IF;
    CLOSE C;
END;
/

DECLARE
    NU_EXISTA_PROD EXCEPTION;
    PRAGMA EXCEPTION_INIT(NU_EXISTA_PROD,-20000);
BEGIN
    AFISARE_PROD(P_CATEGORIE=>'office2');
    EXCEPTION
        WHEN NU_EXISTA_PROD THEN
        DBMS_OUTPUT.PUT_LINE('A APARUT O EXCEPTIE:'||SQLERRM);
END;
/

--SA SE CONSTRUIASAC O FUNCTIE CARE PRIMESTE ID UL UNUI PRODUS IS RETURNEAZA 
--VALOAREA TOTALA A COMENZILOR PT REPSECTIVUL PRODUS
--SA SE APELEZE DINTR UN CURSOR

CREATE OR REPLACE FUNCTION GET_VAL_COM_PROD(P_ID_PRODUS NUMBER)RETURN NUMBER IS
V_VAL NUMBER;
BEGIN
    SELECT SUM(PRET* CANTITATE) INTO V_VAL
    FROM RAND_COMENZI
    WHERE ID_PRODUS=P_ID_PRODUS;
    
    RETURN NVL(V_VAL,0); 
END;
/

--APELARE BLOC ANONIM
DECLARE 
V_VAL NUMBER;
BEGIN
V_VAL:=GET_VAL_COM_PROD(1820);
DBMS_OUTPUT.PUT_LINE('VALOARE COMENZI:'||V_VAL);
END;
/
--FUNCTIILE DEFINITIE IN PL POT FUNCTIA CA SI FUNCTII SQL IN COMENZI SQL
SELECT ID_PRODUS,DENUMIRE_PRODUS,GET_VAL_COM_PROD(ID_PRODUS) VAL FROM PRODUSE
WHERE GET_VAL_COM_PROD(ID_PRODUS)>5000
ORDER BY GET_VAL_COM_PROD(ID_PRODUS)DESC;

--Apelare cu cursor
DECLARE
    CURSOR C IS SELECT
        ID_PRODUS,
        DENUMIRE_PRODUS,
        GET_VAL_COM_PROD(ID_PRODUS) VAL 
        FROM PRODUSE
        WHERE GET_VAL_COM_PROD(ID_PRODUS)>5000
        ORDER BY GET_VAL_COM_PROD(ID_PRODUS)DESC;
BEGIN
    FOR R IN C LOOP
        DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS||'->'||R.DENUMIRE_PRODUS||'->'||R.VAL);
    END LOOP;
END;
/


-- PACHETE GRUPEAZA FUNCTII SI PROCEDURI + VARIABILE, CURSORI, EXCEPTII, TYPE-URI
-- SPEC (PUBLICA)
-- BODY (PRIVATA) --aici avem implementarile

CREATE OR REPLACE PACKAGE MYPACK IS
    V_COTA NUMBER(2):=21;
 PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER);
 PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER, N3 NUMBER); -- PUTEM SUPRAINCARCA FUNCTII SI PROCEDURI IN INTERIORUL PACHETULUI
 FUNCTION MULTIPLY_NUMBERS(N1 NUMBER,N2 NUMBER) RETURN NUMBER;
END;
/

--IN BODY TRB SA IMPLEMENTEZ CEL PUTIN FUNCTIILE SI PROCEDURILE DIN SPEC
--SE POT CONSTRUI SI ALTE FUNCTII SI PROCEDURI PRIVATE

CREATE OR REPLACE PACKAGE BODY MYPACK IS
V_COTA NUMBER(2):=21;
PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER) IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('SUMA ESTE='||(N1+N2));
END;

PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER,N3 NUMBER) IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('SUMA ESTE='||(N1+N2+N3));
END;

FUNCTION MULTIPLY_NUMBERS(N1 NUMBER,N2 NUMBER) RETURN NUMBER IS
BEGIN
    RETURN N1*N2;
END;
END;
/

BEGIN
  DBMS_OUTPUT.PUT_LINE('COTA='||MYPACK.V_COTA);
  MYPACK.V_COTA:=27;
  DBMS_OUTPUT.PUT_LINE('COTA='||MYPACK.V_COTA);
  MYPACK.ADD_NUMBERS(10,25);
  MYPACK.ADD_NUMBERS(10,25,25);
  
  DBMS_OUTPUT.PUT_LINE(MYPACK.MULTIPLY_NUMBERS(15,17));
END;
/
--SA SE CONSTRUIASAC UN PACHET CARE CONTINE 
--O FUNCTIE CARE PRIMESTE CA PARAMETRUL ID UL UNUI PRODUS SI UN AN CALENDARISITIC(EX 2019)
--FUNCTIA VA RETURNA VALOAREA TOTALA PENTRU COMENZILE PRODUSULUI RESPECTIV IN ANUL RESPECTOV
-- O PROCEDURA CARE APELEAZA FUNCTIA DINTR UN CURSOR,PROCEDURA VA DECLANSA O EXCEPTIE DEFINITA DE UTILIZATOR
--EXCEPTIA SE VA DECLANSA DACA VAL COMENZILOR PENTRU ACEL AN <500.000
--SA SE APELEZE PROCEDURA DINTR UN BLOC ANONIMC, SA SE TRATEZE EXCEPTIA FARA A FOLOSI OTHERS

CREATE OR REPLACE PACKAGE PACK IS
FUNCTION TOTAL_VANZARI(P_ID_PRODUS NUMBER,P_AN NUMBER) RETURN NUMBER;
PROCEDURE AFISARE_TOTALA(P_AN NUMBER);
VAL_MICA EXCEPTION;
PRAGMA EXCEPTION_INIT(VAL_MICA,-20001);
END;
/

CREATE OR REPLACE PACKAGE BODY PACK IS
    FUNCTION TOTAL_VANZARI(P_ID_PRODUS NUMBER,P_AN NUMBER) RETURN NUMBER IS
    V_VAL NUMBER;
    BEGIN
        SELECT SUM(R.PRET*R.CANTITATE)INTO V_VAL
        FROM COMENZI C
        JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
        WHERE EXTRACT(YEAR FROM DATA)=P_AN AND R.ID_PRODUS=P_ID_PRODUS;
        
        RETURN NVL(V_VAL,0);
    END;
    
    PROCEDURE AFISARE_TOTALA(P_AN NUMBER) IS
        CURSOR C IS SELECT
            ID_PRODUS,
            DENUMIRE_PRODUS,
            TOTAL_VANZARI(ID_PRODUS,P_AN) VAL
            FROM PRODUSE
            ORDER BY VAL DESC;
        R C%ROWTYPE;
        V_SUMA NUMBER DEFAULT 0;
        BEGIN
            OPEN C;
            LOOP
                FETCH C INTO R;
                EXIT WHEN C%NOTFOUND;
                DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS||' '||R.DENUMIRE_PRODUS||' '||R.VAL);
                V_SUMA:=V_SUMA+R.VAL;
            END LOOP;
            CLOSE C;
            
            IF V_SUMA<700000 THEN
                RAISE_APPLICATION_ERROR(-20001,'SUMA TOTALA ESTE MAI MICA');
            END IF;
        END;
END;
/

-- EXCEPTIILE POT FI DECLARATE SI ASOCIATE CU UN COD DE EXCEPTIE SI IN PARTEA PUBLICA A UNUI PACJET
BEGIN
    PACK.AFISARE_TOTALA(2020);
    EXCEPTION
        WHEN PACK.VAL_MICA THEN
            DBMS_OUTPUT.PUT_LINE('Eroare');
END;
/

--SEMINAR12
/*Declansatorii -Triggeri

la nivel de instructiune(se executa o sigura data/instructiune indiferent cate randuri sunt afectate)
la nivel de rand(o data/pentru ficare rand afectat)

BEFORE          INSERT
AFTER           UPDATE      (TABLE)
                DELETE
                
INSTEAD OF      INSERT/UPDATE/DELETE (VIEW)
*/
--COMMIT SI ROLLBACK NU SE FOLOESC IN INTERIORUL UNUI TRIGGER

--SA SE CONSTRUIASCA UN TRIGGER CARE NU PERMITE 
--ADAUGAREA DE COMENZI DUPA ORA 16:00
--MODIFICAREA DE COMENZI DUPA ORA 16:10
--STERGEREA DE COMENZI DUPA ORA 16:20

CREATE OR REPLACE TRIGGER VERIF_ORA BEFORE INSERT OR UPDATE OR DELETE ON COMENZI
BEGIN
    IF INSERTING AND TO_CHAR(SYSDATE,'HH24:MI')>='16:00' THEN
        RAISE_APPLICATION_ERROR(-20000,'NU SE POATE AD DUPA ORA 16');
    ELSIF UPDATING AND TO_CHAR(SYSDATE,'HH24:MI')>='16:1O' THEN
          RAISE_APPLICATION_ERROR(-20000,'NU SE POT MODIFICA COMENZI DUPA PRA 16:10');
    ELSIF DELETING AND TO_CHAR(SYSDATE,'HH24:MI')>='16:20'THEN
        RAISE_APPLICATION_ERROR(-20000,'NU SE POT STERGE COMENZI DUPA PRA 16:20');
    END IF;
END;
/

UPDATE COMENZI 
SET STARE_COMANDA=STARE_COMANDA+1 
WHERE ID_COMANDA>2430;

--SA SE CONSTRUIASCA UN TRIGGER CARE SA PERMITA MAXIM 5 RANDURI IN TABELA REGIUNI
CREATE OR REPLACE TRIGGER VERIF_REG BEFORE INSERT ON REGIUNI
DECLARE
    NR NUMBER;
BEGIN
    SELECT COUNT(*) INTO NR FROM REGIUNI;
    IF NR>=5 THEN
        RAISE_APPLICATION_ERROR(-20000,'MAXIM 5 RANDURI IN TAB');
    END IF;
END;
/

INSERT INTO REGIUNI VALUES (5, 'Asia');
-- LA TRIGGERI AFTER, MAI INTAI SE DECLANSEAZA RESTR DE INTEGRITATE, DACA ESTE CAZUL
INSERT INTO REGIUNI VALUES(6,'REGIUNEA 6');
  

/*
FOR EACH ROW
            :NEW   :OLD
INSERT       X      NULL
UPDATE       X      X 
DELETE      NULL    X;
*/

CREATE OR REPLACE TRIGGER VERF_SAL BEFORE UPDATE ON ANGAJATI FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('SE MODOFICA SALARIUL PENTRU '||:NEW.ID_ANGAJAT||' DIN '||:OLD.SALARIUL||' IN '||:NEW.SALARIUL);
END;
/

UPDATE ANGAJATI
SET SALARIUL=SALARIUL*1.01
WHERE ID_ANGAJAT>180;



--SA SE CONSTRUIASACA UN TRIGGER CARE 
--NU PERMITE MICSORAREA SALARIILOR ANGAJATI AU INTERMEDIAT CEL PUTIN 2 COMENZI

CREATE OR REPLACE TRIGGER VERF_SAL BEFORE UPDATE OF SALARIUL ON ANGAJATI FOR EACH ROW
DECLARE 
    N NUMBER;
BEGIN
     DBMS_OUTPUT.PUT_LINE('SE MODOFICA SALARIUL PENTRU '||:NEW.ID_ANGAJAT||' DIN '||:OLD.SALARIUL||' IN '||:NEW.SALARIUL);
     IF :NEW.SALARIUL<:OLD.SALARIUL THEN
        SELECT COUNT(*) INTO N FROM COMENZI C
        WHERE C.ID_ANGAJAT=:NEW.ID_ANGAJAT;
        IF N>=2 THEN
            RAISE_APPLICATION_ERROR(-20001,'nu se poate modifica salariul pt acest angajat'||:NEW.ID_ANGAJAT);
        END IF;
    END IF;
END;
/
UPDATE ANGAJATI 
SET COMISION=COMISION*1.01 WHERE ID_ANGAJAT>180;


CREATE OR REPLACE TRIGGER VERF1 BEFORE UPDATE OF SALARIUL ON ANGAJATI FOR EACH ROW
DECLARE 
    N NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('SE MODOFICA SALARIUL PENTRU '||:NEW.ID_ANGAJAT||' DIN '||:OLD.SALARIUL||' IN '||:NEW.SALARIUL);
    IF :NEW.SALARIUL<:OLD.SALARIUL THEN
        SELECT COUNT(*) INTO N FROM COMENZI
        WHERE ID_ANGAJAT=:NEW.ID_ANGAJAT;
        IF N>=2 THEN
            :NEW.SALARIUL:=:OLD.SALARIUL;--MERGE DOAR PT TRIGGER BEFORE..
        END IF;
    END IF;
END;
/
UPDATE ANGAJATI
SET SALARIUL=SALARIUL-5 
WHERE ID_ANGAJAT>140;

CREATE OR REPLACE TRIGGER VERIF_SAL1 BEFORE UPDATE OF SALARIUL ON ANGAJATI FOR EACH ROW
WHEN (NEW.SALARIUL<OLD.SALARIUL)
DECLARE
    N NUMBER;
BEGIN
     DBMS_OUTPUT.PUT_LINE('SE MODOFICA SALARIUL PENTRU '||:NEW.ID_ANGAJAT||' DIN '||:OLD.SALARIUL||' IN '||:NEW.SALARIUL);
     SELECT COUNT(*) INTO N FROM COMENZI C --JOIN ANGAJATI A ON C.ID_ANGAJAT=A.ID_ANGAJAT
        --LA UN TRIGGER FOR EACH ROW, NU FOLOSITI INSTRUCTIUNI SQL PE TABELA PE CARE E DECLARAT TRIGGERUL->MUTATING TRIGGER
        --TRIGERUL DEJA PARCRUGER TABELA ANGAJATI NU TRB SA FACEM NOI JOIN CU ANG
    WHERE C.ID_ANGAJAT=:NEW.ID_ANGAJAT;
    IF N>=2 THEN
        :NEW.SALARIUL:=:OLD.SALARIUL;--FUNCTIONEAZA DOAR PENTRU TRIGGER BEFORE
    END IF;
    
END;
/