--Folosind o colectie sa se afiseze denumirea produselor,valoara totala a comenzilor 
--precum si data ultimei 
--comenzi pt produsul respectiv
-- Se vor afisa produsele ordonate desc dupa data ultimei comenzi

SET SERVEROUTPUT ON

DECLARE

    TYPE R_PRO IS RECORD(
    DENUMIRE_PRODUS VARCHAR2(50),
    VAL_TOTALA NUMBER,
    DATA_ULT TIMESTAMP);
    
    TYPE T_PRO IS TABLE OF R_PRO INDEX BY PLS_INTEGER;
    V T_PRO;
    I PLS_INTEGER;
    
BEGIN
    SELECT 
    P.DENUMIRE_PRODUS,
    SUM(R.PRET * R.CANTITATE) AS VAL_TOTALA,
    MAX(C.DATA) AS DATA_ULT
    BULK COLLECT INTO V 
    FROM PRODUSE P
    JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
    JOIN COMENZI C ON R.ID_COMANDA=C.ID_COMANDA
    GROUP BY P.DENUMIRE_PRODUS
    ORDER BY MAX(C.DATA)DESC;
    
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(V(I).denumire_produs || ' || Total=' || V(I).val_totala ||  ' || Ultima comanda=' || V(I).data_ult);
        I:=V.NEXT(I);
    END LOOP;
END;
/


--FOLOSIND UN CURSOR, SA SE AFISEZE DENUMIREA CATEGORIILOR DE PRODUSE SI VALOAREA TOTALA A COMENZILOR
--DIN PERSPECTIVELE CATEGORII. SE VOR AFISA DOAR CATEG CU VAL TOTALA A COMENZILOR >500000
--PT FIECARE CATEOGIRE SE VOR AFISA PRODUSELE DIN ACEA CATEGORIE SI VALOAREA TOALA COMENZILOR


DECLARE
    CURSOR C1 IS SELECT 
        P.CATEGORIE,
        SUM(R.CANTITATE * R.PRET) AS VAL_TOT
        FROM PRODUSE P
        JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
        GROUP BY P.CATEGORIE
        HAVING SUM(R.CANTITATE * R.PRET)>500000;
    
    CURSOR C2(P_CATG VARCHAR2) IS SELECT
        P.DENUMIRE_PRODUS,
        P.CATEGORIE,
        SUM(R.CANTITATE* R.PRET) AS VAL
        FROM PRODUSE P
        JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
        WHERE P.CATEGORIE=P_CATG
        GROUP BY P.DENUMIRE_PRODUS,P.CATEGORIE;
        
    R1 C1%ROWTYPE;
    R2 C2%ROWTYPE;
BEGIN
    IF NOT C1%ISOPEN THEN
        OPEN C1;
    END IF;
    LOOP
        FETCH C1 INTO R1;
        EXIT WHEN C1%NOTFOUND;
        
        DBMS_OUTPUT.PUT_LINE(R1.CATEGORIE);
        
        IF NOT C2%ISOPEN THEN
            OPEN C2(R1.CATEGORIE);
        END IF;
        LOOP
            FETCH C2 INTO R2;
            EXIT WHEN C2%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE(R2.DENUMIRE_PRODUS||' '||R2.VAL);
        END LOOP;
        CLOSE C2;
        
    END LOOP;
    CLOSE C1;
END;
/

--SA SE AFISEZE NUMELE SI PRENUMELE CLIENTULUI CARE A DAT CELE MAI MULTE COMENZI
--SE VOR AFISA COMENZILE PT RESPECTIVUL CLIENT 
-- ID_COMANDA, DATA, VAL TOATALA


DECLARE
    CURSOR C1 IS SELECT
        C.ID_CLIENT,
        C.NUME_CLIENT,
        C.PRENUME_CLIENT,
        COUNT(*) AS NR
        FROM CLIENTI C
        JOIN COMENZI CO ON C.ID_CLIENT=CO.ID_CLIENT
        GROUP BY C.ID_CLIENT,C.NUME_CLIENT,C.PRENUME_CLIENT
        ORDER BY COUNT(*) DESC FETCH FIRST 1 ROW WITH TIES;
    
    CURSOR C2(P_ID_CLIENT NUMBER) IS SELECT
        C.ID_COMANDA,
        C.DATA,
        SUM(R.CANTITATE* R.PRET) AS VAL
        FROM COMENZI C
        JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
        WHERE C.ID_CLIENT=P_ID_CLIENT
        GROUP BY C.ID_COMANDA,C.DATA;
           
BEGIN
    FOR R1 IN C1 LOOP
        DBMS_OUTPUT.PUT_LINE('Client: ' || R1.nume_client || ' ' || R1.prenume_client);
        FOR R2 IN C2(R1.ID_CLIENT) LOOP
            DBMS_OUTPUT.PUT_LINE('Comanda: ' || R2.id_comanda ||' Data: ' || R2.data||' Total: ' || R2.val);
        END LOOP;
    END LOOP;
END;
/


--CURSORUL FOR UPDATE -PUTEM SA ACTUALIZAM PE MASURA CE PARC CURSORUL

--FOLOSIND UN CURSOR SA SE MAREASCA CU 5% PRETUL DE LISTA PT 
--PRODUSELE CARE APAR IN CEL PUTIN 5 COMENZI DISTINCTE


DECLARE
    CURSOR C IS SELECT
    P.ID_PRODUS,
    P.DENUMIRE_PRODUS,
    P.PRET_LISTA
    FROM PRODUSE P
    WHERE P.ID_PROUDS IN(
    SELECT R.ID_PRODUS
    FROM RAND_COMENZI R
    GROUP BY R.ID_PRODUS
    HAVING COUNT(R.ID_PRODUS)>=5) FOR UPDATE WAIT 10;
    
BEGIN
    FOR R IN C LOOP
        UPDATE PRODUSE
        SET PRET_LISTA=PRET_LISTA*1.05
        WHERE CURRENT OF C;
    END LOOP;
END;
/

--FOLOSIND O EXCEPTIE SA SE REZOLVE URMATOAREA CERINTA
--SA SE ADAUGE UN ANGAJAT CU ID-UL CITIT DE LA TASTARU SI SALARIUL CITIT DE LA TASTATURA
--DACA ANGAJATUL EXISTA, I SE VA MODIFCA SALARIUL CU CEL CITIT

--ACCEPT P_ID PROMPT "INTORUDCETI ID";
--ACCEPT SAL PROMPT "INTRODUCETI SAL";
--BEGIN
--    INESERT INTO ANGAJATI( ) VALUES (&P_ID,..)
--END;
--/


--SA SE CONSTRUIASAC UN PACHET CARE CONTINE 
--O FUNCTIE CARE PRIMESTE CA PARAMETRUL ID UL UNUI PRODUS SI UN AN CALENDARISITIC(EX 2019)
--FUNCTIA VA RETURNA VALOAREA TOTALA PENTRU COMENZILE PRODUSULUI RESPECTIV IN ANUL RESPECTOV
-- O PROCEDURA CARE APELEAZA FUNCTIA DINTR UN CURSOR,PROCEDURA VA DECLANSA O EXCEPTIE DEFINITA DE UTILIZATOR
--EXCEPTIA SE VA DECLANSA DACA VAL COMENZILOR PENTRU ACEL AN <500.000
--SA SE APELEZE PROCEDURA DINTR UN BLOC ANONIMC, SA SE TRATEZE EXCEPTIA FARA A FOLOSI OTHERS


CREATE OR REPLACE PACKAGE MK IS
    FUNCTION TOTAL(P_ID_PRODUS NUMBER,P_AN NUMBER)RETURN NUMBER;
    PROCEDURE AFIS(P_AN NUMBER);
    
    NO_VAL EXCEPTION;
    PRAGMA EXCEPTION_INIT(NO_VAL,-20000);
END;
/

CREATE OR REPLACE PACKAGE BODY MK IS

     FUNCTION TOTAL(P_ID_PRODUS NUMBER,P_AN NUMBER)RETURN NUMBER IS
     V_TOT NUMBER;
     BEGIN
        SELECT SUM(R.PRET*R.CANTITATE)INTO V_TOT
        FROM COMENZI C
        JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
        WHERE R.ID_PRODUS=P_ID_PRODUS
        AND EXTRACT(YEAR FROM C.DATA)=P_AN;
        
        RETURN NVL(V_TOT,0);
     END;
     
     PROCEDURE AFIS(P_AN NUMBER) IS
        CURSOR C IS SELECT
            ID_PRODUS,DENUMIRE_PRODUS,TOTAL(ID_PRODUS,P_AN) AS VAL
            FROM PRODUSE
            ORDER BY VAL DESC;
        
        R C%ROWTYPE;
        V_SUMA NUMBER DEFAULT 0;
     BEGIN
        IF NOT C%ISOPEN THEN
            OPEN C;
        END IF;
        LOOP
            FETCH C INTO R;
            EXIT WHEN C%NOTFOUND;
                DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS||' '||R.VAL);
                V_SUMA:=V_SUMA+R.VAL;
        END LOOP;
        CLOSE C;
        
        IF V_SUMA<500000 THEN
            RAISE_APPLICATION_ERROR(-20000,'MAI MICA');
        END IF;
     END;
     
END;
/

DECLARE 
    TOT NUMBER;
BEGIN
    TOT:=MK.TOTAL(100,2020);
    DBMS_OUTPUT.PUT_LINE(TOT);
    
    MK.AFIS(2019);
    EXCEPTION
        WHEN MK.NO_VAL THEN
            DBMS_OUTPUT.PUT_LINE('EROARE'||SQLERRM);
END;
/