--CURSOR IMPLICIT
set SERVEROUTPUT on
DECLARE
  TYPE T_REC IS RECORD(
    NUME_CLIENT CLIENTI.NUME_CLIENT%TYPE,
    PRENUME_CLIENT CLIENTI.PRENUME_CLIENT%TYPE,
    LIMITA_CREDIT CLIENTI.LIMITA_CREDIT%TYPE
  );
  TYPE T_CLIENT IS TABLE OF T_REC INDEX BY PLS_INTEGER;
  V T_CLIENT;  
BEGIN
  SELECT NUME_CLIENT,PRENUME_CLIENT,LIMITA_CREDIT
  BULK COLLECT INTO V FROM CLIENTI 
    WHERE ID_CLIENT IN (SELECT ID_CLIENT FROM COMENZI)
    AND LIMITA_CREDIT>10000
    ORDER BY LIMITA_CREDIT DESC; 
    
   DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);   
   DBMS_OUTPUT.PUT_LINE(v.count);
 
  V.DELETE;  
END;
/


DECLARE 
    V_LIMITA NUMBER;
BEGIN
    SELECT LIMITA_CREDIT INTO V_LIMITA
    FROM CLIENTI
    WHERE ID_CLIENT=170;
DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT); --AFISEAZA DOAR UNUL 
--EL TRECE DE SELECT CU SUCCES DOAR DACA DECLANSEAZA UN SINGUR RAND!!
    
END;
/


--SA SE MAREASAC CU 5% PREETUL PRODUSELOR CARE AU FOST COMANDATE IN COMENZI CU
--VALOARE TOTALA DE MIN 50000
--SA SE AFISEZE CATE PRODUSE AU FOST MODIFICATE

BEGIN
    UPDATE PRODUSE 
    SET PRET_LISTA=PRET_LISTA*1.05
    WHERE ID_PRODUS IN
    (SELECT ID_PRODUS
    FROM RAND_COMENZI
    GROUP BY ID_PRODUS
    HAVING SUM(CANTITATE*PRET)>50000);
    
DBMS_OUTPUT.PUT_LINE('Nr de preturi modificate:' || SQL%ROWCOUNT);

ROLLBACK;
END;
/

DECLARE 
    TYPE T_COL IS TABLE OF VARCHAR2(10) INDEX BY PLS_INTEGER;
    V T_COL;
BEGIN
    DELETE FROM ISTORIC_FUNCTII WHERE ID_ANGAJAT=101
    RETURNING ID_FUNCTIE BULK COLLECT INTO V;
    DBMS_OUTPUT.PUT_LINE('Nr de randuri sterse:' || SQL%ROWCOUNT);
    
    FOR I IN 1..V.COUNT LOOP
        DBMS_OUTPUT.PUT_LINE(V(I));
    END LOOP;
    ROLLBACK;
END;
/


--CURSOR EXPLICIT INTOTDEAUNA CONSTRUITI PE INTEROGARI
-