--Colectii

SET SERVEROUT ON
DECLARE
    TYPE T_COL IS TABLE OF VARCHAR2(100) INDEX BY VARCHAR2(100);
    V T_COL; --DECLAR VARIABILA V DE T_COL
    I VARCHAR2(100);
BEGIN 
    V('ALINA'):='BUCURESTI';
    V('MARIA'):='BUCURESTI';
    V('PETRU'):='CONSTANTA';
    V('ADELA'):='ALBA IULIA';
    DBMS_OUTPUT.PUT_LINE('NR='|| V.COUNT);
    DBMS_OUTPUT.PUT_LINE('PRIMUL='||V.FIRST); --SE IA IN ORD ALFABETICA
    DBMS_OUTPUT.PUT_LINE('ULTIMUL='||V.LAST||' '||'DOMICILIU='||V(V.LAST));
    
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(I||'->'||V(I));
        I:=V.NEXT(I);
    END LOOP;
END;
/

--COLLECTII PT A AFISA REZULTATUL UNEI INTEROGARI

--FOLOSIND UN BLOC PL/SQL SA SE AFISEZE NUMELE CLIENTILOR CARE AU DAT CEL PUTIN O COMANDA
--CLIENTII VOR FI AFISATI DESC DUPA LIMITA DE CREDIT

DECLARE 
    TYPE T_CL IS TABLE OF CLIENTI%ROWTYPE INDEX BY PLS_INTEGER;
    V T_CL;
    I PLS_INTEGER;
BEGIN
    SELECT *
    BULK COLLECT INTO V
    FROM CLIENTI
    WHERE ID_CLIENT IN(SELECT ID_CLIENT FROM COMENZI)
    ORDER BY LIMITA_CREDIT DESC;
    
    DBMS_OUTPUT.PUT_LINE('NR='||V.COUNT);
    DBMS_OUTPUT.PUT_LINE('PRIMUL='||v.FIRST);
    DBMS_OUTPUT.PUT_LINE('ULTIMUL='||v.LAST);
    
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(V(i).NUME_CLIENT);
        I:=V.NEXT(I);
    END LOOP;
END;
/

DECLARE 
    TYPE R_CL IS RECORD(
    NUME_CLIENT VARCHAR2(30),
    PRENUME_CLIENT VARCHAR2(30),
    LIMITA_CREDIT NUMBER(5));
    
    TYPE T_CL IS TABLE OF R_CL INDEX BY PLS_INTEGER;
    V T_CL; --VARIABILA DE TIP T_CL
    I PLS_INTEGER;
BEGIN
    SELECT NUME_CLIENT,PRENUME_CLIENT,LIMITA_CREDIT
    BULK COLLECT INTO V
    FROM CLIENTI
    WHERE ID_CLIENT IN(SELECT ID_CLIENT FROM COMENZI)
    ORDER BY LIMITA_CREDIT DESC;
    
    DBMS_OUTPUT.PUT_LINE('NR='||V.COUNT);
    DBMS_OUTPUT.PUT_LINE('PRIMUL='||v.FIRST);
    DBMS_OUTPUT.PUT_LINE('ULTIMUL='||v.LAST);
    
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(V(i).NUME_CLIENT||' '||V(I).PRENUME_CLIENT);
        I:=V.NEXT(I);
    END LOOP;
    V.DELETE;
END;
/