Tipuri de DATE
-SCALARE:VARCHAR2, NUMBER, DATE, TIMESTAMP, PLS_INTEGER ETC
-COMPUSE
    -RECORD:TYPE ... IS RECORD, %ROWTYPE
    -COLECTII
        -INDEX BY TABLE
        -NESTED TABLE
        -VARRAY


SET SERVEROUTPUT ON
DECLARE
    TYPE T_ANG IS TABLE OF VARCHAR2(100) INDEX BY VARCHAR2(100); --INDEX BY -> NE SPUNE TIPUL INDEXULUI
    V T_ANG; 
    --am fct o colectie de siruri de caractere 
BEGIN
    V('ION'):=5000;
    V('MARIUS'):=5500;
    V('MARIA'):=5300;
    V('ANA'):=2700;
END;
/

DECLARE
    TYPE T_ANG IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER; --cheia colectie este o valoare numerica asta face integer
    V T_ANG; 
    --am fct o colectie de siruri de caractere 
BEGIN
    V(1):='ION';
    V(2):='MARIUS';
    V(3):='MARIA';
    V(4):='ANA';
    DBMS_OUTPUT.PUT_LINE(V(2));
    DBMS_OUTPUT.PUT_LINE('NR='||V.COUNT);
    DBMS_OUTPUT.PUT_LINE('PRIMUL='||v.FIRST); --af indexul primul element ->1
    DBMS_OUTPUT.PUT_LINE('ULTIMUL='||v.LAST); --af indexul ultimul element ->4
    V.DELETE(3,4);
    DBMS_OUTPUT.PUT_LINE('NR='||V.COUNT);
    
END;
/


DECLARE
    TYPE T_ANG IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER; 
    V T_ANG; 
BEGIN
    V(1):='ION';
    V(2):='MARIUS';
    V(3):='MARIA';
    V(40):='ANA';
    
    FOR I in V.FIRST .. V.LAST LOOP
        CONTINUE WHEN NOT V.EXISTS(I); --daca nu exista trecre la urmatorul
        DBMS_OUTPUT.PUT_LINE(I||'->'||V(I));
    END LOOP;
    
END;
/

DECLARE
    TYPE T_ANG IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER;
    V T_ANG; 
    
BEGIN
    V(1):='ION';
    V(2):='MARIUS';
    V(3):='MARIA';
    V(4):='ANA';
    
    FOR I in 1 .. V.COUNT LOOP
        DBMS_OUTPUT.PUT_LINE(I||'->'||V(i));
    END LOOP;
    
END;
/




DECLARE
    TYPE T_ANG IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER;
    V T_ANG; 
    I PLS_INTEGER;
    
BEGIN
    V(-1):='ION';
    V(2):='MARIUS';
    V(3):='MARIA';
    V(40):='ANA';
    
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(I||'->'||V(i));
        I:=V.NEXT(I);
    END LOOP;
END;
/


DECLARE
    TYPE T_ANG IS TABLE OF VARCHAR2(100) INDEX BY VARCHAR2(100);
    V T_ANG; 
    I VARCHAR2(100);
    
BEGIN
    V('ION'):=5000;
    V('MARIUS'):=5500;
    V('MARIA'):=5300;
    V('ANA'):=2700;
    
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(I||'->'||V(i));
        I:=V.NEXT(I);
    END LOOP;
    V.DELETE; --sterge toate elementele din colectie
END;
/



--FOLOSIND O COLECTIE SA SE AFISEZE NUMELE ANG DIN DEP SA_REPT CU SALARILE INTRE 5000 SI 9000
--ANG VOR FI AFISATI IN ORDINEA DESC A VAL

SELECT NUME FROM ANGAJATI WHERE ID_FUNCTIE='SA_REP' AND SALARIUL BETWEEN 5000 AND 9000 ORDER BY SALARIUL;
DECLARE
    TYPE T_ANG IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER;
    V T_ANG;
BEGIN
    SELECT NUME
    BULK COLLECT INTO V -- PUNEM BULK COLLECT INTO  fata de sus si nu lasa  in PL/SQL INDEXUL INCEPE DE LA 1
    FROM ANGAJATI
    WHERE ID_FUNCTIE = 'SA_REP'
    AND SALARIUL BETWEEN 5000 AND 9000
    ORDER BY SALARIUL DESC;

    DBMS_OUTPUT.PUT_LINE('NR='||V.COUNT);
    DBMS_OUTPUT.PUT_LINE('PRIMUL='||v.FIRST);
    DBMS_OUTPUT.PUT_LINE('ULTIMUL='||v.LAST);
   
    FOR I IN 1 .. V.COUNT LOOP --mult mai bine asa pt ca BULK COLLECT PUNE INDEXI CONSECUTIVI!!! ADUCE DATELE DIN COLECTIE NU DIN TABELA
        DBMS_OUTPUT.PUT_LINE(I||'->'||V(i));
    END LOOP;
    
END;
/

DECLARE
    TYPE T_ANG IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER;
    V T_ANG;
    I PLS_INTEGER;
BEGIN
    SELECT NUME||' '||PRENUME||' '||SALARIUL 
    BULK COLLECT INTO V -- PUNEM BULK COLLECT INTO  fata de sus si nu lasa  in PL/SQL INDEXUL INCEPE DE LA 1
    FROM ANGAJATI
    WHERE ID_FUNCTIE = 'SA_REP'
    AND SALARIUL BETWEEN 5000 AND 9000
    ORDER BY SALARIUL DESC;

    DBMS_OUTPUT.PUT_LINE('NR='||V.COUNT);
    DBMS_OUTPUT.PUT_LINE('PRIMUL='||v.FIRST);
    DBMS_OUTPUT.PUT_LINE('ULTIMUL='||v.LAST);
   
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(I||'->'||V(i));
        I:=V.NEXT(I);
    END LOOP;
END;
/

DECLARE
    TYPE T_ANG IS TABLE OF ANGAJATI%ROWTYPE INDEX BY PLS_INTEGER;
    V T_ANG;
    I PLS_INTEGER;
    
BEGIN
    SELECT *
    BULK COLLECT INTO V -- 
    FROM ANGAJATI
    WHERE ID_FUNCTIE = 'SA_REP'
    AND SALARIUL BETWEEN 5000 AND 9000
    ORDER BY SALARIUL DESC;
   
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(V(I).NUME || ' ' ||V(I).PRENUME||' ' ||'Salariul='||V(I).SALARIUL);
        I:=V.NEXT(I);
    END LOOP;
END;
/

--MAI FOLOSITA VARIANTA CU RECORD
DECLARE
    TYPE R_ANG IS RECORD(
    NUME VARCHAR2(30),
    PRENUME VARCHAR2(30),
    SALARIUL NUMBER);
    
    TYPE T_ANG IS TABLE OF R_ANG INDEX BY PLS_INTEGER;
    V T_ANG;
    I PLS_INTEGER;
    
BEGIN
    SELECT NUME,PRENUME,SALARIUL    
    BULK COLLECT INTO V -- 
    FROM ANGAJATI
    WHERE ID_FUNCTIE = 'SA_REP'
    AND SALARIUL BETWEEN 5000 AND 9000
    ORDER BY SALARIUL DESC;
   
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(V(I).NUME || ' ' ||V(I).PRENUME||' ' ||'Salariul='||V(I).SALARIUL);
        I:=V.NEXT(I);
    END LOOP;
END;
/