/*Declansatorii -Triggeri

la nivel de instructiune(se executa o signura data/instructiune indiferent cate randuri sunt afectate)
la nivel de rand(o data/pentru ficare rand afectat)

BEFORE          INSERT
AFTER           UPDATE      (TABLE)
                DELETE
                
INSTEAD OF      INSERT/UPDATE/DELETE (VIEW)
*/

--SA SE CONSTRUIASCA UN TRIGGER CARE NU PERMITE 
--ADAUGAREA DE COMENZI DUPA ORA 16:00
--MODIFICAREA DE COMENZI DUPA ORA 16:10
--STERGEREA DE COMENZI DUPA ORA 16:20

SET SERVEROUTPUT ON

--COMMIT SI ROLLBACK NU SE FOLOESC IN INTERIORUL UNUI TRIGGER
CREATE OR REPLACE TRIGGER VERIF_ORA BEFORE INSERT OR UPDATE OR DELETE ON COMENZI
BEGIN
    IF INSERTING AND TO_CHAR(SYSDATE,'HH24:MI')>='16:00' THEN
        RAISE_APPLICATION_ERROR(-20000,'NU SE POT ADAUGA COMENZI DUPA PRA 16');
         --DBMS_OUTPUT.PUT_LINE('S-A DECLANSAT TRIGGERUL INAINTEA UNEI OPERATII INSERT');
    ELSIF UPDATING AND TO_CHAR(SYSDATE,'HH24:MI')>='16:1O' THEN
          RAISE_APPLICATION_ERROR(-20000,'NU SE POT MODIFICA COMENZI DUPA PRA 16:10');
        --DBMS_OUTPUT.PUT_LINE('S-A DECLANSAT TRIGGERUL INAINTEA UNEI OPERATII UPDATE');
    ELSIF DELETING AND TO_CHAR(SYSDATE,'HH24:MI')>='16:20'THEN
        RAISE_APPLICATION_ERROR(-20000,'NU SE POT STERGE COMENZI DUPA PRA 16:20');
        --DBMS_OUTPUT.PUT_LINE('S-A DECLANSAT TRIGGERUL INAINTEA UNEI OPERATII DELETE');
    END IF;
END;
/

SELECT * FROM COMENZI;

UPDATE COMENZI 
SET STARE_COMANDA=STARE_COMANDA+1 
WHERE ID_COMANDA>2430;

DELETE FROM COMENZI WHERE ID_COMANDA>2430;

--SA SE CONSTRUIASCA UN TRIGGER CARE SA PERMITA MAXIM 5 RANDURI IN TABELA REGIUNI

CREATE OR REPLACE TRIGGER VERIF_REG BEFORE INSERT ON REGIUNI
DECLARE
    NR NUMBER;
BEGIN
    SELECT COUNT(*) INTO NR FROM REGIUNI;
    IF NR>=5 THEN
        RAISE_APPLICATION_ERROR(-20000,'MAXIM 5 RANDURI IN TABELA');
    END IF;
END;
/

SELECT * FROM REGIUNI;
--la triggeri AFTER mai intai se declanseaza restrictiile de integritate,daca este cazul!!!
INSERT INTO REGIUNI VALUES (5, 'Asia');

--SA SE CONSTRUIASACA UN TRIGGER CARE NU PERMITE MICSORAREA SALARIILOR ANGAJATI AU INTERMEDIAT CEL PUTIN 2 COMENZI

--FOR EACH ROW
--        :NEW    :OLD
--INSERT  X       NULL
--UPDATE  X       X
--DELETE  NULL    X

CREATE OR REPLACE TRIGGER VERF_SAL BEFORE UPDATE ON ANGAJATI FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('SE MODOFICA SALARIUL PENTRU '||:NEW.ID_ANGAJAT||' DIN '||:OLD.SALARIUL||' IN '||:NEW.SALARIUL);
END;
/

UPDATE ANGAJATI
SET SALARIUL=SALARIUL*1.01
WHERE ID_ANGAJAT>180;


--SA SE CONSTRUIASACA UN TRIGGER CARE NU PERMITE MICSORAREA SALARIILOR ANGAJATI AU INTERMEDIAT CEL PUTIN 2 COMENZI
CREATE OR REPLACE TRIGGER VERF_SAL BEFORE UPDATE OF SALARIUL ON ANGAJATI FOR EACH ROW
DECLARE
    N NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('SE MODOFICA SALARIUL PENTRU '||:NEW.ID_ANGAJAT||' DIN '||:OLD.SALARIUL||' IN '||:NEW.SALARIUL);
    IF :NEW.SALARIUL<:OLD.SALARIUL THEN
        SELECT COUNT(*) INTO N FROM COMENZI C --JOIN ANGAJATI A ON C.ID_ANGAJAT=A.ID_ANGAJAT
        --LA UN TRIGGER FOR EACH ROW, NU FOLOSITI INSTRUCTIUNI SQL PE TABELA PE CARE E DECLARAT TRIGGERUL->MUTATING TRIGGER
        --TRIGERUL DEJA PARCRUGER TABELA ANGAJATI NU TRB SA FACEM NOI JOIN CU ANG
        WHERE C.ID_ANGAJAT=:NEW.ID_ANGAJAT;
        IF N>=2 THEN
            RAISE_APPLICATION_ERROR(-20001,'NU SE POATE MODIFICA SALARIUL PT ACEST ANGAJAT'||:NEW.ID_ANGAJAT);
        END IF;
    END IF;
END;
/

--DACA SE VA DECLANSA EXCEPRIA , NICIUN RAND NU VA FI MODIFICAT
select * from comenzi order by id_angajat;

UPDATE ANGAJATI
SET SALARIUL=SALARIUL-5 
WHERE ID_ANGAJAT>140;

UPDATE ANGAJATI 
SET COMISION=COMISION*1.01 WHERE ID_ANGAJAT>180;


CREATE OR REPLACE TRIGGER VERF_SAL1 BEFORE UPDATE OF SALARIUL ON ANGAJATI FOR EACH ROW
DECLARE
    N NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('SE MODOFICA SALARIUL PENTRU '||:NEW.ID_ANGAJAT||' DIN '||:OLD.SALARIUL||' IN '||:NEW.SALARIUL);
    IF :NEW.SALARIUL<:OLD.SALARIUL THEN
        SELECT COUNT(*) INTO N FROM COMENZI C --JOIN ANGAJATI A ON C.ID_ANGAJAT=A.ID_ANGAJAT
        --LA UN TRIGGER FOR EACH ROW, NU FOLOSITI INSTRUCTIUNI SQL PE TABELA PE CARE E DECLARAT TRIGGERUL->MUTATING TRIGGER
        --TRIGERUL DEJA PARCRUGER TABELA ANGAJATI NU TRB SA FACEM NOI JOIN CU ANG
        WHERE C.ID_ANGAJAT=:NEW.ID_ANGAJAT;
        IF N>=2 THEN
            :NEW.SALARIUL:=:OLD.SALARIUL;--FUNCTIONEAZA DOAR PENTRU TRIGGER BEFORE
        END IF;
    END IF;
END;
/

UPDATE ANGAJATI
SET SALARIUL=SALARIUL-5 
WHERE ID_ANGAJAT>140;

CREATE OR REPLACE TRIGGER VERF_SAL1 BEFORE UPDATE OF SALARIUL ON ANGAJATI FOR EACH ROW
WHEN (NEW.SALARIUL<OLD.SALARIUL) --CAND FOLOSIM NEW SI OLD IN ANTET,NU SE FOLOSESTE :
DECLARE
    N NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('SE MODOFICA SALARIUL PENTRU '||:NEW.ID_ANGAJAT||' DIN '||:OLD.SALARIUL||' IN '||:NEW.SALARIUL);
    IF :NEW.SALARIUL<:OLD.SALARIUL THEN
        SELECT COUNT(*) INTO N FROM COMENZI C --JOIN ANGAJATI A ON C.ID_ANGAJAT=A.ID_ANGAJAT
        --LA UN TRIGGER FOR EACH ROW, NU FOLOSITI INSTRUCTIUNI SQL PE TABELA PE CARE E DECLARAT TRIGGERUL->MUTATING TRIGGER
        --TRIGERUL DEJA PARCRUGER TABELA ANGAJATI NU TRB SA FACEM NOI JOIN CU ANG
        WHERE C.ID_ANGAJAT=:NEW.ID_ANGAJAT;
        IF N>=2 THEN
            :NEW.SALARIUL:=:OLD.SALARIUL;--FUNCTIONEAZA DOAR PENTRU TRIGGER BEFORE
        END IF;
    END IF;
END;
/



