--CURSORUL EXPLICIT

--FOLOSIND UN CURSOR SA SE AFISEZE NUMELE SI PRENUMELE CLIENT 
--CARE AU DAT CEL PIUTIN 2 COMENZI
--CLIENTII SE VOR AFISA IN ORDINEA DESC A LIMIT CREDIT

--NUME_CURORS%ISOPEN
--NUME_CURSOR%FOUND
--NUME_CURSOR%NOTFOUND
--NUME_CURSOR%ROWCOUNT

SET SERVEROUTPUT ON

SELECT NUME_CLIENT,PRENUME_CLIENT
FROM CLIENTI
WHERE ID_CLIENT IN ( SELECT ID_CLIENT 
FROM COMENZI 
GROUP BY ID_CLIENT
HAVING COUNT(*)>=2);

--PARCURGERE CLASICA CU OPEN-LOOP-FETCH-CLOSE

DECLARE 
    CURSOR C IS SELECT NUME_CLIENT,PRENUME_CLIENT,LIMITA_CREDIT
                    FROM CLIENTI
                    WHERE ID_CLIENT IN ( SELECT ID_CLIENT 
                    FROM COMENZI 
                    GROUP BY ID_CLIENT
                    HAVING COUNT(*)>=2)
                    ORDER BY LIMITA_CREDIT DESC;
    V_NUME_CLIENT CLIENTI.NUME_CLIENT%TYPE;
    V_PRENUME_CLIENT CLIENTI.PRENUME_CLIENT%TYPE;
    V_LIMITA_CREDIT CLIENTI.LIMITA_CREDIT%TYPE;
BEGIN
    IF NOT C%ISOPEN THEN
        OPEN C;
    END IF;
    
    LOOP
    
    FETCH C INTO  V_NUME_CLIENT,V_PRENUME_CLIENT,V_LIMITA_CREDIT; --FETCH IA PRIMUL RAND DIN SELECT SI IL PUNE IN VARIABILE
    EXIT WHEN C%NOTFOUND; --iesim din loop cand fetch nu mai gaseste nimic
    DBMS_OUTPUT.PUT_LINE(C%ROWCOUNT||' '||V_NUME_CLIENT||' '||V_PRENUME_CLIENT||' '||V_LIMITA_CREDIT);
    END LOOP;
    
    CLOSE C;

END;
/

--varianta cu R -ROWTYPE

DECLARE 
    CURSOR C IS SELECT NUME_CLIENT,PRENUME_CLIENT,LIMITA_CREDIT
                    FROM CLIENTI
                    WHERE ID_CLIENT IN ( SELECT ID_CLIENT 
                    FROM COMENZI 
                    GROUP BY ID_CLIENT
                    HAVING COUNT(*)>=2)
                    ORDER BY LIMITA_CREDIT DESC;
   R C%ROWTYPE; --CEL MAI FOLOSIT ASA!!!
BEGIN
    IF NOT C%ISOPEN THEN
        OPEN C;
    END IF;
    
    LOOP
    
    FETCH C INTO R;
    EXIT WHEN C%NOTFOUND; 
    DBMS_OUTPUT.PUT_LINE(C%ROWCOUNT||' '||R.NUME_CLIENT||' '||R.PRENUME_CLIENT||' '||R.LIMITA_CREDIT);
    END LOOP;
    
    CLOSE C;

END;
/

--sa se afiseze primii 5
DECLARE 
    CURSOR C IS SELECT NUME_CLIENT,PRENUME_CLIENT,LIMITA_CREDIT
                    FROM CLIENTI
                    WHERE ID_CLIENT IN ( SELECT ID_CLIENT 
                    FROM COMENZI 
                    GROUP BY ID_CLIENT
                    HAVING COUNT(*)>=2)
                    ORDER BY LIMITA_CREDIT DESC;
                    --FETCH FIRST 5 ROWS ONLY; -IA DOAR PRIMII 5 DIN SELECT
                    --FETCH FIRST 5 ROWS WITH TIES --DACA MAI AFISEAZA UNA DUPA 5
   R C%ROWTYPE;
BEGIN
    IF NOT C%ISOPEN THEN
        OPEN C;
    END IF;
    
    LOOP
    
    FETCH C INTO R;
    EXIT WHEN C%NOTFOUND OR C%ROWCOUNT>5;
    DBMS_OUTPUT.PUT_LINE(C%ROWCOUNT||' '||R.NUME_CLIENT||' '||R.PRENUME_CLIENT||' '||R.LIMITA_CREDIT);
    END LOOP;
    
    CLOSE C;

END;
/

                
--FOLOSIND UN CURSOR SA SE AFISEZE DENUMIREA DEPARTAMENTELOR UNDE TOTI ANGAJATII AU SALARILE <=10000
DECLARE 
    CURSOR C IS SELECT DENUMIRE_DEPARTAMENT
                FROM DEPARTAMENTE
                WHERE ID_DEPARTAMENT IN(
                SELECT ID_DEPARTAMENT 
                FROM ANGAJATI
                GROUP BY ID_DEPARTAMENT
                HAVING MAX(SALARIUL)<=10000);
    R C%ROWTYPE;
BEGIN 
IF NOT C%ISOPEN THEN
        OPEN C;
    END IF;
    
    LOOP
    
    FETCH C INTO R;
    EXIT WHEN C%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(C%ROWCOUNT||' '||R.DENUMIRE_DEPARTAMENT);
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('Nr departamente:'||C%ROWCOUNT);
    
    CLOSE C;
END;
/

--echivalent dar cu  FOR
DECLARE 
    CURSOR C IS SELECT DENUMIRE_DEPARTAMENT
                FROM DEPARTAMENTE
                WHERE ID_DEPARTAMENT IN(
                SELECT ID_DEPARTAMENT 
                FROM ANGAJATI
                GROUP BY ID_DEPARTAMENT
                HAVING MAX(SALARIUL)<=10000);
   
BEGIN 
    --INAINTE DE PARCURGEREA CU FOR CUROSUL NU TREBUIE DESCHIS / INCHIS DUPA
    --FOR-UL DESCHIDE SI INCHIDE AUTOMAT CURSORUL SI L DECLARA PE R CA C%ROWTYPE
    FOR R IN C LOOP 
    DBMS_OUTPUT.PUT_LINE(C%ROWCOUNT||' '||R.DENUMIRE_DEPARTAMENT);
    END LOOP;
    
END;
/

--CURSOR IN LINE

BEGIN 
    FOR R IN (SELECT DENUMIRE_DEPARTAMENT
                FROM DEPARTAMENTE 
                WHERE ID_DEPARTAMENT IN(
                SELECT ID_DEPARTAMENT 
                FROM ANGAJATI
                GROUP BY ID_DEPARTAMENT
                HAVING MAX(SALARIUL)<=10000))
                LOOP
                DBMS_OUTPUT.PUT_LINE(R.DENUMIRE_DEPARTAMENT);
                END LOOP;
END;
/


--FOLOSIND UN CURSOR, SA SE AFISEZE DENUMIREA CATEGORIILOR DE PRODUSE SI VALOAREA TOTALA A COMENZILOR
--DIN PERSPECTIVELE CATEGORII. SE VOR AFISA DOAR CATEG CU VAL TOTALA A COMENZILOR >500000


DECLARE
    CURSOR C IS SELECT 
    P.CATEGORIE,
    SUM(R.PRET *R.CANTITATE) AS VAL_T
    FROM PRODUSE P
    JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
    GROUP BY P.CATEGORIE
    HAVING SUM(R.PRET *R.CANTITATE)>50000;
BEGIN
    FOR R IN C LOOP 
    DBMS_OUTPUT.PUT_LINE(R.CATEGORIE);
    END LOOP;
END;
/

