set serveroutput on
DECLARE
V_NUME ANGAJATI.NUME%TYPE;
--V_PRENUME CHAR(3);
V_PRENUME ANGAJATI.PRENUME%TYPE;
C_TAXE CONSTANT NUMBER:=0.19; -- o constanta trebuie oblig initializata
BEGIN 

SELECT NUME,PRENUME INTO V_NUME,V_PRENUME 
FROM ANGAJATI 
WHERE id_angajat>=101;
DBMS_OUTPUT.PUT_LINE('ABC');
DBMS_OUTPUT.PUT_LINE('ANGAJAT' || V_NUME || ' '|| V_PRENUME);
EXCEPTION 
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('A aparut o exceptie-' ||SQLERRM); 
END;
/

DECLARE 
    V_ANG ANGAJATI%ROWTYPE; -- variabila de tip record care are aceleasi campuri ca si coloanele tabelei angajati
BEGIN 
    SELECT * INTO V_ANG FROM ANGAJATI WHERE Id_ANGAJAT=101;
    DBMS_OUTPUT.PUT_LINE(V_ANG.ID_ANGAJAT || ' ' || V_ANG.NUME || V_ANG.PRENUME || ' ' || V_ANG.SALARIUL);
END;
/

/*
STRUCTURILE FUNDAMENTELE DE PROGRAM
-SECVENTIALA  (nu are if)
-ALTERNATIVA (cand folosim if - elsif - else end  / case-end case)
-REPETITA 
    -CU NR CUNOSCUT DE PASI: FOR
    -CU NR NECUNOSCUT DE PASI:WHILE SI LOOP

*/


--INITALIZARE VARIABILA := SAU DEFAULT

DECLARE
    V_NOTA NUMBER(2) DEFAULT 10;
BEGIN 
    IF V_NOTA IS NULL THEN 
        DBMS_OUTPUT.PUT_LINE('NOTA LIPSA '); 
    ELSIF V_NOTA=10 THEN
        DBMS_OUTPUT.PUT_LINE('PREMIANT ');
    ELSIF V_NOTA<1 OR V_NOTA>10 THEN
        DBMS_OUTPUT.PUT_LINE('NOTA ERONATA '); 
    ELSIF V_NOTA <5 THEN 
        DBMS_OUTPUT.PUT_LINE('PICAT'); 
        DBMS_OUTPUT.PUT_LINE('CHIAR A PICAT');
     ELSE
        DBMS_OUTPUT.PUT_LINE('PROMOVAT');
    END IF;
END;
/

DECLARE
    V_NOTA NUMBER(2) DEFAULT 10;
BEGIN 
    V_NOTA:=9;
    CASE
    WHEN V_NOTA IS NULL THEN 
        DBMS_OUTPUT.PUT_LINE('NOTA LIPSA '); 
    WHEN V_NOTA=10 THEN
        DBMS_OUTPUT.PUT_LINE('PREMIANT ');
    WHEN V_NOTA<1 OR V_NOTA>10 THEN
        DBMS_OUTPUT.PUT_LINE('NOTA ERONATA '); 
    WHEN V_NOTA <5 THEN 
        DBMS_OUTPUT.PUT_LINE('PICAT'); 
        DBMS_OUTPUT.PUT_LINE('CHIAR A PICAT');
    ELSE --PRACTIC O EXCEPTIE NEAPART O CONDITIE TRUE
        DBMS_OUTPUT.PUT_LINE('PROMOVAT');
    END CASE;
    DBMS_OUTPUT.PUT_LINE('B');
    EXCEPTION WHEN CASE_NOT_FOUND THEN 
            DBMS_OUTPUT.PUT_LINE('PROMOVAT');
END;
/

DECLARE 
    I NUMBER:=5;
BEGIN 
    DBMS_OUTPUT.PUT_LINE('I=' || I);
    I:=I+2;
    FOR I IN /*REVERSE */ 1..10 LOOP --indexul I se declareaza automat, aici este de tip number --REVERSE PRACTIC i--
         DBMS_OUTPUT.PUT_LINE('I=' || I);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('I=' || I);
    EXCEPTION WHEN OTHERS THEN NULL;
END;
/


DECLARE 
    INC NUMBER:=25;
    SF NUMBER:=35;
BEGIN 
    FOR I IN  INC..SF LOOP 
        CONTINUE WHEN I MOD 2 = 1;
         DBMS_OUTPUT.PUT_LINE('I=' || I);
    END LOOP;
    --DBMS_OUTPUT.PUT_LINE('I=' || I);
   -- EXCEPTION WHEN OTHERS THEN NULL;
END;
/

DECLARE
    I PLS_INTEGER:=25;
BEGIN
    WHILE(I<=35) LOOP
         DBMS_OUTPUT.PUT_LINE('I=' || I);
         I:=I+2;
    END LOOP;
END;
/



DECLARE
    I PLS_INTEGER:=25;
BEGIN
   LOOP
         DBMS_OUTPUT.PUT_LINE('I=' || I);
         I:=I+2;
         EXIT WHEN I>35;
    END LOOP;
END;
/