--FOLOSIND UN CURSOR, SA SE AFISEZE DENUMIREA CATEGORIILOR DE PRODUSE SI VALOAREA TOTALA A COMENZILOR
--DIN PERSPECTIVELE CATEGORII. SE VOR AFISA DOAR CATEG CU VAL TOTALA A COMENZILOR >500000


DECLARE
    CURSOR C IS SELECT 
    P.CATEGORIE,
    SUM(R.PRET *R.CANTITATE) AS VAL_T
    FROM PRODUSE P
    JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
    GROUP BY P.CATEGORIE
    HAVING SUM(R.PRET *R.CANTITATE)>50000;
    
    
BEGIN
    FOR R IN C LOOP 
        DBMS_OUTPUT.PUT_LINE(R.CATEGORIE);
    
    
    END LOOP;
END;
/

SET SERVEROUTPUT ON

--FOLOSIND UN CURSOR, SA SE AFISEZE DENUMIREA CATEGORIILOR DE PRODUSE SI VALOAREA TOTALA A COMENZILOR
--DIN PERSPECTIVELE CATEGORII. SE VOR AFISA DOAR CATEG CU VAL TOTALA A COMENZILOR >500000
--PT FIECARE CATEOGIRE SE VOR AFISA PRODUSELE DIN ACEA CATEGORIE SI VALOAREA TOALA COMENZILOR


    
    
DECLARE
    CURSOR C IS SELECT 
    P.CATEGORIE,
    SUM(R.PRET *R.CANTITATE) AS VAL_T
    FROM PRODUSE P
    JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
    GROUP BY P.CATEGORIE
    HAVING SUM(R.PRET *R.CANTITATE)>50000;
    
    CURSOR D(P_CATEG VARCHAR2) IS SELECT 
    P.DENUMIRE_PRODUS,
    categorie,
    SUM(R.PRET *R.CANTITATE) AS VAL_T
    FROM PRODUSE P, RAND_COMENZI R 
    WHERE P.ID_PRODUS=R.ID_PRODUS
    AND P.CATEGORIE=P_CATEG
    GROUP BY P.denumire_produs,categorie;
  
BEGIN
    FOR R IN C LOOP 
        DBMS_OUTPUT.PUT_LINE(R.CATEGORIE);
        FOR S IN D(R.CATEGORIE) LOOP
        --IF S.CATEGORIE=R.CATEGORIE THEN
            DBMS_OUTPUT.PUT_LINE(S.DENUMIRE_PRODUS||':'||S.VAL_T);
        END LOOP;
    END LOOP;
END;
/


--SA SE AFISEZE NUMELE SI PRENUMELE CLIENTULUI CARE A DAT CELE MAI MULTE COMENZI
--SE VOR AFISA COMENZILE PT RESPECTIVUL CLIENT 
-- ID_COMANDA, DATA, VAL TOATALA

DECLARE
    CURSOR C1 IS
        SELECT c.id_client, c.nume_client, c.prenume_client, COUNT(*) NR_COM
        FROM clienti c
        JOIN comenzi co ON c.id_client = co.id_client
        GROUP BY c.id_client, c.nume_client, c.prenume_client
        ORDER BY COUNT(*) DESC FETCH FIRST 1 ROW WITH TIES;

    CURSOR C2(P_ID NUMBER) IS
        SELECT c.id_comanda,
               c.data,
               SUM(r.pret * r.cantitate) AS val_tot
        FROM comenzi c
        JOIN rand_comenzi r ON c.id_comanda = r.id_comanda
        WHERE c.id_client = P_ID
        GROUP BY c.id_comanda, c.data;

BEGIN
    FOR R1 IN C1 LOOP
        DBMS_OUTPUT.PUT_LINE('Client: ' || R1.nume_client || ' ' || R1.prenume_client);
        FOR R2 IN C2(R1.id_client) LOOP
            DBMS_OUTPUT.PUT_LINE('Comanda: ' || R2.id_comanda ||' Data: ' || R2.data||' Total: ' || R2.val_tot);
        END LOOP;
    END LOOP;
END;
/

--CURSORUL FOR UPDATE -PUTEM SA ACTUALIZAM PE MASURA CE PARC CURSORUL

--FOLOSIND UN CURSOR SA SE MAREASCA CU 5% PRETUL DE LISTA PT PRODUSELE CARE APAR IN CEL PUTIN 5 COMENZI DISTINCTE

SELECT 
P.ID_PRODUS,
DENUMIRE_PRODUS,
PRET_LISTA
FROM PRODUSE P
JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
GROUP BY P.ID_PRODUS,DENUMIRE_PRODUS,PRET_LISTA
HAVING COUNT(*)>=5;

DECLARE
    CURSOR C IS SELECT 
        P.ID_PRODUS,
        DENUMIRE_PRODUS,
        PRET_LISTA
        FROM PRODUSE P
        WHERE P.ID_PRODUS IN (SELECT R.ID_PRODUS 
                             FROM RAND_COMENZI R
                             GROUP BY R.ID_PRODUS
                             HAVING COUNT(R.ID_PRODUS)>=5) FOR UPDATE WAIT 10;
BEGIN
    FOR R IN C LOOP
        UPDATE PRODUSE
        SET PRET_LISTA=PRET_LISTA*1.05
        WHERE CURRENT OF C;
        DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS||' '||R.DENUMIRE_PRODUS||' '||R.PRET_LISTA); 
        --AFISEAZA DATELE DE LA DESCHIDEREA CURSORULUI NU CELE ACTUALIZATE
    END LOOP;
END;
/

