ERORI

- COMPILATION TIME ERRORS

- RUN TIME ERRORS
    EXCEPTII
      - IMPLICITE
          - PREDEFINITE: NO_DATA_FOUND, TOO_MANY_ROWS, DUP_VAL_ON_INDEX, INVALID_CURSOR...
          - NON-PREDEFINITE: AU COD DE EXCEPTIE DAR NU AU SI HANDLER-UL EXCEPTIEI
      - EXPLICITE
          - DEFINITE DE UTILIZATOR\
DECLARE
  I DATE;
BEGIN
I:=100;
EXCEPTION WHEN OTHERS THEN
  NULL;
END;
/
SET SERVEROUTPUT ON
DECLARE
  I NUMBER(3);
  CURSOR C IS SELECT * FROM ANGAJATI;
  R C%ROWTYPE;
BEGIN
I:=100;
I:=I/0; 
 EXCEPTION 
   WHEN ZERO_DIVIDE THEN
    BEGIN
    DBMS_OUTPUT.PUT_LINE('NU PUTEM IMPARTI LA ZERO');
    FETCH C INTO R;  
      EXCEPTION WHEN OTHERS THEN 
       DBMS_OUTPUT.PUT_LINE('EXCEPTIE IN EXCEPTIE');
    END;
   WHEN INVALID_CURSOR OR VALUE_ERROR THEN  
   DBMS_OUTPUT.PUT_LINE('CURSORUL NU A FOST DESCHIS SAU VARIABILA ARE O DIMENSIUNE PREA MICA');
   WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('A APARUT O EXCEPTIE');
     DBMS_OUTPUT.PUT_LINE(SQLERRM);
     DBMS_OUTPUT.PUT_LINE(SQLCODE);     
END;
/

DECLARE 
  ESTE_MANAGER EXCEPTION;
  PRAGMA EXCEPTION_INIT(ESTE_MANAGER,-2292);
BEGIN
  DELETE FROM ANGAJATI WHERE ID_ANGAJAT=100;
  EXCEPTION
  WHEN ESTE_MANAGER THEN
     DBMS_OUTPUT.PUT_LINE('NU POT STERGE ANGAJATUL, SE INCALCA UN FK');
END;
/

FOLOSIND O EXCEPTIE SA SE REZOLVE URMATOAREA CERINTA
SA SE ADAUGE UN ANGAJAT CU ID-UL CITIT DE LA TASTARU SI SALARIUL CITIT DE LA TASTATURA
DACA ANGAJATUL EXISTA, I SE VA MODIFCA SALARIUL CU CEL CITIT


ACCEPT P_ID_ANG PROMPT "INTRODUCETI ID-UL ANGAJATULUI" 
ACCEPT P_SALARIUL PROMPT "INTRODUCETI SALARIUL ANGAJATULUI" 
BEGIN
INSERT INTO ANGAJATI (ID_ANGAJAT, NUME, EMAIL, ID_FUNCTIE,DATA_ANGAJARE, SALARIUL) VALUES
  (&P_ID_ANG,'JOHNSON','JOHNSON@GMAIL.COM','SA_REP',SYSDATE-30, &P_SALARIUL);
  EXCEPTION 
   WHEN DUP_VAL_ON_INDEX THEN
     UPDATE ANGAJATI SET SALARIUL=&P_SALARIUL WHERE ID_ANGAJAT=&P_ID_ANG;
END;
/
  

SELECT * FROM ANGAJATI;

-- SA SE CONSTRUIASCA TABELA PERSOANE(ID_PERS,NUME,PRENUME)
-- DACA TABELA EXISTA SA SE STEARGA TABELA CLIENTI

IN PLSQL PUTEM RULA INSTRUCTIUNI LMD SI LCT DIRECT
PUTEM RULA INSTRUCTIUNI LDD SI LCD FOLOSIND EXECUTE IMMEDIATE SAU DBMS_SQL

DECLARE 
 TABELA_EXISTA EXCEPTION;
 PRAGMA EXCEPTION_INIT(TABELA_EXISTA,-955);
BEGIN
EXECUTE IMMEDIATE 'CREATE TABLE PERSOANE(ID_PERS NUMBER,NUME VARCHAR2(30),PRENUME VARCHAR2(30))';
DBMS_OUTPUT.PUT_LINE('AM CREAT TABELA');
EXECUTE IMMEDIATE 'INSERT INTO PERSOANE VALUES(1,''POPESCU'',''MARIUS'')';
DBMS_OUTPUT.PUT_LINE('AM ADAUGAT RANDUL');
COMMIT;
EXCEPTION WHEN TABELA_EXISTA THEN
    EXECUTE IMMEDIATE 'DROP TABLE PERSOANE';
    DBMS_OUTPUT.PUT_LINE('AM STERS TABELA');
END;
/
SELECT * FROM PERSOANE;

