SET SERVEROUTPUT ON

CREATE OR REPLACE PROCEDURE MARESTE_PRET_PROD3(P_ID_PRODUS NUMBER, P_PROCENT NUMBER DEFAULT 5,P_PRET_NOU OUT NUMBER) IS
BEGIN
    UPDATE PRODUSE SET PRET_LISTA=PRET_LISTA*(100+P_PROCENT)/100 WHERE ID_PRODUS=NVL(P_ID_PRODUS,ID_PRODUS)
    RETURNING PRET_LISTA INTO P_PRET_NOU;
    EXCEPTION
        WHEN TOO_MANY_ROWS THEN 
        UPDATE PRODUSE SET PRET_LISTA=PRET_LISTA*(100+P_PROCENT)/100 WHERE ID_PRODUS=NVL(P_ID_PRODUS,ID_PRODUS);
        P_PRET_NOU:=SQL%ROWCOUNT; --VEI RETURNA NUMARUL DE RANDURI MODIFICARE NU PRETUL NOU
        
END;
/

DECLARE 
P NUMBER;
BEGIN
MARESTE_PRET_PROD3(P_PRET_NOU=>P,P_ID_PRODUS=>23,P_PROCENT=>10);
IF P IS NOT NULL THEN
DBMS_OUTPUT.PUT_LINE('PRETUL NOU ESTE' ||P);
END IF;
END;
/


DECLARE 
P NUMBER;
BEGIN
MARESTE_PRET_PROD3(P_PRET_NOU=>P);
IF P IS NOT NULL THEN
DBMS_OUTPUT.PUT_LINE('PRETUL NOU ESTE' ||P);
ELSE
DBMS_OUTPUT.PUT_LINE('NU S-A MODIFICAT NICIUN PRODUS');
END IF;
END;
/

-- SA SE CONSTRUIASACA O PROCEDURA CARE PRIMESTE O CATEG DE PRODUSE SI AFISEAZA DENUMIREA 
--FIECAURI PRODUS DIN ACEEA CATEGORIE PRECUM SI VALOAREA TOTALA A COMENZIILOR
--PT FIECARE PRODUS.DACA CATEGORIA NU EXISTA, SA SE RIDICE O EXCEPTIE

CREATE OR REPLACE PROCEDURE AFISARE_PROD(P_CATEGORIE VARCHAR2) IS
CURSOR C IS
    SELECT DENUMIRE_PRODUS,
    SUM(PRET * CANTITATE) as VALOARE
    FROM PRODUSE P
    JOIN RAND_COMENZI R ON P.ID_PRODUS = R.ID_PRODUS
    WHERE CATEGORIE=P_CATEGORIE
    GROUP BY DENUMIRE_PRODUS;
    R C%ROWTYPE;
BEGIN
    OPEN C;
    LOOP
    FETCH C INTO R;
    EXIT WHEN C%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(R.DENUMIRE_PRODUS||'->'||R.VALOARE);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('NUMAR PROCEDURA PT CARE EXISTA COMENZI:'|| C%ROWCOUNT);
    
    IF C%ROWCOUNT=0 THEN
        RAISE_APPLICATION_ERROR(-20000,'NU SUNT PRODUSE IN ACEA CATEGORIE');
    END IF;
    CLOSE C;
END;
/

DECLARE
    NU_EXISTA_PROD EXCEPTION;
    PRAGMA EXCEPTION_INIT(NU_EXISTA_PROD,-20000);
BEGIN
     AFISARE_PROD(P_CATEGORIE=>'office2');
EXCEPTION
    WHEN NU_EXISTA_PROD THEN
    DBMS_OUTPUT.PUT_LINE('A APARUT O EXCEPTIE:'||SQLERRM);
END;
/

--SA SE CONSTRUIASAC O FUNCTIE CARE PRIMESTE ID UL UNUI PRODUS IS RETURNEAZA 
--VALOAREA TOTALA A COMENZILOR PT REPSECTIVUL PRODUS
--SA SE APELEZE DINTR UN CURSOR

CREATE OR REPLACE FUNCTION GET_VAL_COM_PROD(P_ID_PRODUS NUMBER) RETURN NUMBER IS
V_VAL NUMBER;
BEGIN
    SELECT 
    SUM(PRET * CANTITATE)
    INTO V_VAL
    FROM RAND_COMENZI
    WHERE ID_PRODUS = P_ID_PRODUS;
    
    RETURN NVL(V_VAL,0);
END;
/

SELECT * FROM RAND_COMENZI ORDER BY ID_PRODUS;

BEGIN
DBMS_OUTPUT.PUT_LINE('VALOARE COMENZI:'||GET_VAL_COM_PROD(1820));
END;
/

DECLARE 
V_VAL NUMBER;
BEGIN
V_VAL:=GET_VAL_COM_PROD(1820);
DBMS_OUTPUT.PUT_LINE('VALOARE COMENZI:'||V_VAL);
END;
/


--FUNCTIILE DEFINITIE IN PL POT FUNCTIA CA SI FUNCTII SQL IN COMENZI SQL
SELECT ID_PRODUS,DENUMIRE_PRODUS,GET_VAL_COM_PROD(ID_PRODUS) VAL FROM PRODUSE
WHERE GET_VAL_COM_PROD(ID_PRODUS)>5000
ORDER BY GET_VAL_COM_PROD(ID_PRODUS)DESC;



DECLARE 
CURSOR C IS SELECT ID_PRODUS,DENUMIRE_PRODUS,GET_VAL_COM_PROD(ID_PRODUS) VAL FROM PRODUSE
WHERE GET_VAL_COM_PROD(ID_PRODUS)>5000
ORDER BY GET_VAL_COM_PROD(ID_PRODUS)DESC;

BEGIN
    FOR R IN C LOOP
        DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS||'->'||R.DENUMIRE_PRODUS||'->'||R.VAL);
    END LOOP;
END;
/


--PACHETE GRUPEAZA FUNCTII SI PROCEDURI +VARAIBILE, CURSORI,EXCEPTII,TYPE URI ETC
--PACHETELE AU 2 COMP:
--SPECIFICATII -SPEC(PUBLICA)
--             -BODY(PRIVATA) -AICI AVEM IMPLEMENTARILE


CREATE OR REPLACE PACKAGE MY_PACK IS
V_COTA NUMBER(2):=21;
PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER);
PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER,N3 NUMBER); --PUTEM SUPRAINCARCA FUNCTII SI PROCEDURI IN INTERIORUL PACHETULUI
FUNCTION MULTIPLY_NUMBERS(N1 NUMBER,N2 NUMBER) RETURN NUMBER;
END;
/

--IN BODY TRB SA IMPLEMENTEZ CEL PUTIN FUNCTIILE SI PROCEDURILE DIN SPEC
--SE POT CONSTRUI SI ALTE FUNCTII SI PROCEDURI PRIVATE
CREATE OR REPLACE PACKAGE BODY MY_PACK IS
V_COTA NUMBER(2):=21;

PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER) IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('SUMA ESTE='||(N1+N2));
END;

PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER,N3 NUMBER) IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('SUMA ESTE='||(N1+N2+N3));
END;

FUNCTION MULTIPLY_NUMBERS(N1 NUMBER,N2 NUMBER) RETURN NUMBER IS
BEGIN
    RETURN N1*N2;
END;
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('COTA='||MY_PACK.V_COTA);
    MY_PACK.V_COTA:=27;
    DBMS_OUTPUT.PUT_LINE('COTA='||MY_PACK.V_COTA);
    MY_PACK.ADD_NUMBERS(10,20);
    MY_PACK.ADD_NUMBERS(10,30,15);
END;
/