SET SERVEROUTPUT ON
--PACHETE GRUPEAZA FUNCTII SI PROCEDURI +VARAIBILE, CURSORI,EXCEPTII,TYPE URI ETC
--PACHETELE AU 2 COMP:
--SPECIFICATII -SPEC(PUBLICA)
--             -BODY(PRIVATA) -AICI AVEM IMPLEMENTARILE


CREATE OR REPLACE PACKAGE MY_PACK IS
V_COTA NUMBER(2):=21;
PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER);
PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER,N3 NUMBER); --PUTEM SUPRAINCARCA FUNCTII SI PROCEDURI IN INTERIORUL PACHETULUI
FUNCTION MULTIPLY_NUMBERS(N1 NUMBER,N2 NUMBER) RETURN NUMBER;
END;
/

--IN BODY TRB SA IMPLEMENTEZ CEL PUTIN FUNCTIILE SI PROCEDURILE DIN SPEC
--SE POT CONSTRUI SI ALTE FUNCTII SI PROCEDURI PRIVATE
CREATE OR REPLACE PACKAGE BODY MY_PACK IS
V_COTA NUMBER(2):=21;

PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER) IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('SUMA ESTE='||(N1+N2));
END;

PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER,N3 NUMBER) IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('SUMA ESTE='||(N1+N2+N3));
END;

FUNCTION MULTIPLY_NUMBERS(N1 NUMBER,N2 NUMBER) RETURN NUMBER IS
BEGIN
    RETURN N1*N2;
END;
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('COTA='||MY_PACK.V_COTA);
    MY_PACK.V_COTA:=27;
    DBMS_OUTPUT.PUT_LINE('COTA='||MY_PACK.V_COTA);
    MY_PACK.ADD_NUMBERS(10,20);
    MY_PACK.ADD_NUMBERS(10,30,15);
END;
/


--SA SE CONSTRUIASAC UN PACHET CARE CONTINE 
--O FUNCTIE CARE PRIMESTE CA PARAMETRUL ID UL UNUI PRODUS SI UN AN CALENDARISITIC(EX 2019)
--FUNCTIA VA RETURNA VALOAREA TOTALA PENTRU COMENZILE PRODUSULUI RESPECTIV IN ANUL RESPECTOV
-- O PROCEDURA CARE APELEAZA FUNCTIA DINTR UN CURSOR,PROCEDURA VA DECLANSA O EXCEPTIE DEFINITA DE UTILIZATOR
--EXCEPTIA SE VA DECLANSA DACA VAL COMENZILOR PENTRU ACEL AN <500.000
--SA SE APELEZE PROCEDURA DINTR UN BLOC ANONIMC, SA SE TRATEZE EXCEPTIA FARA A FOLOSI OTHERS


CREATE OR REPLACE PACKAGE PACK IS
FUNCTION TOTAL_VANZARI(P_ID_PRODUS NUMBER,P_AN NUMBER)RETURN NUMBER;
PROCEDURE AFISARE_TOTAL(P_AN NUMBER);
VAL_MICA EXCEPTION;
PRAGMA EXCEPTION_INIT(VAL_MICA,-200001);
END;
/

CREATE OR REPLACE PACKAGE BODY PACK IS
    FUNCTION TOTAL_VANZARI(P_ID_PRODUS NUMBER,P_AN NUMBER)RETURN NUMBER IS
    V_VAL NUMBER;
    BEGIN
        SELECT SUM(PRET*CANTITATE) INTO V_VAL
        FROM COMENZI C
        JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
        WHERE EXTRACT(YEAR FROM DATA)=P_AN AND R.ID_PRODUS=P_ID_PRODUS;
        RETURN NVL(V_VAL,0);
    END;
    PROCEDURE AFISARE_TOTAL(P_AN NUMBER) IS
        CURSOR C IS 
        SELECT ID_PRODUS,DENUMIRE_PRODUS,TOTAL_VANZARI(ID_PRODUS,P_AN) VAL
        FROM PRODUSE
        ORDER BY VAL DESC;
        
        R C%ROWTYPE;
        V_SUMA NUMBER DEFAULT 0;
        BEGIN
            OPEN C;
            LOOP
                FETCH C INTO R;
                EXIT WHEN C%NOTFOUND;
                DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS||' '||R.DENUMIRE_PRODUS||' '||R.VAL);
                V_SUMA:=V_SUMA+R.VAL;
            END LOOP;
            CLOSE C;
            
             IF  V_SUMA<7000000 THEN
                    RAISE_APPLICATION_ERROR(-20001,'SUMA TOTALA ESTE MAI MICA');
            END IF;
        END;
END;
/

--EXCEPTIILE POT FI DECLARATE SI ASOCIOATE IN PARTEA PBULICA A UNUI PACHET
BEGIN
    PACK.AFISARE_TOTAL(2020);
EXCEPTION
    WHEN PACK.VAL_MICA THEN
        DBMS_OUTPUT.PUT_LINE('Eroare'); 
END;
/


