/*- RUN TIME ERRORS
    EXCEPTII
      - IMPLICITE
          - PREDEFINITE: NO_DATA_FOUND, TOO_MANY_ROWS, DUP_VAL_ON_INDEX, INVALID_CURSOR...
          - NON-PREDEFINITE: AU COD DE EXCEPTIE DAR NU AU SI HANDLER-UL EXCEPTIEI
      - EXPLICITE
          - DEFINITE DE UTILIZATOR
*/
          
          
SET SERVEROUTPUT ON 
DECLARE
    EX_PRODUS EXCEPTION;
    NU_EXISTA EXCEPTION;
    PRAGMA EXCEPTION_INIT(EX_PRODUS,-2292);
BEGIN
    DELETE FROM PRODUSE WHERE ID_PRODUS>=35000;
    IF SQL%NOTFOUND THEN
        RAISE NU_EXISTA ; --RIDIC ORICE EXCEPTIE PREDEFINITA PE CARE O DORESC
        --DBMS_OUTPUT.PUT_LINE('NU S A STERS NICIUN PRODUS');
    ELSE
    DBMS_OUTPUT.PUT_LINE('S-AU STERS'||SQL%ROWCOUNT||'PRDOSUE');
    END IF;
    
    EXCEPTION
    WHEN EX_PRODUS THEN
        DBMS_OUTPUT.PUT_LINE('NU SE POATE STERGE ACEST PRODUS');
    WHEN NU_EXISTA  THEN
        DBMS_OUTPUT.PUT_LINE('A APARUT EXCEPTIA');
    
END;
/
SELECT * FROM PRODUSE WHERE ID_PRODUS NOT IN(SELECT ID_PRODUS FROM RAND_COMENZI) ORDER BY 1;

--INTERVALUL DE CODURI PT EXCEPTILE DEFINITE DE UTILIZATOR ESTE  -20999 ... -20000

DECLARE
    EX_PRODUS EXCEPTION;
    NU_EXISTA EXCEPTION;
    PRAGMA EXCEPTION_INIT(EX_PRODUS,-2292);
    PRAGMA EXCEPTION_INIT(NU_EXISTA,-20000);
BEGIN
    DELETE FROM PRODUSE WHERE ID_PRODUS>=35000;
    IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR(-20000,'NU EXISTA PRODUSUL'); --MODALITATEA CLASICA DE A DECLANSA EXCEPTII DEF DE UTILIZATOR
    ELSE
    DBMS_OUTPUT.PUT_LINE('S-AU STERS'||SQL%ROWCOUNT||'PRDOSUE');
    END IF;
    
    EXCEPTION
    WHEN EX_PRODUS THEN
        DBMS_OUTPUT.PUT_LINE('NU SE POATE STERGE ACEST PRODUS');
    WHEN NU_EXISTA  THEN
        DBMS_OUTPUT.PUT_LINE('A APARUT EXCEPTIA');
    
END;
/
--AM CONSTRUIT BLOCURI ANONIM

/*
PROCEDURI SI FUNCTII =PUTEM SA STOCAM COD IN BAZA DE DATE 

*/

CREATE OR REPLACE PROCEDURE STERGE_PRODUS IS
EX_PRODUS EXCEPTION;
NU_EXISTA EXCEPTION;
PRAGMA EXCEPTION_INIT(EX_PRODUS,-2292);
PRAGMA EXCEPTION_INIT(NU_EXISTA,-20000);
BEGIN
    DELETE FROM PRODUSE WHERE ID_PRODUS>=35000;
    IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR(-20000,'NU EXISTA PRODUSUL'); --MODALITATEA CLASICA DE A DECLANSA EXCEPTII DEF DE UTILIZATOR
    ELSE
    DBMS_OUTPUT.PUT_LINE('S-AU STERS'||SQL%ROWCOUNT||'PRDOSUE');
    END IF;
    
    EXCEPTION
    WHEN EX_PRODUS THEN
        DBMS_OUTPUT.PUT_LINE('NU SE POATE STERGE ACEST PRODUS');
    WHEN NU_EXISTA  THEN
        DBMS_OUTPUT.PUT_LINE('A APARUT EXCEPTIA'||SQLERRM);
    
END;
/

EXEC STERGE_PRODUS; --APEL TIP PLQSQL

CALL STERGE_PRODUS(); --APEL TIP SQL

--putem trata execptia in blocul operator sau in bloc anonim
--APELEZ PROCEDURA DINTR UN BLOC ANONIM
DECLARE
NU_EXISTA EXCEPTION;
PRAGMA EXCEPTION_INIT(NU_EXISTA,-20000);
BEGIN
    STERGE_PRODUS; --DACA O EXCEPTIE NU ESTE TRATATA IN SUBPROGRAM
                    --ATUNCI EA ESTE "PROPAGATA" BLOCULUI APELATOR CARE POATE LA RANDUL SAU SA O TRATEZE
    EXCEPTION 
    WHEN NU_EXISTA THEN
     DBMS_OUTPUT.PUT_LINE('A APARUT EXCEPTIA'||SQLERRM);
END;
/

/*SUBPROGRAMELE POT AVEA PARAMETRII
IN-(VAR IMPLICITA)
OUT
IN OUT
*/

--OR REPLACE POATE SA LIPSEASACA, DACA EA EXISTA TREBUIE SA II DAM INAINTE DROP PROCEDURE
--SA SE MODIFICE PROCEDURA ASTFEL INCAT SA SE AFISEZE SI PRRETUL NOU
CREATE OR REPLACE PROCEDURE MARESTE_PRET_PROD1(P_ID_PRODUS NUMBER, P_PROCENT NUMBER) IS
V_PRET_NOU NUMBER;
BEGIN
    UPDATE PRODUSE SET PRET_LISTA=PRET_LISTA*(100+P_PROCENT)/100 WHERE ID_PRODUS=P_ID_PRODUS;
    SELECT PRET_LISTA
        INTO V_PRET_NOU
        FROM PRODUSE
        WHERE ID_PRODUS = P_ID_PRODUS;
        DBMS_OUTPUT.PUT_LINE('Pretul nou este: ' || V_PRET_NOU);
    EXCEPTION 
        WHEN NO_DATA_FOUND THEN NULL;
    
END;
/

SELECT ID_PRODUS,DENUMIRE_PRODUS,PRET_LISTA FROM PRODUSE;
EXEC MARESTE_PRET_PROD1(2378,10);


BEGIN
MARESTE_PRET_PROD1(2378,10);
END;
/

--pt exceptie
BEGIN
MARESTE_PRET_PROD1(5378,10);
END;
/

CREATE OR REPLACE PROCEDURE MARESTE_PRET_PROD2(P_ID_PRODUS NUMBER, P_PROCENT NUMBER) IS
V_PRET_NOU NUMBER;
BEGIN
    UPDATE PRODUSE SET PRET_LISTA=PRET_LISTA*(100+P_PROCENT)/100 WHERE ID_PRODUS=P_ID_PRODUS
    RETURNING PRET_LISTA INTO V_PRET_NOU;
    
    IF SQL%FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Pretul nou este: ' || V_PRET_NOU);
    END IF;
    
END;
/

CREATE OR REPLACE PROCEDURE MARESTE_PRET_PROD3(P_ID_PRODUS NUMBER, P_PROCENT NUMBER,P_PRET_NOU OUT NUMBER) IS
BEGIN
    UPDATE PRODUSE SET PRET_LISTA=PRET_LISTA*(100+P_PROCENT)/100 WHERE ID_PRODUS=P_ID_PRODUS
    RETURNING PRET_LISTA INTO P_PRET_NOU;
END;
/

DECLARE 
P NUMBER;
BEGIN
MARESTE_PRET_PROD3(7378,10,P);
IF P IS NOT NULL THEN
DBMS_OUTPUT.PUT_LINE('PRETUL NOU ESTE' ||P);
END IF;
END;
/



