SET SERVEROUTPUT ON

DECLARE 
    TYPE T_ANG IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER;
    V T_ANG;
    I PLS_INTEGER;
BEGIN
    SELECT NUME
    BULK COLLECT INTO V
    FROM ANGAJATI
    WHERE ID_FUNCTIE='SA_REP'
    AND SALARIUL BETWEEN 5000 AND 9000
    ORDER BY SALARIUL DESC;
    
    DBMS_OUTPUT.PUT_LINE(V.COUNT);
    DBMS_OUTPUT.PUT_LINE(V.FIRST);
    DBMS_OUTPUT.PUT_LINE(V.LAST);
    
    FOR I IN 1..V.COUNT LOOP
        DBMS_OUTPUT.PUT_LINE(V(I));
    END LOOP;
    
    
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(V(I));
        I:=V.NEXT(I);
    END LOOP;
END;
/

DECLARE
    TYPE R_ANG IS RECORD(
    NUME VARCHAR2(30),
    PRENUME VARCHAR2(30),
    SALARIUL NUMBER);
    
    TYPE T_ANG IS TABLE OF R_ANG INDEX BY PLS_INTEGER;
    V T_ANG;
    I PLS_INTEGER;
    
BEGIN
    SELECT NUME,PRENUME,SALARIUL    
    BULK COLLECT INTO V -- 
    FROM ANGAJATI
    WHERE ID_FUNCTIE = 'SA_REP'
    AND SALARIUL BETWEEN 5000 AND 9000
    ORDER BY SALARIUL DESC;
   
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE(V(I).NUME || ' ' ||V(I).PRENUME||' ' ||'Salariul='||V(I).SALARIUL);
        I:=V.NEXT(I);
    END LOOP;
END;
/


DECLARE
    TYPE R_PR IS RECORD(
    DENUMIRE_PRODUS VARCHAR2(50),
    VALOARE_TOTALA NUMBER,
    DATA_ULTIMA TIMESTAMP);
    
    TYPE T_PR IS TABLE OF R_PR INDEX BY PLS_INTEGER;
    V T_PR;
    I PLS_INTEGER;
BEGIN
    SELECT P.DENUMIRE_PRODUS,
        SUM(R.CANTITATE * R.PRET) AS VALOARE_TOTALA,
        MAX(C.DATA) AS DATA_ULTIMA
        BULK COLLECT INTO V
        FROM PRODUSE P
        JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
        JOIN COMENZI C ON R.ID_COMANDA=C.ID_COMANDA
        GROUP BY P.DENUMIRE_PRODUS
        ORDER BY MAX(C.DATA) DESC;
        
        I:=V.FIRST;
        WHILE I IS NOT NULL LOOP
         DBMS_OUTPUT.PUT_LINE(V(I).denumire_produs || ' || Total=' || V(I).valoare_totala ||  ' || Ultima comanda=' || V(I).data_ultima);
            I:=V.NEXT(I);
        END LOOP;
        
END;
/


DECLARE
    TYPE R_PR IS RECORD(
    DENUMIRE_PRODUS VARCHAR2(50),
    VALOARE_TOTALA NUMBER,
    DATA_ULTIMA TIMESTAMP);
    
    TYPE T_PR IS TABLE OF R_PR; --NESTED TABLE
    V T_PR;
    I PLS_INTEGER;
    
BEGIN
    SELECT P.DENUMIRE_PRODUS,
    SUM(R.CANTITATE * R.PRET) AS VALOARE_TOTALA,
    MAX(C.DATA) AS DATA_ULTIMA
    BULK COLLECT INTO V
    FROM PRODUSE P
    JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
    JOIN COMENZI C ON R.ID_COMANDA=C.ID_COMANDA
    GROUP BY P.DENUMIRE_PRODUS
    ORDER BY MAX(C.DATA) DESC;
    
    --V.DELETE(5,180);--  NU PUTEM STERGE VALORI DE LA MIJLOC
    V.TRIM; --STERGE DE LA INCEPUTUL COLECTIEI
    V.TRIM(5);-- STERGE ULTIMELE 5 ELEMENTE
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
     DBMS_OUTPUT.PUT_LINE(V(I).denumire_produs || ' || Total=' || V(I).valoare_totala ||  ' || Ultima comanda=' || V(I).data_ultima);
     I:=V.NEXT(I);
    
    END LOOP;
    
END;
/



DECLARE 
    CURSOR C IS SELECT
        NUME_CLIENT,
        PRENUME_CLIENT,
        LIMITA_CREDIT
        FROM CLIENTI
        WHERE ID_CLIENT IN(
        SELECT ID_CLIENT 
        FROM COMENZI
        GROUP BY ID_CLIENT
        HAVING COUNT(*)>=2)
        ORDER BY LIMITA_CREDIT DESC
        FETCH FIRST 5 ROWS ONLY;
R C%ROWTYPE;
BEGIN
    IF NOT C%ISOPEN THEN
        OPEN C;
    END IF;
    LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(C%ROWCOUNT);
    END LOOP;
    CLOSE C;
END;
/


DECLARE
    CURSOR C IS SELECT DENUMIRE_DEPARTAMNENT
    FROM DEPARTAMENTE
    WHERE ID_DEPARTAMENT IN(
    SELECT ID_DEPARTAMENT
    FROM ANGAJATI
    GROUP BY ID_DEPARTAMENT
    HAVING MAX(SALARIUL)<=10000);
        
    R C%ROWTYPE;
BEGIN
    OPEN C;
    LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(C%ROWCOUNT||' '||R.DENUMIRE_DEPARTAMENT);
        END LOOP;
        
        DBMS_OUTPUT.PUT_LINE('Nr departamente:'||C%ROWCOUNT);
        CLOSE C;
END;
/



DECLARE 
    CURSOR C IS SELECT
        P.CATEGORIE,
        SUM(R.PRET*R.CANTITATE) AS VAL_T
        FROM PRODUSE P
        JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
        GROUP BY P.CATEGORIE
        HAVING SUM(R.PRET*R.CANTITATE)>50000;
     R C%ROWTYPE;
BEGIN
    OPEN C;
    LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(R.CATEGORIE);
    END LOOP;
END;
/




DECLARE
    CURSOR C IS SELECT
    P.CATEGORIE,
    SUM(R.PRET*R.CANTITATE) AS VAL_T
    FROM PRODUSE P
    JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
    GROUP BY P.CATEGORIE
    HAVING SUM(R.PRET*R.CANTITATE)>50000;
    
    CURSOR D(P_CATEG VARCHAR2) IS SELECT
        P.DENUMIRE_PRODUS,
        CATEGORIE,
        SUM(R.CANTITATE*R.PRET) AS VAL_T
        FROM PRODUSE P
        JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
        WHERE P.CATEGORIE=P_CATEG
        GROUP BY P.DENUMIRE_PRODUS,CATEGORIE;
        
BEGIN
    FOR R IN C LOOP
        DBMS_OUTPUT.PUT_LINE(R.CATEGORIE);
        FOR S IN D(R.CATEGORIE) LOOP
            DBMS_OUTPUT.PUT_LINE(S.DENUMIRE_PRODUS||':'||S.VAL_T);
        END LOOP;
    END LOOP;

END;
/



DECLARE
    CURSOR C1 IS SELECT
        C.ID_CLIENT,
        C.NUME_CLIENT,
        C.PRENUME_CLIENT,
        COUNT(*) NR_COM
        FROM CLIENTI C
        JOIN COMENZI CO ON C.ID_CLIENT=CO.ID_CLIENT
        GROUP BY C.ID_CLIENT,C.NUME_CLIENT,C.PRENUME_CLIENT
        ORDER BY COUNT(*) DESC 
        FETCH FIRST 1 ROWS WITH TIES;
        
    CURSOR C2(P_ID NUMBER) IS SELECT
        C.ID_COMANDA,
        C.DATA,
        SUM(R.PRET*R.CANTITATE) AS VAL_TOT
        FROM COMENZI C
        JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
        WHERE C.ID_CLIENT=P_ID
        GROUP BY C.ID_COMANDA,C.DATA;
    
BEGIN
    FOR R IN C1 LOOP
        DBMS_OUTPUT.PUT(R.ID_CLIENT);
        FOR R2 IN C2(R.ID_CLIENT) LOOP
            DBMS_OUTPUT.PUT_LINE(R2.ID_COMANDA||' '||R2.DATA);
        
        END LOOP;
    END LOOP;
END;
/

DECLARE

    CURSOR C IS SELECT
        P.ID_PRODUS,
        DENUMIRE_PRODUS,
        PRET_LISTA
        FROM PRODUSE P
        WHERE P.ID_PRODUS IN(
        SELECT R.ID_PRODUS
        FROM RAND_COMENZI R
        GROUP BY R.ID_PRODUS
        HAVING COUNT(R.ID_PRODUS)>=5)FOR UPDATE WAIT 10;
BEGIN
    FOR R IN C LOOP
        UPDATE PRODUSE
        SET PRET_LISTA=PRET_LISTA*1.05
        WHERE CURRENT OF C;
         DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS||' '||R.DENUMIRE_PRODUS||' '||R.PRET_LISTA); 
        --AFISEAZA DATELE DE LA DESCHIDEREA CURSORULUI NU CELE ACTUALIZATE
    END LOOP;
END;
/

DECLARE
    EX_PRODUS EXCEPTION;
    NU_EXISTA EXCEPTION;
    PRAGMA EXCEPTION_INIT(EX_PRODUS,-2292);
    PRAGMA EXCEPTION_INIT(NU_EXISTA,-20000);
BEGIN
    DELETE FROM PRODUSE WHERE ID_PRODUS>=350000;
    IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR(-20000,'NU EXISTA PROD');
    END IF;
    
    EXCEPTION 
        WHEN EX_PRODUS THEN
             DBMS_OUTPUT.PUT_LINE('NU SE POATE STERGE ACEST PRODUS');
    WHEN NU_EXISTA  THEN
        DBMS_OUTPUT.PUT_LINE('A APARUT EXCEPTIA');
END;
/
    

CREATE OR REPLACE PROCEDURE STERGE_PRODUS IS

EX_PRODUS EXCEPTION;
NU_EXISTA EXCEPTION;
PRAGMA EXCEPTION_INIT(EX_PRODUS,-2292);
PRAGMA EXCEPTION_INIT(NU_EXISTA,-20000);
BEGIN
    DELETE FROM PRODUSE WHERE ID_PRODUS>=35000;
    IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR(-20000,'NU EXISTA PRODUSUL'); --MODALITATEA CLASICA DE A DECLANSA EXCEPTII DEF DE UTILIZATOR
    ELSE
    DBMS_OUTPUT.PUT_LINE('S-AU STERS'||SQL%ROWCOUNT||'PRDOSUE');
    END IF;
    
    EXCEPTION
    WHEN EX_PRODUS THEN
        DBMS_OUTPUT.PUT_LINE('NU SE POATE STERGE ACEST PRODUS');
    WHEN NU_EXISTA  THEN
        DBMS_OUTPUT.PUT_LINE('A APARUT EXCEPTIA'||SQLERRM);
    
END;
/

EXEC STERGE_PRODUS;

DECLARE 
    NU_EXISTA EXCEPTION;
    PRAGMA EXCEPTION_INIT(NU_EXISTA,-20000);
BEGIN
    STERGE_PRODUS;
    EXCEPTION
        WHEN NU_EXISTA THEN
            DBMS_OUTPUT.PUT_LINE('A APARUT EXCEPTIA'||SQLERRM);
END;
/


CREATE OR REPLACE PROCEDURE MARESTE_PRET_PROD1(P_ID_PRODUS NUMBER, P_PROCENT NUMBER) IS
V_PRET_NOU NUMBER;
BEGIN
    UPDATE PRODUSE 
    SET PRET_LISTA=PRET_LISTA*(100+P_PROCENT)/100
    WHERE ID_PRODUS=P_ID_PRODUS;
    SELECT PRET_LISTA
    INTO V_PRET_NOU
    FROM PRODUSE
    WHERE ID_PRODUS=P_ID_PRODUS;
     DBMS_OUTPUT.PUT_LINE('Pretul nou este: ' || V_PRET_NOU);
    EXCEPTION 
        WHEN NO_DATA_FOUND THEN NULL;

END;
/

BEGIN
MARESTE_PRET_PROD1(2378,10);
END;
/

CREATE OR REPLACE PROCEDURE AFISARE_PROD(P_CATEGORIE VARCHAR2) IS
    CURSOR C IS SELECT
        DENUMIRE_PRODUS,
        SUM(R.PRET*R.CANTITATE) AS VALOARE
        FROM PRODUSE P
        JOIN RAND_COMENZI R ON P.ID_PRODUS=R.ID_PRODUS
        WHERE CATEGORIE=P_CATEGORIE
        GROUP BY DENUMIRE_PRODUS;
    R C%ROWTYPE;
BEGIN
    OPEN C;
    LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(R.DENUMIRE_PRODUS||' '||R.VALOARE);
    END LOOP;
     DBMS_OUTPUT.PUT_LINE('NUMAR PROCEDURA PT CARE EXISTA COMENZI:'|| C%ROWCOUNT);
     
     IF C%ROWCOUNT=0 THEN
        RAISE_APPLICATION_ERROR(-20000,'NU SUNT PRODUSE IN ACEA CATEGORIE');
    END IF;
    CLOSE C;
END;
/

DECLARE
    NU_EXISTA_PROD EXCEPTION;
    PRAGMA EXCEPTION_INIT(NU_EXISTA_PROD,-20000);
BEGIN
    AFISARE_PROD('office2');
    EXCEPTION
        WHEN NU_EXISTA_PROD THEN
            DBMS_OUTPUT.PUT_LINE(' A APARUT EXCEPTIA:'||SQLERRM);
END;
/


CREATE OR REPLACE FUNCTION GET_VAL_COM_PROD(P_ID_PRODUS NUMBER) RETURN NUMBER IS
V_VAL NUMBER;
BEGIN
    SELECT 
    SUM(PRET*CANTITATE)
    INTO V_VAL
    FROM RAND_COMENZI
    WHERE ID_PRODUS=P_ID_PRODUS;
    
    RETURN NVL(V_VAL,0);
END;
/

DECLARE 
    CURSOR C IS SELECT
        ID_PRODUS,
        DENUMIRE_PRODUS,
        GET_VAL_COM_PROD(ID_PRODUS) VAL
        FROM PRODUSE
        WHERE GET_VAL_COM_PROD(ID_PRODUS)>5000
        ORDER BY GET_VAL_COM_PROD(ID_PRODUS) DESC;
BEGIN
    FOR R IN C LOOP
    DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS||'->'||R.DENUMIRE_PRODUS||'->'||R.VAL);
    END LOOP;

END;
/    



CREATE OR REPLACE PACKAGE PACK IS
    V_COTA NUMBER(2):=21;
    PROCEDURE ADD_NUMBERS(N1 NUMBER,N2 NUMBER);
    FUNCTION MULTIPLY_NUMBERS(N1 NUMBER,N2 NUMBER) RETURN NUMBER;
END;
/

CREATE OR REPLACE PACKAGE BODY PACK IS 
 V_COTA NUMBER(2):=21;
 PROCEDURE ADD_NUMBERS(N1 NUMBER, N2 NUMBER) IS
 BEGIN
    DBMS_OUTPUT.PUT_LINE('SUMA ESTE='||(N1+N2));
 END;
 
FUNCTION MULTIPLY_NUMBERS(N1 NUMBER,N2 NUMBER) RETURN NUMBER IS
BEGIN
    RETURN N1*N2;
END;
  
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('COTA='||MY_PACK.V_COTA);
    MY_PACK.V_COTA:=27;
    DBMS_OUTPUT.PUT_LINE('COTA='||MY_PACK.V_COTA);
    MY_PACK.ADD_NUMBERS(10,20);
    
END;
/


CREATE OR REPLACE PACKAGE PK IS
    FUNCTION TOTAL_VANZARI(P_ID_PRODUS NUMBER,P_AN NUMBER) RETURN NUMBER;
    PROCEDURE AFISARE_TOTAL(P_AN NUMBER);
    VAL_MICA EXCEPTION;
    PRAGMA EXCEPTION_INIT(VAL_MICA,-20000);
END;
/

CREATE OR REPLACE PACKAGE BODY PK IS
    FUNCTION TOTAL_VANZARI(P_ID_PRODUS NUMBER,P_AN NUMBER)RETURN NUMBER IS
    V_VAL NUMBER;
    BEGIN
        SELECT SUM(PRET*CANTITATE) INTO V_VAL
        FROM COMENZI C
        JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
        WHERE EXTRACT(YEAR FROM DATA)=P_AN AND R.ID_PRODUS=P_ID_PRODUS;
        
        RETURN NVL(V_VAL,0);
    END;
    
    PROCEDURE AFISARE_TOTAL(P_AN NUMBER) IS
        CURSOR C IS SELECT
            ID_PRODUS,
            DENUMIRE_PRODUS,
            TOTAL_VANZARI(ID_PRODUS,P_AN) VAL
            FROM PRODUSE
            ORDER BY VAL DESC;
        R C%ROWTYPE;
        V_SUMA NUMBER DEFAULT 0;
        BEGIN
            OPEN C;
            LOOP
                FETCH C INTO R;
                EXIT WHEN C%NOTFOUND;
                DBMS_OUTPUT.PUT_LINE(R.ID_PRODUS||' '||R.DENUMIRE_PRODUS||' '||R.VAL);
                V_SUMA:=V_SUMA+R.VAL;
            END LOOP;
            CLOSE C;
            
            IF  V_SUMA<7000000 THEN
                RAISE_APPLICATION_ERROR(-20000,'MAI MICA');
            END IF;
        END;
        
END;
/

BEGIN
    PK.AFISARE_TOTAL(2020);
    EXCEPTION
        WHEN PK.VAL_MICA THEN
            DBMS_OUTPUT.PUT_LINE('A APARUT EROAREA'||SQLERRM);
END;
/



CREATE OR REPLACE TRIGGER VERIF_ORA BEFORE INSERT OR UPDATE OR DELETE ON COMENZI
BEGIN
    IF INSERTING AND TO_CHAR(SYSDATE,'HH24;MI')>='16:00' THEN
        RAISE_APPLICATION_ERROR(-20000,'NU');
     ELSIF UPDATING AND TO_CHAR(SYSDATE,'HH24:MI')>='16:1O' THEN
          RAISE_APPLICATION_ERROR(-20000,'NU SE POT MODIFICA COMENZI DUPA PRA 16:10');
        --DBMS_OUTPUT.PUT_LINE('S-A DECLANSAT TRIGGERUL INAINTEA UNEI OPERATII UPDATE');
    ELSIF DELETING AND TO_CHAR(SYSDATE,'HH24:MI')>='16:20'THEN
        RAISE_APPLICATION_ERROR(-20000,'NU SE POT STERGE COMENZI DUPA PRA 16:20');
        --DBMS_OUTPUT.PUT_LINE('S-A DECLANSAT TRIGGERUL INAINTEA UNEI OPERATII DELETE');
    END IF;
END;
/


CREATE OR REPLACE TRIGGER V BEFORE INSERT ON REGIUNI
DECLARE
    NR NUMBER;
BEGIN
    SELECT COUNT(*) INTO NR
    FROM REGIUNI;
    IF NR>=5 THEN
        RAISE_APPLICATION_ERROR(-20000,'MAXIM 5 RANDURI IN TABELA');
    END IF;
END;
/
SELECT * FROM REGIUNI;
--la triggeri AFTER mai intai se declanseaza restrictiile de integritate,daca este cazul!!!
INSERT INTO REGIUNI VALUES (5, 'Asia');

CREATE OR REPLACE TRIGGER VERIF_SAL BEFORE UPDATE ON ANGAJATI FOR EACH ROW
BEGIN
  DBMS_OUTPUT.PUT_LINE('SE MODOFICA SALARIUL PENTRU '||:NEW.ID_ANGAJAT||' DIN '||:OLD.SALARIUL||' IN '||:NEW.SALARIUL);
END;
/

UPDATE ANGAJATI
SET SALARIUL=SALARIUL*1.01
WHERE ID_ANGAJAT>180;



CREATE OR REPLACE TRIGGER VKL BEFORE UPDATE OF SALARIUL ON ANGAJATI FOR EACH ROW
DECLARE 
    NR NUMBER;
BEGIN
    IF :NEW.SALARIUL<:OLD.SALARIUL THEN
        SELECT COUNT(*) INTO NR
        FROM COMENZI C
        WHERE C.ID_ANGAJAT=:NEW.ID_ANGAJAT;
        
        IF N>=2 THEN
            RAISE_APPLICATION_ERROR(-20000,'ERR');
        END IF;
    END IF;
END;
/

UPDATE ANGAJATI
SET SALARIUL=SALARIUL-5 
WHERE ID_ANGAJAT>140;
