SET SERVEROUTPUT ON

--1
CREATE OR REPLACE PACKAGE PKE IS
    FUNCTION TOTAL_COM(P_ID_CLIENT NUMBER, P_AN NUMBER) RETURN NUMBER;
END;
/

CREATE OR REPLACE PACKAGE BODY PKE IS

    FUNCTION TOTAL_COM(P_ID_CLIENT NUMBER, P_AN NUMBER) RETURN NUMBER IS
    V_VAL NUMBER;
    BEGIN
        SELECT SUM(R.PRET*R.CANTITATE)INTO V_VAL
        FROM COMENZI C
        JOIN RAND_COMENZI R ON C.ID_COMANDA=R.ID_COMANDA
        WHERE EXTRACT(YEAR FROM DATA)=P_AN AND C.ID_CLIENT=P_ID_CLIENT;
        
        RETURN NVL(V_VAL,0);
    END;

END;
/

DECLARE
    TYPE R_ANG IS RECORD(
    id_client number,
    prenume_client varchar2(50),
    nume_client varchar2(50),
    total number);
    
    TYPE T_ANG IS TABLE OF R_ANG INDEX BY PLS_INTEGER;
    V T_ANG;
    I PLS_INTEGER;
BEGIN
    SELECT ID_CLIENT,
    PRENUME_CLIENT,
    NUME_CLIENT,
    PKE.TOTAL_COM(ID_CLIENT,2024) 
    BULK COLLECT INTO V
    FROM CLIENTI
    WHERE nivel_venituri = 'F: 110,000 - 129,999'
    ORDER BY ID_CLIENT ASC;
    
    DBMS_OUTPUT.PUT_LINE('Clienti cu nivelul de venituri F: 110,000 - 129,999 pentru anul 2024:');
    
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE('Clientul:'||V(I).id_client||'-'||V(I).nume_client||' '||V(I).prenume_client||' , total comenzi:'||V(I).total);
        I:=V.NEXT(I);
    END LOOP;
END;
/
    

--2
CREATE OR REPLACE PROCEDURE ACTUALIZEAZA_PRET_PRODUS(P_ID_PRODUS NUMBER,P_PROCENT NUMBER) IS
    CURSOR C IS SELECT
    P.ID_PRODUS,
    P.PRET_LISTA,
    P.PRET_MIN 
    FROM PRODUSE P
    WHERE P.ID_PRODUS=P_ID_PRODUS;
    
    R C%ROWTYPE;
    V_GASIT NUMBER DEFAULT 0;
    
    BEGIN
        OPEN C;
        LOOP
            FETCH C INTO R;
            EXIT WHEN C%NOTFOUND;
            
            V_GASIT:=V_GASIT+1;
            -- Afisam valorile initiale
         DBMS_OUTPUT.PUT_LINE('Produs actualizat: ' || R.ID_PRODUS);
         DBMS_OUTPUT.PUT_LINE('Pret lista initial: ' || R.PRET_LISTA || ', pret lista final: ' || (R.PRET_LISTA * (1 + P_PROCENT/100)));
         DBMS_OUTPUT.PUT_LINE('Pret minim initial: ' || R.PRET_MIN || ', pret minim final: ' || (R.PRET_MIN * (1 + P_PROCENT/100)));
            
            UPDATE PRODUSE 
            SET 
            PRET_LISTA = PRET_LISTA * (1 + P_PROCENT/100),
            PRET_MIN = PRET_MIN * (1 + P_PROCENT/100)
            WHERE ID_PRODUS = R.ID_PRODUS;
        END LOOP;
        CLOSE C;
        
        IF V_GASIT=0 THEN
            RAISE_APPLICATION_ERROR(-20000,'NU EXISTA');
        END IF;
    
    
    END;
    /


DECLARE
    E_EXC EXCEPTION;
    PRAGMA EXCEPTION_INIT(E_EXC, -20000);
BEGIN
    ACTUALIZEAZA_PRET_PRODUS(1733, 10);
EXCEPTION
    WHEN E_EXC THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

--2
CREATE OR REPLACE PROCEDURE ACTUALIZEAZA_LIMITA_CREDIT(P_ID_CLIENT NUMBER,P_PROCENT NUMBER) IS
    CURSOR C IS SELECT
        ID_CLIENT,
        LIMITA_CREDIT
        FROM CLIENTI
        WHERE ID_CLIENT=P_ID_CLIENT;
        
    R C%ROWTYPE;
    V_NR NUMBER DEFAULT 0;
BEGIN
    OPEN C;
    LOOP
        FETCH C INTO R;
        EXIT WHEN C%NOTFOUND;
        
        V_NR:=V_NR+1;
        DBMS_OUTPUT.PUT_LINE('CLIENT ACTUALIZAZT:'||R.ID_CLIENT);
        DBMS_OUTPUT.PUT_LINE('LIMITA CREDIT INITIALA:'||R.LIMITA_CREDIT);
        DBMS_OUTPUT.PUT_LINE('LIMITA CREDIT FINALA:'||(R.LIMITA_CREDIT *(1+P_PROCENT/100)));
        
        UPDATE CLIENTI
        SET LIMITA_CREDIT=R.LIMITA_CREDIT *(1+P_PROCENT/100)
        WHERE ID_CLIENT=R.ID_CLIENT;
    END LOOP;
    CLOSE C;
    
    IF V_NR=0 THEN
        RAISE_APPLICATION_ERROR(-20000,'NU EXISTA CLIENTUL CU ID UL ACESTA');
    END IF;
        
END;
/

DECLARE
    NU_EXI EXCEPTION;
    PRAGMA EXCEPTION_INIT(NU_EXI,-20000);
BEGIN
    ACTUALIZEAZA_LIMITA_CREDIT(101,20);
    
    EXCEPTION
        WHEN NU_EXI THEN
            DBMS_OUTPUT.PUT_LINE('A APARUT EROAREA '||SQLERRM);

END;
/

--3
CREATE OR REPLACE PACKAGE PACK IS
    FUNCTION OBTINE_TOTAL(P_ID_DEPARTAMENT NUMBER,P_AN NUMBER)RETURN NUMBER;
END;
/

CREATE OR REPLACE PACKAGE BODY PACK IS
    
    FUNCTION OBTINE_TOTAL(P_ID_DEPARTAMENT NUMBER,P_AN NUMBER)RETURN NUMBER IS
        V_VAL NUMBER;
    BEGIN
        SELECT 
            SUM(SALARIUL) INTO V_VAL
            FROM ANGAJATI A
            WHERE ID_DEPARTAMENT=P_ID_DEPARTAMENT 
            AND EXTRACT(YEAR FROM DATA_ANGAJARE)=P_AN;
            
        RETURN NVL(V_VAL,0);
    END;
    
END;
/

DECLARE
    TYPE R_SAL IS RECORD(
    ID_DEPARTAMENT NUMBER,
    DENUMIRE_DEPARTAMENT VARCHAR2(30),
    ORAS VARCHAR2(20),
    TOTAL NUMBER);
    
    TYPE T_SAL IS TABLE OF R_SAL INDEX BY PLS_INTEGER;
    V T_SAL;
    I PLS_INTEGER;
BEGIN
    SELECT 
    D.ID_DEPARTAMENT,
    D.DENUMIRE_DEPARTAMENT,
    L.ORAS,
    PACK.OBTINE_TOTAL(D.ID_DEPARTAMENT,2023)
    BULK COLLECT INTO V
    FROM DEPARTAMENTE D
    JOIN LOCATII L ON D.ID_LOCATIE=L.ID_LOCATIE
    WHERE L.ID_TARA='US'
    ORDER BY D.ID_DEPARTAMENT ASC;
    
    I:=V.FIRST;
    WHILE I IS NOT NULL LOOP
        DBMS_OUTPUT.PUT_LINE('Departament '||V(I).ID_DEPARTAMENT||'-'||V(I).DENUMIRE_DEPARTAMENT||'oras:'||V(I).ORAS||'total sal:'||V(I).total);
        I:=V.NEXT(I);
    END LOOP;
    
END;
/


